### Multi-Language

In [1]:
import pandas as pd
import data_enrichment
import importlib

c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\marian\tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\pipelines\text_classification.py:104: UserWarning: `return_all_scores` is now deprecated,  if want a similar functionality use `top_k=None` instead of `return_all_scores=True` or `top_k=1` instead of `return_all_scores=False`.
  warnings.warn(

In [3]:
importlib.reload(data_enrichment)

In [3]:
train_fr = pd.read_json('datasets/competition/ML-ESG-3_Trainset_French.json')
test_fr = pd.read_json('datasets/competition/ML-ESG3_Testset_FR.json')

In [5]:
train_fr

,URL,news_title,news_content,impact_level,impact_length
0,https://www.novethic.fr/actualite/energie/tran...,Interdiction à la location des passoires therm...,"Depuis le 1er janvier, les passoires thermique...",low,More than 5 years
1,https://www.novethic.fr/actualite/energie/tran...,Interdiction à la location des passoires therm...,"Depuis le 1er janvier 2023, les logements les ...",low,More than 5 years
2,https://www.novethic.fr/actualite/energie/tran...,Interdiction à la location des passoires therm...,Des exceptions pour les logements pas isolable...,low,More than 5 years
3,https://www.novethic.fr/actualite/energie/tran...,Interdiction à la location des passoires therm...,Des rapports qui se suivent et se ressemblent....,low,More than 5 years
4,https://www.novethic.fr/actualite/energie/tran...,Interdiction à la location des passoires therm...,"""Aujourd’hui, nous devons bouger, l’échéancier...",low,More than 5 years
...,...,...,...,...,...
656,https://www.novethic.fr/actualite/energie/mobi...,Les Français ont acheté en 2021 plus de vélos ...,C’est un symbole de taille. Selon les derniers...,high,2 to 5 years
657,https://www.novethic.fr/actualite/energie/mobi...,Les Français ont acheté en 2021 plus de vélos ...,Avec la crise des Gilets jaunes et la multipli...,medium,2 to 5 years
658,https://www.novethic.fr/actualite/energie/mobi...,Les Français ont acheté en 2021 plus de vélos ...,Ces retards ont notamment permis de renforcer ...,medium,2 to 5 years
659,https://www.novethic.fr/actualite/energie/mobi...,Les Français ont acheté en 2021 plus de vélos ...,"Pas encore un pays du vélo\n""Il y a un phénomè...",medium,2 to 5 years
660,https://www.novethic.fr/actualite/energie/mobi...,"Laura Foglia, The Shift Project : ""Avec la vil...",Mais une politique de mobilité durable nécessi...,medium,More than 5 years

In [ ]:
train_fr['news_title'] = train_fr['news_title'].apply(data_enrichment.translate_french)
train_fr['news_content'] = train_fr['news_content'].apply(data_enrichment.translate_french)

In [16]:
train_fr

,URL,news_title,news_content,impact_level,impact_length
0,https://www.novethic.fr/actualite/energie/tran...,Prohibition on the rental of thermal colanders...,"Since January 1st, the most energy-efficient t...",low,More than 5 years
1,https://www.novethic.fr/actualite/energie/tran...,Prohibition on the rental of thermal colanders...,"Since 1 January 2023, the most energy-efficien...",low,More than 5 years
2,https://www.novethic.fr/actualite/energie/tran...,Prohibition on the rental of thermal colanders...,"Exceptions for non-insolable housing ""Everyone...",low,More than 5 years
3,https://www.novethic.fr/actualite/energie/tran...,Prohibition on the rental of thermal colanders...,Reports that follow and are similar. Court of ...,low,More than 5 years
4,https://www.novethic.fr/actualite/energie/tran...,Prohibition on the rental of thermal colanders...,"""Today we have to move, so the timetable set u...",low,More than 5 years
...,...,...,...,...,...
656,https://www.novethic.fr/actualite/energie/mobi...,The French bought in 2021 more bicycles than cars,According to the latest figures from the Union...,high,2 to 5 years
657,https://www.novethic.fr/actualite/energie/mobi...,The French bought in 2021 more bicycles than cars,With the crisis of the Yellow Gilets and the m...,medium,2 to 5 years
658,https://www.novethic.fr/actualite/energie/mobi...,The French bought in 2021 more bicycles than cars,"In 2021, 800,000 bicycles were produced in the...",medium,2 to 5 years
659,https://www.novethic.fr/actualite/energie/mobi...,The French bought in 2021 more bicycles than cars,"Not yet a country of cycling ""There is a pheno...",medium,2 to 5 years
660,https://www.novethic.fr/actualite/energie/mobi...,"Laura Foglia, The Shift Project: ""With the cit...",But a sustainable mobility policy needs to red...,medium,More than 5 years

In [ ]:
train_fr.to_csv("datasets/update_datasets/other_languages/train_fr_to_en.csv", index=False)
test_fr.to_csv("datasets/update_datasets/other_languages/test_fr_to_en.csv", index=False)

#### Translate Japanese texts to English

The Japanese-language dataset contains unique and valuable attributes. To make it more accessible for analysis in this thesis, we will translate the Japanese texts into English. The only attribute requiring translation is the ‘Text’ column, as all other attributes are either already in English or numerical. For this task, we will employ the Opus-MT model, the same model previously used for translating French to English.

In [6]:
train_jp = pd.read_json('datasets/competition/ML-ESG-3_Trainset_Japanese.json')
test_jp = pd.read_json('datasets/competition/ML-ESG3_Testset_Japanese.json')
test_jp

,ID,Text,Relevancy,ESG_type,Impact_type,Impact_duration
0,22348912,例えば、製品の「安全性」や「環境対応」を大幅に改善していることで、企業の成長と社会への貢献を...,Relevant,ESG_General,Opportunity,within_2_years
1,22348917,先進国および新興国の社会課題解決に資する事業を世界80カ国以上で展開し、確固たる市場シェアを...,Relevant,Social_Capital,Opportunity,within_2_years
2,2376729,凸版印刷は、「健康・ライフサイエンス」「教育・文化交流」「都市空間・モビリティ」「エネルギー...,Relevant,ESG_General,Opportunity,longer_than_5_years
3,23767210,凸版印刷はサステナビリティ活動を、「国連グローバル・コンパクト」を活動の原則に、また組織の社...,Relevant,ESG_General,Opportunity,longer_than_5_years
4,2739634,花王グループは2017年度より、「自ら変わり、そして変化を先導する企業へ」をスローガンに掲げ...,Irrelevant,,,
...,...,...,...,...,...,...
1495,3869382679,トヨタは15年10月末にカローラとレビンのデュアルエンジン車を発売し、このハイブリッド車は現...,Relevant,Environmental,Opportunity,within_2_years
1496,3869382680,カローラの販売量は16年1月5日現在で9268台、レビンは15年12月27日現在で8465台...,Irrelevan,,,
1497,3869382681,トヨタの計画では、両ハイブリッド車を合わせての月間販売目標は5千台だが、今の状況をみると、1...,Irrelevan,,,
1498,3869382682,だが15年の好調な業績とデュアルエンジンの新車2車種に後押しされながらも、トヨタは16年の目...,Irrelevan,,,
1499,389721618,PwCは「社会に信頼を構築し、重要な課題を解決する」を存在意義に掲げ、日々の業務を通じた社会...,Relevant,Social_Capital,Opportunity,between_2_and_5_years

In [7]:
train_jp['Text'] = train_jp['Text'].apply(data_enrichment.translate_japanese)
test_jp['Text'] = test_jp['Text'].apply(data_enrichment.translate_japanese)

In [8]:
test_jp

,ID,Text,Relevancy,ESG_type,Impact_type,Impact_duration
0,22348912,"For example, by greatly improving the product'...",Relevant,ESG_General,Opportunity,within_2_years
1,22348917,It expands its business to meet social challen...,Relevant,Social_Capital,Opportunity,within_2_years
2,2376729,The letterpress is working on solving the prob...,Relevant,ESG_General,Opportunity,longer_than_5_years
3,23767210,"The letter-pressing has adopted ""United Nation...",Relevant,ESG_General,Opportunity,longer_than_5_years
4,2739634,The Hana King Group has launched a 4-year midt...,Irrelevant,,,
...,...,...,...,...,...,...
1495,3869382679,"In the end of October 15th, 22th of 15th, a du...",Relevant,Environmental,Opportunity,within_2_years
1496,3869382680,"As of January 5, 16th, the sales of the canoe ...",Irrelevan,,,
1497,3869382681,"The yo-yo plan is to sell 5,000 hybrid cars a ...",Irrelevan,,,
1498,3869382682,But despite 15 years of fine performance and t...,Irrelevan,,,
1499,389721618,PwC is trying to solve social problems through...,Relevant,Social_Capital,Opportunity,between_2_and_5_years

In [ ]:
train_jp.to_csv("datasets/update_datasets/other_languages/train_jp_to_en.csv", index=False)
test_jp.to_csv("datasets/update_datasets/other_languages/test_jp_to_en.csv", index=False)

In [10]:
test_jp

,ID,Text,Relevancy,ESG_type,Impact_type,Impact_duration
0,22348912,"For example, by greatly improving the product'...",Relevant,ESG_General,Opportunity,within_2_years
1,22348917,It expands its business to meet social challen...,Relevant,Social_Capital,Opportunity,within_2_years
2,2376729,The letterpress is working on solving the prob...,Relevant,ESG_General,Opportunity,longer_than_5_years
3,23767210,"The letter-pressing has adopted ""United Nation...",Relevant,ESG_General,Opportunity,longer_than_5_years
4,2739634,The Hana King Group has launched a 4-year midt...,Irrelevant,,,
...,...,...,...,...,...,...
1495,3869382679,"In the end of October 15th, 22th of 15th, a du...",Relevant,Environmental,Opportunity,within_2_years
1496,3869382680,"As of January 5, 16th, the sales of the canoe ...",Irrelevan,,,
1497,3869382681,"The yo-yo plan is to sell 5,000 hybrid cars a ...",Irrelevan,,,
1498,3869382682,But despite 15 years of fine performance and t...,Irrelevan,,,
1499,389721618,PwC is trying to solve social problems through...,Relevant,Social_Capital,Opportunity,between_2_and_5_years

The dataset will be cleaned to retain only the information necessary for the analysis. Specifically:

- Only entries relevant to ESG issues will be considered. Therefore, rows where the column "Relevancy" has the value "Relevant" will be kept.
- ESG issues are categorized into three main factors: Environment, Social, and Governance. Accordingly, new columns corresponding to these factors will be created, and the respective percentage values will be derived from the ESG_type attribute.
- The impact_type attribute is also important, as it relates directly to sentiment analysis. In this context, opportunity indicates that the news has a positive impact, whereas risk signifies a negative impact.

##### Relevancy

In [13]:
train_jp_filtered = train_jp[train_jp['Relevancy'] == 'Relevant']
test_jp_filtered = test_jp[test_jp['Relevancy'] == 'Relevant']

##### ESG_type

In [17]:
train_jp_filtered['Environment'] = 0
train_jp_filtered['Social'] = 0
train_jp_filtered['Governance'] = 0
train_jp_filtered['None'] = 0

cols = ['Environment', 'Social', 'Governance', 'None']
train_jp_filtered[cols] = train_jp_filtered[cols].astype(float)

train_jp_filtered.loc[train_jp_filtered['ESG_type'] =='Environment', 'Environment'] = 1
train_jp_filtered.loc[train_jp_filtered['ESG_type'] =='Social_Capital','Social'] = 1
train_jp_filtered.loc[train_jp_filtered['ESG_type'] =='Governance','Governance'] = 1
train_jp_filtered.loc[train_jp_filtered['ESG_type'] =='', 'None'] = 1
train_jp_filtered.loc[train_jp_filtered['ESG_type'] =='ESG_general',['Environment', 'Social', 'Governance', 'None']] = [0.3333, 0.3333, 0.3333, 0]

train_jp_filtered = train_jp_filtered[train_jp_filtered['ESG_type'] != 'Human_Capital']

In [21]:
test_jp_filtered['Environment'] = 0.0
test_jp_filtered['Social'] = 0.0
test_jp_filtered['Governance'] = 0.0
test_jp_filtered['None'] = 0.0

cols = ['Environment', 'Social', 'Governance', 'None']
test_jp_filtered[cols] = test_jp_filtered[cols].astype(float)

test_jp_filtered.loc[test_jp_filtered['ESG_type'] =='Environment', 'Environment'] = 1
test_jp_filtered.loc[test_jp_filtered['ESG_type'] =='Social_Capital','Social'] = 1
test_jp_filtered.loc[test_jp_filtered['ESG_type'] =='Governance','Governance'] = 1
test_jp_filtered.loc[test_jp_filtered['ESG_type'] =='', 'None'] = 1
test_jp_filtered.loc[test_jp_filtered['ESG_type'] =='ESG_general',['Environment', 'Social', 'Governance', 'None']] = [0.3333, 0.3333, 0.3333, 0]

test_jp_filtered = test_jp_filtered[test_jp_filtered['ESG_type'] != 'Human_Capital']

##### Impact_type

In [22]:
train_jp_filtered['pos'] = 0.0
train_jp_filtered['neu'] = 0.0
train_jp_filtered['neg'] = 0.0

train_jp_filtered.loc[train_jp_filtered['Impact_type'] == 'Opportunity', 'pos'] = 1
train_jp_filtered.loc[train_jp_filtered['Impact_type'] == 'Risk', 'neg'] = 1
train_jp_filtered.loc[train_jp_filtered['Impact_type'] == '', 'neu'] = 1

In [24]:
test_jp_filtered['pos'] = 0.0
test_jp_filtered['neu'] = 0.0
test_jp_filtered['neg'] = 0.0

test_jp_filtered.loc[test_jp_filtered['Impact_type'] == 'Opportunity', 'pos'] = 1
test_jp_filtered.loc[test_jp_filtered['Impact_type'] == 'Risk', 'neg'] = 1
test_jp_filtered.loc[test_jp_filtered['Impact_type'] == '', 'neu'] = 1

Clean the unecessery attributes
- Relevancy
- ESG_type
- Impact_type

In [26]:
train_jp_filtered = train_jp_filtered.drop(columns=['Relevancy', 'ESG_type', 'Impact_type'])
test_jp_filtered = test_jp_filtered.drop(columns=['Relevancy', 'ESG_type', 'Impact_type'])

In [ ]:
train_jp_filtered.to_csv("datasets/update_datasets/other_languages/train_jp_to_en_filtered.csv", index=False)
test_jp_filtered.to_csv("datasets/update_datasets/other_languages/test_jp_to_en_fitered.csv", index=False)

### Mixing French dataset and English dataset 
An attempt will be made to merge the French and English datasets in order to construct a more balanced dataset. It is well established that machine learning models generally perform more effectively and achieve higher predictive accuracy when trained on balanced datasets.

In [14]:
train_df = pd.read_csv('datasets/update_datasets/train_df.csv')
train_fr = pd.read_csv("datasets/update_datasets/other_languages/train_fr_to_en.csv")
train_df = train_df.drop(columns = ['combination'])
train_fr["impact_level"] = train_fr["impact_level"].replace(["low","medium","high"],[0,1,2])
train_fr["impact_length"] = train_fr["impact_length"].replace(["Less than 2 years","2 to 5 years","More than 5 years"],[0,1,2])
train_fr_en = pd.concat([train_df, train_fr], ignore_index=True)

In [15]:
train_df

,URL,news_title,news_content,impact_level,impact_length
0,https://www.esgtoday.com/arabesque-ai-appoints...,Arabesque AI Appoints Carolina Minio Paluello ...,ESG-focused financial technology company Arabe...,0,1
1,https://www.esgtoday.com/arabesque-ai-appoints...,Arabesque AI Appoints Carolina Minio Paluello ...,The company also announced the appointment of ...,0,1
2,https://www.esgtoday.com/arabesque-ai-appoints...,Arabesque AI Appoints Carolina Minio Paluello ...,Wong said: \n“Personalised portfolios demand ...,1,1
3,https://www.esgtoday.com/ukraine-war-inflation...,"Ukraine War, Inflation Reduction Act Driving F...",One of the key themes of the report is the imp...,2,2
4,https://www.esgtoday.com/eu-regulators-welcome...,"EU Regulators Welcome, Critique New European S...",Europe’s three primary financial regulatory ag...,1,0
...,...,...,...,...,...
540,https://www.esgtoday.com/methane-emissions-det...,Methane Emissions Detection Platform Kuva Rais...,"Stefan Bokaemper, CEO of Kuva Systems, said: “...",0,1
541,https://www.esgtoday.com/eaton-appoints-harold...,Eaton Appoints Harold Jones as Chief Sustainab...,Eaton Appoints Harold Jones as Chief Sustainab...,0,1
542,https://www.esgtoday.com/ssga-outlines-2021-st...,"SSGA Outlines 2021 Stewardship Priorities, Wil...","In his letter, Taraporevala wrote: “As a signa...",1,0
543,https://www.esgtoday.com/survey-investors-shif...,Survey: Investors Shifting to Offense on Clima...,O’Brien said: “Investors globally are increasi...,0,0
544,https://www.esgtoday.com/chicago-to-transition...,"Chicago to Transition Buildings, Airports & Op...","Jim McHugh, Chief Commercial Officer, Constell...",1,1

In [16]:
train_fr_en

,URL,news_title,news_content,impact_level,impact_length
0,https://www.esgtoday.com/arabesque-ai-appoints...,Arabesque AI Appoints Carolina Minio Paluello ...,ESG-focused financial technology company Arabe...,0,1
1,https://www.esgtoday.com/arabesque-ai-appoints...,Arabesque AI Appoints Carolina Minio Paluello ...,The company also announced the appointment of ...,0,1
2,https://www.esgtoday.com/arabesque-ai-appoints...,Arabesque AI Appoints Carolina Minio Paluello ...,Wong said: \n“Personalised portfolios demand ...,1,1
3,https://www.esgtoday.com/ukraine-war-inflation...,"Ukraine War, Inflation Reduction Act Driving F...",One of the key themes of the report is the imp...,2,2
4,https://www.esgtoday.com/eu-regulators-welcome...,"EU Regulators Welcome, Critique New European S...",Europe’s three primary financial regulatory ag...,1,0
...,...,...,...,...,...
1201,https://www.novethic.fr/actualite/energie/mobi...,The French bought in 2021 more bicycles than cars,According to the latest figures from the Union...,2,1
1202,https://www.novethic.fr/actualite/energie/mobi...,The French bought in 2021 more bicycles than cars,With the crisis of the Yellow Gilets and the m...,1,1
1203,https://www.novethic.fr/actualite/energie/mobi...,The French bought in 2021 more bicycles than cars,"In 2021, 800,000 bicycles were produced in the...",1,1
1204,https://www.novethic.fr/actualite/energie/mobi...,The French bought in 2021 more bicycles than cars,"Not yet a country of cycling ""There is a pheno...",1,1
1205,https://www.novethic.fr/actualite/energie/mobi...,"Laura Foglia, The Shift Project: ""With the cit...",But a sustainable mobility policy needs to red...,1,2

In [ ]:
balanced_df = data_enrichment.balance_two_columns_by_undersample(
    df=train_fr_en,
    col_a='impact_level',
    col_b='impact_length',
    strategy='median',   
    random_state=123,
    verbose=True
)

Balancing joint groups (impact_level, impact_length) with cap = 88 (strategy=median)
Group counts before (sample):
 impact_level  impact_length  count
            2              2    308
            1              1    284
            1              2    181
            1              0    106
            0              1     88
            0              2     75
            0              0     74
            2              1     57
            2              0     33

Counts after balancing (joint groups):
 impact_level  impact_length  count
            0              1     88
            1              0     88
            1              1     88
            1              2     88
            2              2     88
            0              2     75
            0              0     74
            2              1     57
            2              0     33

Marginal counts after balancing:
impact_level
1    264
0    237
2    178
impact_length
2    251
1    233
0    195

In [18]:
balanced_df.to_csv("datasets/update_datasets/other_languages/train_balanced.csv", index=False)