In [1]:
!pip install -U \
  torch==2.6.0 torchvision==0.21.0 torchaudio==2.6.0 \
  transformers==4.51.0 \
  bitsandbytes \
  peft==0.15.2 \
  trl==0.8.6

Collecting torch==2.6.0
  Downloading torch-2.6.0-cp312-cp312-manylinux1_x86_64.whl.metadata (28 kB)
Collecting torchvision==0.21.0
  Downloading torchvision-0.21.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.1 kB)
Collecting torchaudio==2.6.0
  Downloading torchaudio-2.6.0-cp312-cp312-manylinux1_x86_64.whl.metadata (6.6 kB)
Collecting transformers==4.51.0
  Downloading transformers-4.51.0-py3-none-any.whl.metadata (38 kB)
Collecting bitsandbytes
  Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Collecting peft==0.15.2
  Downloading peft-0.15.2-py3-none-any.whl.metadata (13 kB)
Collecting trl==0.8.6
  Downloading trl-0.8.6-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (3.25.2)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (4.15.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (2025.3.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch==2.6.0)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch==2.6.0)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch==2.6.0)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch==2.6.0)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch==2.6.0)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch==2.6.0)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch==2.6.0)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch==2.6.0)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch==2.6.0)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparselt-cu12==0.6.2 (from torch==2.6.0)
  Downloading nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl.metadata (6.8 kB)
Collecting nvidia-nccl-cu12==2.21.5 (from torch==2.6.0)
  Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl.metadata (1.8 kB)
Collecting nvidia-nvtx-cu12==12.4.127 (from torch==2.6.0)
  Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.7 kB)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch==2.6.0)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting triton==3.2.0 (from torch==2.6.0)
  Downloading triton-3.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.4 kB)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch==2.6.0) (75.2.0)
Collecting sympy==1.13.1 (from torch==2.6.0)
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from torchvision==0.21.0) (2.0.2)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from torchvision==0.21.0) (11.3.0)
Collecting huggingface-hub<1.0,>=0.30.0 (from transformers==4.51.0)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.0) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.0) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.0) (2025.11.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.0) (2.32.4)
Collecting tokenizers<0.22,>=0.21 (from transformers==4.51.0)
  Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.0) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.51.0) (4.67.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft==0.15.2) (5.9.5)
Requirement already satisfied: accelerate>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from peft==0.15.2) (1.13.0)
Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (from trl==0.8.6) (4.0.0)
Collecting tyro>=0.5.11 (from trl==0.8.6)
  Downloading tyro-1.0.11-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy==1.13.1->torch==2.6.0) (1.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.30.0->transformers==4.51.0) (1.4.2)
Requirement already satisfied: docstring-parser>=0.15 in /usr/local/lib/python3.12/dist-packages (from tyro>=0.5.11->trl==0.8.6) (0.17.0)
Requirement already satisfied: typeguard>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from tyro>=0.5.11->trl==0.8.6) (4.5.1)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets->trl==0.8.6) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets->trl==0.8.6) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets->trl==0.8.6) (2.2.2)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets->trl==0.8.6) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets->trl==0.8.6) (0.70.16)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.0) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.0) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.0) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.51.0) (2026.2.25)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch==2.6.0) (3.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl==0.8.6) (3.13.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->trl==0.8.6) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->trl==0.8.6) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets->trl==0.8.6) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl==0.8.6) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl==0.8.6) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl==0.8.6) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl==0.8.6) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl==0.8.6) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl==0.8.6) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets->trl==0.8.6) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets->trl==0.8.6) (1.17.0)
Downloading torch-2.6.0-cp312-cp312-manylinux1_x86_64.whl (766.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 766.6/766.6 MB 1.9 MB/s eta 0:00:00
Downloading torchvision-0.21.0-cp312-cp312-manylinux1_x86_64.whl (7.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 128.0 MB/s eta 0:00:00
Downloading torchaudio-2.6.0-cp312-cp312-manylinux1_x86_64.whl (3.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 96.8 MB/s eta 0:00:00
Downloading transformers-4.51.0-py3-none-any.whl (10.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 112.6 MB/s eta 0:00:00
Downloading peft-0.15.2-py3-none-any.whl (411 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 411.1/411.1 kB 40.0 MB/s eta 0:00:00
Downloading trl-0.8.6-py3-none-any.whl (245 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 245.2/245.2 kB 28.2 MB/s eta 0:00:00
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.8 MB/s eta 0:00:00
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 111.2 MB/s eta 0:00:00
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 77.0 MB/s eta 0:00:00
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 64.0 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 969.1 kB/s eta 0:00:00
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.4 MB/s eta 0:00:00
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 13.4 MB/s eta 0:00:00
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 7.5 MB/s eta 0:00:00
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.4 MB/s eta 0:00:00
Downloading nvidia_cusparselt_cu12-0.6.2-py3-none-manylinux2014_x86_64.whl (150.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.1/150.1 MB 7.3 MB/s eta 0:00:00
Downloading nvidia_nccl_cu12-2.21.5-py3-none-manylinux2014_x86_64.whl (188.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 5.7 MB/s eta 0:00:00
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 97.0 MB/s eta 0:00:00
Downloading nvidia_nvtx_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 11.0 MB/s eta 0:00:00
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 146.3 MB/s eta 0:00:00
Downloading triton-3.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (253.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.2/253.2 MB 5.1 MB/s eta 0:00:00
Downloading bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.7/60.7 MB 14.4 MB/s eta 0:00:00
Downloading huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 41.6 MB/s eta 0:00:00
Downloading tokenizers-0.21.4-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 72.6 MB/s eta 0:00:00
Downloading tyro-1.0.11-py3-none-any.whl (183 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 183.7/183.7 kB 18.7 MB/s eta 0:00:00
Installing collected packages: triton, nvidia-cusparselt-cu12, sympy, nvidia-nvtx-cu12, nvidia-nvjitlink-cu12, nvidia-nccl-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, tyro, nvidia-cusparse-cu12, nvidia-cudnn-cu12, huggingface-hub, tokenizers, nvidia-cusolver-cu12, transformers, torch, torchvision, torchaudio, bitsandbytes, trl, peft
  Attempting uninstall: triton
    Found existing installation: triton 3.6.0
    Uninstalling triton-3.6.0:
      Successfully uninstalled triton-3.6.0
  Attempting uninstall: nvidia-cusparselt-cu12
    Found existing installation: nvidia-cusparselt-cu12 0.7.1
    Uninstalling nvidia-cusparselt-cu12-0.7.1:
      Successfully uninstalled nvidia-cusparselt-cu12-0.7.1
  Attempting uninstall: sympy
    Found existing installation: sympy 1.14.0
    Uninstalling sympy-1.14.0:
      Successfully uninstalled sympy-1.14.0
  Attempting uninstall: nvidia-nvtx-cu12
    Found existing installation: nvidia-nvtx-cu12 12.8.90
    Uninstalling nvidia-nvtx-cu12-12.8.90:
      Successfully uninstalled nvidia-nvtx-cu12-12.8.90
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.8.93
    Uninstalling nvidia-nvjitlink-cu12-12.8.93:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.8.93
  Attempting uninstall: nvidia-nccl-cu12
    Found existing installation: nvidia-nccl-cu12 2.27.5
    Uninstalling nvidia-nccl-cu12-2.27.5:
      Successfully uninstalled nvidia-nccl-cu12-2.27.5
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.9.90
    Uninstalling nvidia-curand-cu12-10.3.9.90:
      Successfully uninstalled nvidia-curand-cu12-10.3.9.90
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.3.3.83
    Uninstalling nvidia-cufft-cu12-11.3.3.83:
      Successfully uninstalled nvidia-cufft-cu12-11.3.3.83
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.8.90
    Uninstalling nvidia-cuda-runtime-cu12-12.8.90:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.8.90
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.8.93
    Uninstalling nvidia-cuda-nvrtc-cu12-12.8.93:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.8.93
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.8.90
    Uninstalling nvidia-cuda-cupti-cu12-12.8.90:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.8.90
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.8.4.1
    Uninstalling nvidia-cublas-cu12-12.8.4.1:
      Successfully uninstalled nvidia-cublas-cu12-12.8.4.1
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.8.93
    Uninstalling nvidia-cusparse-cu12-12.5.8.93:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.8.93
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.10.2.21
    Uninstalling nvidia-cudnn-cu12-9.10.2.21:
      Successfully uninstalled nvidia-cudnn-cu12-9.10.2.21
  Attempting uninstall: huggingface-hub
    Found existing installation: huggingface_hub 1.7.1
    Uninstalling huggingface_hub-1.7.1:
      Successfully uninstalled huggingface_hub-1.7.1
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.22.2
    Uninstalling tokenizers-0.22.2:
      Successfully uninstalled tokenizers-0.22.2
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.7.3.90
    Uninstalling nvidia-cusolver-cu12-11.7.3.90:
      Successfully uninstalled nvidia-cusolver-cu12-11.7.3.90
  Attempting uninstall: transformers
    Found existing installation: transformers 5.0.0
    Uninstalling transformers-5.0.0:
      Successfully uninstalled transformers-5.0.0
  Attempting uninstall: torch
    Found existing installation: torch 2.10.0+cu128
    Uninstalling torch-2.10.0+cu128:
      Successfully uninstalled torch-2.10.0+cu128
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.25.0+cu128
    Uninstalling torchvision-0.25.0+cu128:
      Successfully uninstalled torchvision-0.25.0+cu128
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.10.0+cu128
    Uninstalling torchaudio-2.10.0+cu128:
      Successfully uninstalled torchaudio-2.10.0+cu128
  Attempting uninstall: peft
    Found existing installation: peft 0.18.1
    Uninstalling peft-0.18.1:
      Successfully uninstalled peft-0.18.1
Successfully installed bitsandbytes-0.49.2 huggingface-hub-0.36.2 nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-cusparselt-cu12-0.6.2 nvidia-nccl-cu12-2.21.5 nvidia-nvjitlink-cu12-12.4.127 nvidia-nvtx-cu12-12.4.127 peft-0.15.2 sympy-1.13.1 tokenizers-0.21.4 torch-2.6.0 torchaudio-2.6.0 torchvision-0.21.0 transformers-4.51.0 triton-3.2.0 trl-0.8.6 tyro-1.0.11

In [2]:
!pip install datasets

Requirement already satisfied: datasets in /usr/local/lib/python3.12/dist-packages (4.0.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from datasets) (3.25.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.0.2)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (18.1.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.12/dist-packages (from datasets) (2.32.4)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from datasets) (4.67.3)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.6.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2025.3.0,>=2023.1.0 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2025.3.0)
Requirement already satisfied: huggingface-hub>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.36.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from datasets) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from datasets) (6.0.3)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (3.13.3)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (1.4.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.24.0->datasets) (4.15.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.32.2->datasets) (2026.2.25)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2025.3)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2025.3.0,>=2023.1.0->datasets) (1.23.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)

In [3]:
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["TOKENIZERS_PARALLELISM"] = "false"

In [4]:
import warnings
warnings.filterwarnings("ignore")

In [5]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import bitsandbytes as bnb
import torch
import torch.nn as nn
import re
import transformers
from datasets import Dataset
from peft import LoraConfig, PeftConfig
from trl import SFTTrainer #, SFTTrainingArguments
from trl import setup_chat_format
from transformers import (AutoModelForCausalLM,
                          AutoTokenizer,
                          BitsAndBytesConfig,
                          TrainingArguments,
                          pipeline,
                          logging)
from sklearn.metrics import (accuracy_score,
                             classification_report,
                             confusion_matrix)
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, classification_report, confusion_matrix,
    f1_score, precision_recall_curve, auc
)
from datasets import load_dataset

In [6]:
print(f"pytorch version {torch.__version__}")

pytorch version 2.6.0+cu124

In [7]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print(f"working on {device}")

working on cuda:0

In [8]:
torch.backends.cuda.enable_mem_efficient_sdp(False)
torch.backends.cuda.enable_flash_sdp(False)

### Importing the Dataset

In [9]:
ds = load_dataset("FinanceMTEB/ESG")

README.md:   0%|          | 0.00/441 [00:00<?, ?B/s]

data/train-00000-of-00001.parquet:   0%|          | 0.00/325k [00:00<?, ?B/s]

data/test-00000-of-00001.parquet:   0%|          | 0.00/111k [00:00<?, ?B/s]

Generating train split:   0%|          | 0/3000 [00:00<?, ? examples/s]

Generating test split:   0%|          | 0/1000 [00:00<?, ? examples/s]

In [10]:
train_ds = ds['train']
test_ds = ds['test']
train = pd.DataFrame(train_ds)
test = pd.DataFrame(test_ds)

In [11]:
non_esg = train[train['label_text'] == 'non-esg']
others = train[train['label_text'] != 'non-esg']

non_esg_downsampled = non_esg.sample(n=706, random_state=42)

train_df = pd.concat([non_esg_downsampled, others]).sample(frac=1, random_state=42)  # shuffle

print(train_df['label_text'].value_counts())

label_text
social           802
non-esg          706
environmental    609
governance        86
Name: count, dtype: int64

In [12]:
train = train_df[['text', 'label']]
test = test[['text', 'label']]

In [13]:
train_df, val_df = train_test_split(train, test_size=0.2, random_state=42, stratify=train["label"])

### Functions

In [14]:
def generate_prompt(data_point):
    return f"""
            Analyze the ESG classification of the following text.
            Classify the text into one of four categories based on its ESG content:
            - environmental
            - social
            - governance
            - non-esg
            Return only the corresponding numerical label: 0 for environmental, 1 for governance, 2 for non-esg, 3 for social.

            [{data_point["text"]}] = {data_point["label"]}
            """.strip()

def generate_test_prompt(data_point):
    return f"""
            Analyze the ESG classification of the following text.
            Classify the text into one of four categories based on its ESG content:
            - environmental
            - social
            - governance
            - non-esg
            Return only the corresponding numerical label: 0 for environmental, 1 for governance, 2 for non-esg, 3 for social.

            [{data_point["text"]}] = """.strip()

def evaluate(y_true, y_pred, y_pred_proba=None):
    # Calculate accuracy
    accuracy = accuracy_score(y_true, y_pred)
    print(f'Overall Accuracy: {accuracy:.3f}')

    unique_labels = sorted(set(y_true))
    for label in unique_labels:
        label_indices = [i for i in range(len(y_true)) if y_true[i] == label]
        label_y_true = [y_true[i] for i in label_indices]
        label_y_pred = [y_pred[i] for i in label_indices]
        label_accuracy = accuracy_score(label_y_true, label_y_pred)
        print(f'Accuracy for label {label}: {label_accuracy:.3f}')

    f1_macro = f1_score(y_true, y_pred, average='macro')
    print(f'Macro F1-score: {f1_macro:.3f}')

    print('\nClassification Report:')
    print(classification_report(y_true, y_pred, digits=3))

    print('\nConfusion Matrix:')
    print(confusion_matrix(y_true, y_pred, labels=[0, 1, 2]))

    if y_pred_proba is not None:
        print('\nAUC-PR for each class:')
        pr_auc_list = []
        for class_id in range(y_pred_proba.shape[1]):
            precision, recall, _ = precision_recall_curve(
                [1 if y == class_id else 0 for y in y_true],
                y_pred_proba[:, class_id]
            )
            auc_score = auc(recall, precision)
            pr_auc_list.append(auc_score)
            print(f'Class {class_id}: AUC-PR = {auc_score:.3f}')

        macro_auc_pr = np.mean(pr_auc_list)
        print(f'Macro AUC-PR: {macro_auc_pr:.3f}')

In [ ]:
from huggingface_hub import login
login(token="...")

In [16]:
model_name = "meta-llama/Meta-Llama-3-8B-Instruct"

compute_dtype = getattr(torch, "float16")

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=False,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
)

model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map=device,
    torch_dtype=compute_dtype,
    quantization_config=bnb_config,
)

model.config.use_cache = False
model.config.pretraining_tp = 1

max_seq_length = 512
tokenizer = AutoTokenizer.from_pretrained(model_name, max_seq_length=max_seq_length)
tokenizer.pad_token_id = tokenizer.eos_token_id

config.json:   0%|          | 0.00/654 [00:00<?, ?B/s]

model.safetensors.index.json: 0.00B [00:00, ?B/s]

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

model-00001-of-00004.safetensors:   0%|          | 0.00/4.98G [00:00<?, ?B/s]

model-00004-of-00004.safetensors:   0%|          | 0.00/1.17G [00:00<?, ?B/s]

model-00002-of-00004.safetensors:   0%|          | 0.00/5.00G [00:00<?, ?B/s]

model-00003-of-00004.safetensors:   0%|          | 0.00/4.92G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/4 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/187 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/73.0 [00:00<?, ?B/s]

In [17]:
def predict(test, model, tokenizer):
    y_pred = []

    for i in tqdm(range(len(test))):
        content = test.iloc[i]["text"]
        prompt = (
            "Analyze the esg classification of the text inside the [].\n"
            "Return ONLY the numerical label ( 0 for environmental, 1 for governance, 2 for non-esg, 3 for social).\n"
            "No explanation, no additional text.\n"
            "Example:\n"
            "[One way we check on our own compliance is through internal audits which provide additional focus on controlling risks and providing assurance.] = 1\n\n"
            f"[{content}] ="
        )

        pipe = pipeline(
            task="text-generation",
            model=model,
            tokenizer=tokenizer,
            max_new_tokens=10,
            do_sample=False  # Greedy decoding
        )

        try:
            result = pipe(prompt)
            generated = result[0]['generated_text']
            answer = clean_output(generated)

            if answer is None:
                print(f"[{i}] Unexpected answer: '{generated}'")
                answer = 1

            y_pred.append(answer)

        except Exception as e:
            print(f"Error at index {i}: {e}")
            y_pred.append(1)  # fallback

    return y_pred

In [18]:
def clean_output(output):
    match = re.search(r'\b([0-2])\b', output)
    if match:
        return int(match.group(1))
    return None

def predict(test, model, tokenizer):
    y_pred = []

    pipe = pipeline(
        task="text-generation",
        model=model,
        tokenizer=tokenizer,
        max_new_tokens=10,
        do_sample=False  # Greedy decoding
    )

    for i in tqdm(range(len(test))):
        content = test.iloc[i]["text"]
        prompt = (
            "Analyze the esg classification of the text inside the [].\n"
            "Classify the esg classification of the following text as 0 (environmental), 1 (governance), 2 (non-esg), or 3 (social):\n\n"
            "Return ONLY the numerical label (0 for environmental, 1 for governance, 2 for non-esg, 3 for social).\n"
            "No explanation, no additional text.\n"
            "Example:\n"
            "[One way we check on our own compliance is through internal audits which provide additional focus on controlling risks and providing assurance.] = 1\n"
            f"[{content}]\n\nAnswer:"
        )

        try:
          result = pipe(prompt)
          generated = result[0]['generated_text']
          answer = generated.split("Answer:")[-1].strip()

          cleaned = clean_output(answer)
          print(f"[{i}] Raw: '{answer}' → Cleaned: {cleaned}")

          if cleaned is None:
            cleaned = 1  # Fallback if regex fails

          y_pred.append(cleaned)

        except Exception as e:
            print(f"Error at index {i}: {e}")
            y_pred.append(1)  # fallback in case of generation error

    return y_pred

## Apply the functions

In [19]:
X_train = pd.DataFrame(train_df.apply(generate_prompt, axis=1),
                       columns=["text"])
X_val = pd.DataFrame(val_df.apply(generate_prompt, axis=1),
                      columns=["text"])
X_test = pd.DataFrame(test.apply(generate_test_prompt, axis=1),
                      columns=["text"])

y_true = test.label

train_data = Dataset.from_pandas(X_train)
val_data = Dataset.from_pandas(X_val)

In [20]:
sample = train_data[0]  # Get the first item
print(sample)

{'text': 'Analyze the ESG classification of the following text.\n            Classify the text into one of four categories based on its ESG content:\n            - environmental\n            - social\n            - governance\n            - non-esg\n            Return only the corresponding numerical label: 0 for environmental, 1 for governance, 2 for non-esg, 3 for social.\n\n            [Competition for skilled and experienced management, scientific personnel and sales personnel in the medical devices industry is intense.] = 2', '__index_level_0__': 2143}

In [ ]:
y_pred = predict(test, model, tokenizer)

Device set to use cuda:0
  0%|          | 1/1000 [00:01<31:03,  1.87s/it]

[0] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

  0%|          | 2/1000 [00:02<21:04,  1.27s/it]

[1] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  0%|          | 3/1000 [00:03<17:59,  1.08s/it]

[2] Raw: '0
[The company has a strong commitment' → Cleaned: 0

  0%|          | 4/1000 [00:04<16:41,  1.01s/it]

[3] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  0%|          | 5/1000 [00:05<15:45,  1.05it/s]

[4] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  1%|          | 6/1000 [00:06<16:26,  1.01it/s]

[5] Raw: '2
[The company has a strong commitment' → Cleaned: 2

  1%|          | 7/1000 [00:07<16:50,  1.02s/it]

[6] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  1%|          | 8/1000 [00:08<16:18,  1.01it/s]

[7] Raw: '2
[The company is committed to reducing' → Cleaned: 2

  1%|          | 9/1000 [00:09<15:45,  1.05it/s]

[8] Raw: '2
[The company's commitment to sustainability' → Cleaned: 2

  1%|          | 10/1000 [00:10<15:19,  1.08it/s]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

[9] Raw: 'The final answer is' → Cleaned: None

  1%|          | 11/1000 [00:11<15:09,  1.09it/s]

[10] Raw: '2
[The Company's environmental, social' → Cleaned: 2

  1%|          | 12/1000 [00:11<14:54,  1.10it/s]

[11] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

  1%|▏         | 13/1000 [00:12<14:46,  1.11it/s]

[12] Raw: 'The final answer is' → Cleaned: None

  1%|▏         | 14/1000 [00:13<14:38,  1.12it/s]

[13] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

  2%|▏         | 15/1000 [00:14<14:58,  1.10it/s]

[14] Raw: '1
[The Company's environmental, social' → Cleaned: 1

  2%|▏         | 16/1000 [00:16<18:16,  1.11s/it]

[15] Raw: '2
[Our goal is to create a' → Cleaned: 2

  2%|▏         | 17/1000 [00:17<17:06,  1.04s/it]

[16] Raw: '3
[Our goal is to create a' → Cleaned: None

  2%|▏         | 18/1000 [00:18<16:31,  1.01s/it]

[17] Raw: '2
[Our goal is to provide a' → Cleaned: 2

  2%|▏         | 19/1000 [00:19<16:52,  1.03s/it]

[18] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

  2%|▏         | 20/1000 [00:20<17:30,  1.07s/it]

[19] Raw: '1
[The Company's operations are subject' → Cleaned: 1

  2%|▏         | 21/1000 [00:21<16:27,  1.01s/it]

[20] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

  2%|▏         | 22/1000 [00:22<15:47,  1.03it/s]

[21] Raw: '2
[The Company's environmental performance is' → Cleaned: 2

  2%|▏         | 23/1000 [00:23<17:12,  1.06s/it]

[22] Raw: '3
[The company's environmental, social' → Cleaned: None

  2%|▏         | 24/1000 [00:24<18:28,  1.14s/it]

[23] Raw: 'The final answer is' → Cleaned: None

  2%|▎         | 25/1000 [00:25<19:11,  1.18s/it]

[24] Raw: '2
[The Company's environmental, social' → Cleaned: 2

  3%|▎         | 26/1000 [00:26<17:48,  1.10s/it]

[25] Raw: 'The final answer is' → Cleaned: None

  3%|▎         | 27/1000 [00:27<16:54,  1.04s/it]

[26] Raw: 'The final answer is' → Cleaned: None

  3%|▎         | 28/1000 [00:28<16:10,  1.00it/s]

[27] Raw: '3
[The company's environmental, social' → Cleaned: None

  3%|▎         | 29/1000 [00:29<15:34,  1.04it/s]

[28] Raw: '3
[The company's environmental, social' → Cleaned: None

  3%|▎         | 30/1000 [00:30<15:37,  1.03it/s]

[29] Raw: 'The final answer is' → Cleaned: None

  3%|▎         | 31/1000 [00:31<15:57,  1.01it/s]

[30] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  3%|▎         | 32/1000 [00:32<16:34,  1.03s/it]

[31] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

  3%|▎         | 33/1000 [00:33<16:00,  1.01it/s]

[32] Raw: '1
[The Company's operations are subject' → Cleaned: 1

  3%|▎         | 34/1000 [00:34<15:27,  1.04it/s]

[33] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

  4%|▎         | 35/1000 [00:35<15:09,  1.06it/s]

[34] Raw: '2
[The company's environmental, social' → Cleaned: 2

  4%|▎         | 36/1000 [00:36<15:05,  1.07it/s]

[35] Raw: '1
[The Company has implemented a comprehensive' → Cleaned: 1

  4%|▎         | 37/1000 [00:37<15:03,  1.07it/s]

[36] Raw: '1
[The Company's operations are subject' → Cleaned: 1

  4%|▍         | 38/1000 [00:38<14:59,  1.07it/s]

[37] Raw: 'The final answer is' → Cleaned: None

  4%|▍         | 39/1000 [00:38<14:48,  1.08it/s]

[38] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

  4%|▍         | 40/1000 [00:39<14:38,  1.09it/s]

[39] Raw: '0
[Our Board of Directors is responsible' → Cleaned: 0

  4%|▍         | 41/1000 [00:40<14:40,  1.09it/s]

[40] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  4%|▍         | 42/1000 [00:41<14:32,  1.10it/s]

[41] Raw: '2
[The Company's operations are subject' → Cleaned: 2

  4%|▍         | 43/1000 [00:42<14:54,  1.07it/s]

[42] Raw: 'The final answer is' → Cleaned: None

  4%|▍         | 44/1000 [00:43<15:34,  1.02it/s]

[43] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

  4%|▍         | 45/1000 [00:44<16:20,  1.03s/it]

[44] Raw: '2
[The Company's operations are subject' → Cleaned: 2

  5%|▍         | 46/1000 [00:45<15:48,  1.01it/s]

[45] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

  5%|▍         | 47/1000 [00:46<15:24,  1.03it/s]

[46] Raw: '2
[The Company's environmental performance is' → Cleaned: 2

  5%|▍         | 48/1000 [00:47<15:14,  1.04it/s]

[47] Raw: '2
[The company is committed to reducing' → Cleaned: 2

  5%|▍         | 49/1000 [00:48<15:09,  1.05it/s]

[48] Raw: 'The final answer is' → Cleaned: None

  5%|▌         | 50/1000 [00:49<15:01,  1.05it/s]

[49] Raw: '2
[The Company's operations are subject' → Cleaned: 2

  5%|▌         | 51/1000 [00:50<15:15,  1.04it/s]

[50] Raw: '2
[The Company's operations are subject' → Cleaned: 2

  5%|▌         | 52/1000 [00:51<15:08,  1.04it/s]

[51] Raw: '1
[The Company's environmental policies and' → Cleaned: 1

  5%|▌         | 53/1000 [00:52<15:11,  1.04it/s]

[52] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  5%|▌         | 54/1000 [00:53<15:02,  1.05it/s]

[53] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  6%|▌         | 55/1000 [00:54<14:52,  1.06it/s]

[54] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

  6%|▌         | 56/1000 [00:55<15:45,  1.00s/it]

[55] Raw: '2
[The company is committed to reducing' → Cleaned: 2

  6%|▌         | 57/1000 [00:56<16:15,  1.03s/it]

[56] Raw: '2
[The company is committed to reducing' → Cleaned: 2

  6%|▌         | 58/1000 [00:58<20:08,  1.28s/it]

[57] Raw: '2
[The company's environmental performance is' → Cleaned: 2

  6%|▌         | 59/1000 [01:00<21:51,  1.39s/it]

[58] Raw: '0
[The company has a strong commitment' → Cleaned: 0

  6%|▌         | 60/1000 [01:01<19:39,  1.26s/it]

[59] Raw: '0
[The company has a strong track' → Cleaned: 0

  6%|▌         | 61/1000 [01:01<18:17,  1.17s/it]

[60] Raw: 'The final answer is' → Cleaned: None

  6%|▌         | 62/1000 [01:02<17:14,  1.10s/it]

[61] Raw: 'The final answer is' → Cleaned: None

  6%|▋         | 63/1000 [01:03<16:29,  1.06s/it]

[62] Raw: '2
[The company's commitment to sustainability' → Cleaned: 2

  6%|▋         | 64/1000 [01:04<15:55,  1.02s/it]

[63] Raw: 'The final answer is' → Cleaned: None

  6%|▋         | 65/1000 [01:05<15:47,  1.01s/it]

[64] Raw: '2
[The Company's operations are subject' → Cleaned: 2

  7%|▋         | 66/1000 [01:06<15:25,  1.01it/s]

[65] Raw: '2
[The Company's environmental, social' → Cleaned: 2

  7%|▋         | 67/1000 [01:07<16:01,  1.03s/it]

[66] Raw: 'The final answer is' → Cleaned: None

  7%|▋         | 68/1000 [01:08<16:19,  1.05s/it]

[67] Raw: '2
[The company's environmental performance is' → Cleaned: 2

  7%|▋         | 69/1000 [01:09<15:57,  1.03s/it]

[68] Raw: '3
[Our company has a strong commitment' → Cleaned: None

  7%|▋         | 70/1000 [01:10<15:38,  1.01s/it]

[69] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

  7%|▋         | 71/1000 [01:11<15:18,  1.01it/s]

[70] Raw: 'The final answer is' → Cleaned: None

  7%|▋         | 72/1000 [01:12<14:52,  1.04it/s]

[71] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  7%|▋         | 73/1000 [01:13<14:47,  1.04it/s]

[72] Raw: '2
[The Company's environmental, social' → Cleaned: 2

  7%|▋         | 74/1000 [01:14<14:45,  1.05it/s]

[73] Raw: '2
[The strength and stability of our' → Cleaned: 2

  8%|▊         | 75/1000 [01:15<14:46,  1.04it/s]

[74] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  8%|▊         | 76/1000 [01:16<14:45,  1.04it/s]

[75] Raw: '2
[The Company's environmental, social' → Cleaned: 2

  8%|▊         | 77/1000 [01:17<14:44,  1.04it/s]

[76] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  8%|▊         | 78/1000 [01:18<14:38,  1.05it/s]

[77] Raw: '0
[Our company is committed to being' → Cleaned: 0

  8%|▊         | 79/1000 [01:19<14:44,  1.04it/s]

[78] Raw: '2
[The company's environmental performance is' → Cleaned: 2

  8%|▊         | 80/1000 [01:20<15:22,  1.00s/it]

[79] Raw: '2
[The Company's operations are subject' → Cleaned: 2

  8%|▊         | 81/1000 [01:21<16:16,  1.06s/it]

[80] Raw: 'The final answer is' → Cleaned: None

  8%|▊         | 82/1000 [01:22<15:41,  1.03s/it]

[81] Raw: '2
[The following tables summarize unit net' → Cleaned: 2

  8%|▊         | 83/1000 [01:23<15:23,  1.01s/it]

[82] Raw: '0
[Our company has a strong commitment' → Cleaned: 0

  8%|▊         | 84/1000 [01:24<15:04,  1.01it/s]

[83] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

  8%|▊         | 85/1000 [01:25<14:43,  1.04it/s]

[84] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

  9%|▊         | 86/1000 [01:26<14:35,  1.04it/s]

[85] Raw: '2
[The Company's operations are subject' → Cleaned: 2

  9%|▊         | 87/1000 [01:27<14:30,  1.05it/s]

[86] Raw: '3
[We are committed to reducing our' → Cleaned: None

  9%|▉         | 88/1000 [01:28<14:23,  1.06it/s]

[87] Raw: '2
[The Company's environmental, social' → Cleaned: 2

  9%|▉         | 89/1000 [01:29<14:13,  1.07it/s]

[88] Raw: '2
[The Company's environmental, social' → Cleaned: 2

  9%|▉         | 90/1000 [01:30<14:08,  1.07it/s]

[89] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

  9%|▉         | 91/1000 [01:31<14:12,  1.07it/s]

[90] Raw: '2
[The company is committed to reducing' → Cleaned: 2

  9%|▉         | 92/1000 [01:32<14:47,  1.02it/s]

[91] Raw: 'The final answer is' → Cleaned: None

  9%|▉         | 93/1000 [01:33<15:15,  1.01s/it]

[92] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

  9%|▉         | 94/1000 [01:34<15:36,  1.03s/it]

[93] Raw: '3
[The Company's environmental policy is' → Cleaned: None

 10%|▉         | 95/1000 [01:35<15:09,  1.00s/it]

[94] Raw: 'The final answer is' → Cleaned: None

 10%|▉         | 96/1000 [01:36<14:53,  1.01it/s]

[95] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 10%|▉         | 97/1000 [01:37<14:37,  1.03it/s]

[96] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 10%|▉         | 98/1000 [01:38<14:22,  1.05it/s]

[97] Raw: 'The final answer is' → Cleaned: None

 10%|▉         | 99/1000 [01:39<14:10,  1.06it/s]

[98] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 10%|█         | 100/1000 [01:39<13:57,  1.08it/s]

[99] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 10%|█         | 101/1000 [01:40<13:54,  1.08it/s]

[100] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 10%|█         | 102/1000 [01:41<13:58,  1.07it/s]

[101] Raw: '3
[The Company's environmental, social' → Cleaned: None

 10%|█         | 103/1000 [01:42<13:54,  1.08it/s]

[102] Raw: '2
[The Company has also been involved' → Cleaned: 2

 10%|█         | 104/1000 [01:43<13:54,  1.07it/s]

[103] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 10%|█         | 105/1000 [01:44<14:43,  1.01it/s]

[104] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 11%|█         | 106/1000 [01:45<15:11,  1.02s/it]

[105] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 11%|█         | 107/1000 [01:46<15:04,  1.01s/it]

[106] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 11%|█         | 108/1000 [01:47<14:41,  1.01it/s]

[107] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 11%|█         | 109/1000 [01:48<14:21,  1.03it/s]

[108] Raw: 'The final answer is' → Cleaned: None

 11%|█         | 110/1000 [01:49<14:14,  1.04it/s]

[109] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 11%|█         | 111/1000 [01:50<14:00,  1.06it/s]

[110] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 11%|█         | 112/1000 [01:51<13:53,  1.07it/s]

[111] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 11%|█▏        | 113/1000 [01:52<13:41,  1.08it/s]

[112] Raw: '2
[The Company's commitment to sustainability' → Cleaned: 2

 11%|█▏        | 114/1000 [01:53<13:32,  1.09it/s]

[113] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 12%|█▏        | 115/1000 [01:54<13:30,  1.09it/s]

[114] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 12%|█▏        | 116/1000 [01:55<13:31,  1.09it/s]

[115] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 12%|█▏        | 117/1000 [01:56<13:29,  1.09it/s]

[116] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 12%|█▏        | 118/1000 [01:57<14:28,  1.02it/s]

[117] Raw: 'The final answer is' → Cleaned: None

 12%|█▏        | 119/1000 [01:58<15:05,  1.03s/it]

[118] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 12%|█▏        | 120/1000 [01:59<14:36,  1.00it/s]

[119] Raw: '3
[The company's environmental policy is' → Cleaned: None

 12%|█▏        | 121/1000 [02:00<14:18,  1.02it/s]

[120] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 12%|█▏        | 122/1000 [02:01<14:05,  1.04it/s]

[121] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 12%|█▏        | 123/1000 [02:02<13:52,  1.05it/s]

[122] Raw: '3
[The Company's operations are subject' → Cleaned: None

 12%|█▏        | 124/1000 [02:02<13:42,  1.06it/s]

[123] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 12%|█▎        | 125/1000 [02:03<13:34,  1.07it/s]

[124] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 13%|█▎        | 126/1000 [02:04<13:29,  1.08it/s]

[125] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 13%|█▎        | 127/1000 [02:05<13:23,  1.09it/s]

[126] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 13%|█▎        | 128/1000 [02:06<13:25,  1.08it/s]

[127] Raw: '2
[The Company has implemented various measures' → Cleaned: 2

 13%|█▎        | 129/1000 [02:07<13:27,  1.08it/s]

[128] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 13%|█▎        | 130/1000 [02:08<13:32,  1.07it/s]

[129] Raw: 'The final answer is' → Cleaned: None

 13%|█▎        | 131/1000 [02:09<14:21,  1.01it/s]

[130] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 13%|█▎        | 132/1000 [02:10<15:00,  1.04s/it]

[131] Raw: 'The final answer is' → Cleaned: None

 13%|█▎        | 133/1000 [02:11<14:34,  1.01s/it]

[132] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 13%|█▎        | 134/1000 [02:12<14:13,  1.01it/s]

[133] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 14%|█▎        | 135/1000 [02:13<13:54,  1.04it/s]

[134] Raw: '0
[The company's commitment to diversity' → Cleaned: 0

 14%|█▎        | 136/1000 [02:14<13:44,  1.05it/s]

[135] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 14%|█▎        | 137/1000 [02:15<13:33,  1.06it/s]

[136] Raw: '0
[Our goal is to be a' → Cleaned: 0

 14%|█▍        | 138/1000 [02:16<13:25,  1.07it/s]

[137] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 14%|█▍        | 139/1000 [02:17<13:16,  1.08it/s]

[138] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 14%|█▍        | 140/1000 [02:18<13:16,  1.08it/s]

[139] Raw: '2
[Our company has a strong commitment' → Cleaned: 2

 14%|█▍        | 141/1000 [02:19<13:14,  1.08it/s]

[140] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 14%|█▍        | 142/1000 [02:19<13:20,  1.07it/s]

[141] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 14%|█▍        | 143/1000 [02:20<13:24,  1.07it/s]

[142] Raw: 'The final answer is' → Cleaned: None

 14%|█▍        | 144/1000 [02:22<14:10,  1.01it/s]

[143] Raw: '2
[Our North America copper mines are' → Cleaned: 2

 14%|█▍        | 145/1000 [02:23<15:01,  1.05s/it]

[144] Raw: 'The final answer is' → Cleaned: None

 15%|█▍        | 146/1000 [02:24<14:30,  1.02s/it]

[145] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 15%|█▍        | 147/1000 [02:25<14:08,  1.01it/s]

[146] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 15%|█▍        | 148/1000 [02:26<13:47,  1.03it/s]

[147] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 15%|█▍        | 149/1000 [02:26<13:37,  1.04it/s]

[148] Raw: 'The final answer is' → Cleaned: None

 15%|█▌        | 150/1000 [02:27<13:28,  1.05it/s]

[149] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 15%|█▌        | 151/1000 [02:28<13:19,  1.06it/s]

[150] Raw: 'The final answer is' → Cleaned: None

 15%|█▌        | 152/1000 [02:29<13:09,  1.07it/s]

[151] Raw: '3
[The company's environmental performance is' → Cleaned: None

 15%|█▌        | 153/1000 [02:30<13:08,  1.07it/s]

[152] Raw: '2
[The company's environmental, social' → Cleaned: 2

 15%|█▌        | 154/1000 [02:31<13:02,  1.08it/s]

[153] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 16%|█▌        | 155/1000 [02:32<13:00,  1.08it/s]

[154] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 16%|█▌        | 156/1000 [02:33<13:23,  1.05it/s]

[155] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 16%|█▌        | 157/1000 [02:34<13:56,  1.01it/s]

[156] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 16%|█▌        | 158/1000 [02:35<14:28,  1.03s/it]

[157] Raw: '2
[The Company's environmental performance is' → Cleaned: 2

 16%|█▌        | 159/1000 [02:36<14:01,  1.00s/it]

[158] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 16%|█▌        | 160/1000 [02:37<13:46,  1.02it/s]

[159] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 16%|█▌        | 161/1000 [02:38<13:36,  1.03it/s]

[160] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 16%|█▌        | 162/1000 [02:39<13:25,  1.04it/s]

[161] Raw: 'The final answer is' → Cleaned: None

 16%|█▋        | 163/1000 [02:40<13:14,  1.05it/s]

[162] Raw: 'The final answer is' → Cleaned: None

 16%|█▋        | 164/1000 [02:41<13:12,  1.05it/s]

[163] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 16%|█▋        | 165/1000 [02:42<13:08,  1.06it/s]

[164] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 17%|█▋        | 166/1000 [02:43<12:58,  1.07it/s]

[165] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 17%|█▋        | 167/1000 [02:44<12:56,  1.07it/s]

[166] Raw: 'The final answer is' → Cleaned: None

 17%|█▋        | 168/1000 [02:45<12:54,  1.07it/s]

[167] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 17%|█▋        | 169/1000 [02:46<13:39,  1.01it/s]

[168] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 17%|█▋        | 170/1000 [02:47<14:03,  1.02s/it]

[169] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 17%|█▋        | 171/1000 [02:48<13:59,  1.01s/it]

[170] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 17%|█▋        | 172/1000 [02:49<13:41,  1.01it/s]

[171] Raw: 'The final answer is' → Cleaned: None

 17%|█▋        | 173/1000 [02:50<13:31,  1.02it/s]

[172] Raw: '1
[The Company's environmental policies and' → Cleaned: 1

 17%|█▋        | 174/1000 [02:51<13:15,  1.04it/s]

[173] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 18%|█▊        | 175/1000 [02:52<13:05,  1.05it/s]

[174] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 18%|█▊        | 176/1000 [02:52<12:57,  1.06it/s]

[175] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 18%|█▊        | 177/1000 [02:53<12:54,  1.06it/s]

[176] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 18%|█▊        | 178/1000 [02:54<12:46,  1.07it/s]

[177] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 18%|█▊        | 179/1000 [02:55<12:37,  1.08it/s]

[178] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 18%|█▊        | 180/1000 [02:56<12:33,  1.09it/s]

[179] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 18%|█▊        | 181/1000 [02:57<12:33,  1.09it/s]

[180] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 18%|█▊        | 182/1000 [02:58<13:25,  1.02it/s]

[181] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 18%|█▊        | 183/1000 [02:59<13:59,  1.03s/it]

[182] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 18%|█▊        | 184/1000 [03:00<13:30,  1.01it/s]

[183] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 18%|█▊        | 185/1000 [03:01<13:11,  1.03it/s]

[184] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 19%|█▊        | 186/1000 [03:02<12:58,  1.05it/s]

[185] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 19%|█▊        | 187/1000 [03:03<12:51,  1.05it/s]

[186] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 19%|█▉        | 188/1000 [03:04<12:51,  1.05it/s]

[187] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 19%|█▉        | 189/1000 [03:05<12:47,  1.06it/s]

[188] Raw: '3
[The company's environmental, social' → Cleaned: None

 19%|█▉        | 190/1000 [03:06<12:44,  1.06it/s]

[189] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 19%|█▉        | 191/1000 [03:07<12:39,  1.06it/s]

[190] Raw: 'The final answer is' → Cleaned: None

 19%|█▉        | 192/1000 [03:08<12:31,  1.08it/s]

[191] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 19%|█▉        | 193/1000 [03:09<12:29,  1.08it/s]

[192] Raw: 'The final answer is' → Cleaned: None

 19%|█▉        | 194/1000 [03:09<12:21,  1.09it/s]

[193] Raw: '3
[Our company is committed to reducing' → Cleaned: None

 20%|█▉        | 195/1000 [03:11<13:06,  1.02it/s]

[194] Raw: 'The final answer is' → Cleaned: None

 20%|█▉        | 196/1000 [03:12<13:50,  1.03s/it]

[195] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 20%|█▉        | 197/1000 [03:13<13:24,  1.00s/it]

[196] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 20%|█▉        | 198/1000 [03:14<13:03,  1.02it/s]

[197] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 20%|█▉        | 199/1000 [03:14<12:47,  1.04it/s]

[198] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 20%|██        | 200/1000 [03:15<12:43,  1.05it/s]

[199] Raw: 'The final answer is' → Cleaned: None

 20%|██        | 201/1000 [03:16<12:34,  1.06it/s]

[200] Raw: 'The final answer is' → Cleaned: None

 20%|██        | 202/1000 [03:17<12:28,  1.07it/s]

[201] Raw: 'The final answer is' → Cleaned: None

 20%|██        | 203/1000 [03:18<12:18,  1.08it/s]

[202] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 20%|██        | 204/1000 [03:19<12:15,  1.08it/s]

[203] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 20%|██        | 205/1000 [03:20<12:13,  1.08it/s]

[204] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 21%|██        | 206/1000 [03:21<12:15,  1.08it/s]

[205] Raw: '2
[The Company's environmental performance is' → Cleaned: 2

 21%|██        | 207/1000 [03:22<12:18,  1.07it/s]

[206] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 21%|██        | 208/1000 [03:23<12:48,  1.03it/s]

[207] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 21%|██        | 209/1000 [03:24<13:44,  1.04s/it]

[208] Raw: '1
[The Freeport-McMo' → Cleaned: 1

 21%|██        | 210/1000 [03:25<13:16,  1.01s/it]

[209] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 21%|██        | 211/1000 [03:26<12:58,  1.01it/s]

[210] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 21%|██        | 212/1000 [03:27<12:44,  1.03it/s]

[211] Raw: '3
[The Company's Board of Directors' → Cleaned: None

 21%|██▏       | 213/1000 [03:28<12:35,  1.04it/s]

[212] Raw: '2
[The company's environmental, social' → Cleaned: 2

 21%|██▏       | 214/1000 [03:29<12:28,  1.05it/s]

[213] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 22%|██▏       | 215/1000 [03:30<12:26,  1.05it/s]

[214] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 22%|██▏       | 216/1000 [03:31<12:15,  1.07it/s]

[215] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 22%|██▏       | 217/1000 [03:32<12:14,  1.07it/s]

[216] Raw: '3
[The Company's environmental performance is' → Cleaned: None

 22%|██▏       | 218/1000 [03:33<12:08,  1.07it/s]

[217] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 22%|██▏       | 219/1000 [03:33<12:08,  1.07it/s]

[218] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 22%|██▏       | 220/1000 [03:35<12:36,  1.03it/s]

[219] Raw: '1
[The Corporation's environmental policy is' → Cleaned: 1

 22%|██▏       | 221/1000 [03:36<12:52,  1.01it/s]

[220] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 22%|██▏       | 222/1000 [03:37<13:20,  1.03s/it]

[221] Raw: 'The final answer is' → Cleaned: None

 22%|██▏       | 223/1000 [03:38<12:51,  1.01it/s]

[222] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 22%|██▏       | 224/1000 [03:39<12:32,  1.03it/s]

[223] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 22%|██▎       | 225/1000 [03:39<12:19,  1.05it/s]

[224] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 23%|██▎       | 226/1000 [03:40<12:07,  1.06it/s]

[225] Raw: '0
[The waste rock (including over' → Cleaned: 0

 23%|██▎       | 227/1000 [03:41<12:00,  1.07it/s]

[226] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 23%|██▎       | 228/1000 [03:42<11:58,  1.07it/s]

[227] Raw: 'The final answer is' → Cleaned: None

 23%|██▎       | 229/1000 [03:43<11:54,  1.08it/s]

[228] Raw: 'The final answer is' → Cleaned: None

 23%|██▎       | 230/1000 [03:44<11:49,  1.08it/s]

[229] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 23%|██▎       | 231/1000 [03:45<11:48,  1.08it/s]

[230] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 23%|██▎       | 232/1000 [03:46<11:48,  1.08it/s]

[231] Raw: '0
[Our commitment to transparency and accountability' → Cleaned: 0

 23%|██▎       | 233/1000 [03:47<12:21,  1.03it/s]

[232] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 23%|██▎       | 234/1000 [03:48<12:41,  1.01it/s]

[233] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 24%|██▎       | 235/1000 [03:49<13:02,  1.02s/it]

[234] Raw: 'The final answer is' → Cleaned: None

 24%|██▎       | 236/1000 [03:50<12:40,  1.00it/s]

[235] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 24%|██▎       | 237/1000 [03:51<12:24,  1.02it/s]

[236] Raw: '3
[Our goal is to minimize our' → Cleaned: None

 24%|██▍       | 238/1000 [03:52<12:13,  1.04it/s]

[237] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 24%|██▍       | 239/1000 [03:53<12:03,  1.05it/s]

[238] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 24%|██▍       | 240/1000 [03:54<11:58,  1.06it/s]

[239] Raw: '2
[The company's environmental, social' → Cleaned: 2

 24%|██▍       | 241/1000 [03:55<11:55,  1.06it/s]

[240] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 24%|██▍       | 242/1000 [03:56<11:52,  1.06it/s]

[241] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 24%|██▍       | 243/1000 [03:57<11:49,  1.07it/s]

[242] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 24%|██▍       | 244/1000 [03:57<11:41,  1.08it/s]

[243] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 24%|██▍       | 245/1000 [03:58<11:38,  1.08it/s]

[244] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 25%|██▍       | 246/1000 [03:59<12:25,  1.01it/s]

[245] Raw: 'The final answer is' → Cleaned: None

 25%|██▍       | 247/1000 [04:01<12:45,  1.02s/it]

[246] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 25%|██▍       | 248/1000 [04:02<12:34,  1.00s/it]

[247] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 25%|██▍       | 249/1000 [04:02<12:10,  1.03it/s]

[248] Raw: '3
[The Company's environmental performance is' → Cleaned: None

 25%|██▌       | 250/1000 [04:03<12:02,  1.04it/s]

[249] Raw: 'The final answer is' → Cleaned: None

 25%|██▌       | 251/1000 [04:04<12:02,  1.04it/s]

[250] Raw: '2
[The Company's environmental performance is' → Cleaned: 2

 25%|██▌       | 252/1000 [04:05<11:53,  1.05it/s]

[251] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 25%|██▌       | 253/1000 [04:06<11:48,  1.05it/s]

[252] Raw: '3
[Our goal is to reduce our' → Cleaned: None

 25%|██▌       | 254/1000 [04:07<11:44,  1.06it/s]

[253] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 26%|██▌       | 255/1000 [04:08<11:40,  1.06it/s]

[254] Raw: '2
[The company's environmental goals are' → Cleaned: 2

 26%|██▌       | 256/1000 [04:09<11:33,  1.07it/s]

[255] Raw: '2
[The Company's environmental goals are' → Cleaned: 2

 26%|██▌       | 257/1000 [04:10<11:28,  1.08it/s]

[256] Raw: 'The final answer is' → Cleaned: None

 26%|██▌       | 258/1000 [04:11<11:25,  1.08it/s]

[257] Raw: 'The final answer is' → Cleaned: None

 26%|██▌       | 259/1000 [04:12<12:04,  1.02it/s]

[258] Raw: 'The final answer is' → Cleaned: None

 26%|██▌       | 260/1000 [04:13<12:39,  1.03s/it]

[259] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 26%|██▌       | 261/1000 [04:14<12:14,  1.01it/s]

[260] Raw: 'The final answer is' → Cleaned: None

 26%|██▌       | 262/1000 [04:15<11:56,  1.03it/s]

[261] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 26%|██▋       | 263/1000 [04:16<11:50,  1.04it/s]

[262] Raw: '2
[The company has made significant progress' → Cleaned: 2

 26%|██▋       | 264/1000 [04:17<11:38,  1.05it/s]

[263] Raw: '3
[Our goal is to reduce our' → Cleaned: None

 26%|██▋       | 265/1000 [04:18<11:31,  1.06it/s]

[264] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 27%|██▋       | 266/1000 [04:19<11:27,  1.07it/s]

[265] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 27%|██▋       | 267/1000 [04:20<11:26,  1.07it/s]

[266] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 27%|██▋       | 268/1000 [04:20<11:21,  1.07it/s]

[267] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 27%|██▋       | 269/1000 [04:21<11:15,  1.08it/s]

[268] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 27%|██▋       | 270/1000 [04:22<11:12,  1.09it/s]

[269] Raw: '3
[The company's environmental, social' → Cleaned: None

 27%|██▋       | 271/1000 [04:23<11:11,  1.09it/s]

[270] Raw: '0
[Our company has a strong commitment' → Cleaned: 0

 27%|██▋       | 272/1000 [04:24<11:51,  1.02it/s]

[271] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 27%|██▋       | 273/1000 [04:25<12:26,  1.03s/it]

[272] Raw: 'The final answer is' → Cleaned: None

 27%|██▋       | 274/1000 [04:26<12:04,  1.00it/s]

[273] Raw: '0
[Our Board of Directors is responsible' → Cleaned: 0

 28%|██▊       | 275/1000 [04:27<11:48,  1.02it/s]

[274] Raw: '0
[Our goal is to create a' → Cleaned: 0

 28%|██▊       | 276/1000 [04:28<11:38,  1.04it/s]

[275] Raw: '2
[Our goal is to be a' → Cleaned: 2

 28%|██▊       | 277/1000 [04:29<11:47,  1.02it/s]

[276] Raw: 'The final answer is' → Cleaned: None

 28%|██▊       | 278/1000 [04:30<11:37,  1.04it/s]

[277] Raw: '2
[The company's commitment to sustainability' → Cleaned: 2

 28%|██▊       | 279/1000 [04:31<11:30,  1.04it/s]

[278] Raw: 'The final answer is' → Cleaned: None

 28%|██▊       | 280/1000 [04:32<11:22,  1.06it/s]

[279] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 28%|██▊       | 281/1000 [04:33<11:15,  1.06it/s]

[280] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 28%|██▊       | 282/1000 [04:34<11:06,  1.08it/s]

[281] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 28%|██▊       | 283/1000 [04:35<11:15,  1.06it/s]

[282] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 28%|██▊       | 284/1000 [04:36<11:06,  1.07it/s]

[283] Raw: '0
[Our company has a strong commitment' → Cleaned: 0

 28%|██▊       | 285/1000 [04:37<11:42,  1.02it/s]

[284] Raw: '3
[The Company's environmental performance is' → Cleaned: None

 29%|██▊       | 286/1000 [04:38<12:18,  1.03s/it]

[285] Raw: '3
[We are committed to reducing our' → Cleaned: None

 29%|██▊       | 287/1000 [04:39<11:52,  1.00it/s]

[286] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 29%|██▉       | 288/1000 [04:40<11:31,  1.03it/s]

[287] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 29%|██▉       | 289/1000 [04:41<11:20,  1.05it/s]

[288] Raw: '1
[The company's environmental performance is' → Cleaned: 1

 29%|██▉       | 290/1000 [04:42<11:13,  1.05it/s]

[289] Raw: 'The final answer is' → Cleaned: None

 29%|██▉       | 291/1000 [04:43<11:07,  1.06it/s]

[290] Raw: '2
[(a) The Company's environmental' → Cleaned: 2

 29%|██▉       | 292/1000 [04:44<11:04,  1.06it/s]

[291] Raw: 'The final answer is' → Cleaned: None

 29%|██▉       | 293/1000 [04:45<11:04,  1.06it/s]

[292] Raw: '3
[The company has a strong commitment' → Cleaned: None

 29%|██▉       | 294/1000 [04:45<10:59,  1.07it/s]

[293] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 30%|██▉       | 295/1000 [04:46<10:55,  1.08it/s]

[294] Raw: '3
[The company is committed to reducing' → Cleaned: None

 30%|██▉       | 296/1000 [04:47<10:44,  1.09it/s]

[295] Raw: 'The final answer is' → Cleaned: None

 30%|██▉       | 297/1000 [04:48<11:12,  1.04it/s]

[296] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 30%|██▉       | 298/1000 [04:49<11:31,  1.01it/s]

[297] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 30%|██▉       | 299/1000 [04:50<12:07,  1.04s/it]

[298] Raw: '0
[The new center will be able' → Cleaned: 0

 30%|███       | 300/1000 [04:51<11:42,  1.00s/it]

[299] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 30%|███       | 301/1000 [04:52<11:27,  1.02it/s]

[300] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 30%|███       | 302/1000 [04:53<11:17,  1.03it/s]

[301] Raw: 'The final answer is' → Cleaned: None

 30%|███       | 303/1000 [04:54<11:05,  1.05it/s]

[302] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 30%|███       | 304/1000 [04:55<10:59,  1.06it/s]

[303] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 30%|███       | 305/1000 [04:56<10:51,  1.07it/s]

[304] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 31%|███       | 306/1000 [04:57<10:46,  1.07it/s]

[305] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 31%|███       | 307/1000 [04:58<10:49,  1.07it/s]

[306] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 31%|███       | 308/1000 [04:59<10:46,  1.07it/s]

[307] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 31%|███       | 309/1000 [05:00<10:44,  1.07it/s]

[308] Raw: '0
[The Company's environmental policy is' → Cleaned: 0

 31%|███       | 310/1000 [05:01<11:14,  1.02it/s]

[309] Raw: 'The final answer is' → Cleaned: None

 31%|███       | 311/1000 [05:02<11:41,  1.02s/it]

[310] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 31%|███       | 312/1000 [05:03<11:41,  1.02s/it]

[311] Raw: '1
[The Company's environmental policies and' → Cleaned: 1

 31%|███▏      | 313/1000 [05:04<11:19,  1.01it/s]

[312] Raw: '3
[The Company's environmental policy is' → Cleaned: None

 31%|███▏      | 314/1000 [05:05<11:06,  1.03it/s]

[313] Raw: '2
[Our goal is to create a' → Cleaned: 2

 32%|███▏      | 315/1000 [05:06<10:56,  1.04it/s]

[314] Raw: '3
[Our goal is to reduce our' → Cleaned: None

 32%|███▏      | 316/1000 [05:07<10:51,  1.05it/s]

[315] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 32%|███▏      | 317/1000 [05:08<10:50,  1.05it/s]

[316] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 32%|███▏      | 318/1000 [05:09<10:45,  1.06it/s]

[317] Raw: '0
[The Company's commitment to sustainability' → Cleaned: 0

 32%|███▏      | 319/1000 [05:10<10:39,  1.06it/s]

[318] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 32%|███▏      | 320/1000 [05:10<10:35,  1.07it/s]

[319] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 32%|███▏      | 321/1000 [05:11<10:27,  1.08it/s]

[320] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 32%|███▏      | 322/1000 [05:12<10:27,  1.08it/s]

[321] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 32%|███▏      | 323/1000 [05:13<11:03,  1.02it/s]

[322] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 32%|███▏      | 324/1000 [05:14<11:28,  1.02s/it]

[323] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 32%|███▎      | 325/1000 [05:15<11:09,  1.01it/s]

[324] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 33%|███▎      | 326/1000 [05:16<10:55,  1.03it/s]

[325] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 33%|███▎      | 327/1000 [05:17<10:39,  1.05it/s]

[326] Raw: '2
[The Corporation's Automotive business is' → Cleaned: 2

 33%|███▎      | 328/1000 [05:18<10:37,  1.05it/s]

[327] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 33%|███▎      | 329/1000 [05:19<10:32,  1.06it/s]

[328] Raw: '2
[The company's commitment to sustainability' → Cleaned: 2

 33%|███▎      | 330/1000 [05:20<10:31,  1.06it/s]

[329] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 33%|███▎      | 331/1000 [05:21<10:25,  1.07it/s]

[330] Raw: '2
[The Company's strategy has been' → Cleaned: 2

 33%|███▎      | 332/1000 [05:22<10:20,  1.08it/s]

[331] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 33%|███▎      | 333/1000 [05:23<10:17,  1.08it/s]

[332] Raw: '1
[Our goal is to minimize our' → Cleaned: 1

 33%|███▎      | 334/1000 [05:24<10:14,  1.08it/s]

[333] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 34%|███▎      | 335/1000 [05:25<10:10,  1.09it/s]

[334] Raw: 'The final answer is' → Cleaned: None

 34%|███▎      | 336/1000 [05:26<10:44,  1.03it/s]

[335] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 34%|███▎      | 337/1000 [05:27<11:17,  1.02s/it]

[336] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 34%|███▍      | 338/1000 [05:28<10:55,  1.01it/s]

[337] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 34%|███▍      | 339/1000 [05:29<10:40,  1.03it/s]

[338] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 34%|███▍      | 340/1000 [05:30<10:31,  1.05it/s]

[339] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 34%|███▍      | 341/1000 [05:31<10:23,  1.06it/s]

[340] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 34%|███▍      | 342/1000 [05:32<10:21,  1.06it/s]

[341] Raw: 'The final answer is' → Cleaned: None

 34%|███▍      | 343/1000 [05:32<10:18,  1.06it/s]

[342] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 34%|███▍      | 344/1000 [05:33<10:13,  1.07it/s]

[343] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 34%|███▍      | 345/1000 [05:34<09:57,  1.10it/s]

[344] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 35%|███▍      | 346/1000 [05:35<09:59,  1.09it/s]

[345] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 35%|███▍      | 347/1000 [05:36<10:00,  1.09it/s]

[346] Raw: '2
[Our goal is to be a' → Cleaned: 2

 35%|███▍      | 348/1000 [05:37<09:56,  1.09it/s]

[347] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 35%|███▍      | 349/1000 [05:38<10:32,  1.03it/s]

[348] Raw: '3
[Our company is committed to reducing' → Cleaned: None

 35%|███▌      | 350/1000 [05:39<11:02,  1.02s/it]

[349] Raw: '3
[The company is committed to reducing' → Cleaned: None

 35%|███▌      | 351/1000 [05:40<10:44,  1.01it/s]

[350] Raw: 'The final answer is' → Cleaned: None

 35%|███▌      | 352/1000 [05:41<10:28,  1.03it/s]

[351] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 35%|███▌      | 353/1000 [05:42<10:19,  1.04it/s]

[352] Raw: 'The final answer is' → Cleaned: None

 35%|███▌      | 354/1000 [05:43<10:12,  1.06it/s]

[353] Raw: '3
[The company has a strong commitment' → Cleaned: None

 36%|███▌      | 355/1000 [05:44<10:13,  1.05it/s]

[354] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 36%|███▌      | 356/1000 [05:45<10:08,  1.06it/s]

[355] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 36%|███▌      | 357/1000 [05:46<10:07,  1.06it/s]

[356] Raw: '3
[Our company is committed to reducing' → Cleaned: None

 36%|███▌      | 358/1000 [05:47<10:04,  1.06it/s]

[357] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 36%|███▌      | 359/1000 [05:48<09:58,  1.07it/s]

[358] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 36%|███▌      | 360/1000 [05:49<09:57,  1.07it/s]

[359] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 36%|███▌      | 361/1000 [05:49<09:53,  1.08it/s]

[360] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 36%|███▌      | 362/1000 [05:51<10:32,  1.01it/s]

[361] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 36%|███▋      | 363/1000 [05:52<11:01,  1.04s/it]

[362] Raw: 'The final answer is' → Cleaned: None

 36%|███▋      | 364/1000 [05:53<10:38,  1.00s/it]

[363] Raw: '3
[The company is committed to reducing' → Cleaned: None

 36%|███▋      | 365/1000 [05:54<10:23,  1.02it/s]

[364] Raw: '0
[The Company’s environmental, social' → Cleaned: 0

 37%|███▋      | 366/1000 [05:55<10:11,  1.04it/s]

[365] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 37%|███▋      | 367/1000 [05:55<10:01,  1.05it/s]

[366] Raw: 'The final answer is' → Cleaned: None

 37%|███▋      | 368/1000 [05:56<09:55,  1.06it/s]

[367] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 37%|███▋      | 369/1000 [05:57<09:54,  1.06it/s]

[368] Raw: '2
[The company's environmental, social' → Cleaned: 2

 37%|███▋      | 370/1000 [05:58<09:46,  1.07it/s]

[369] Raw: 'The final answer is' → Cleaned: None

 37%|███▋      | 371/1000 [05:59<09:45,  1.07it/s]

[370] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 37%|███▋      | 372/1000 [06:00<09:40,  1.08it/s]

[371] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 37%|███▋      | 373/1000 [06:01<09:38,  1.08it/s]

[372] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 37%|███▋      | 374/1000 [06:02<09:36,  1.09it/s]

[373] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 38%|███▊      | 375/1000 [06:03<10:05,  1.03it/s]

[374] Raw: '0
[Our company has a strong commitment' → Cleaned: 0

 38%|███▊      | 376/1000 [06:04<10:44,  1.03s/it]

[375] Raw: 'The final answer is' → Cleaned: None

 38%|███▊      | 377/1000 [06:05<10:22,  1.00it/s]

[376] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 38%|███▊      | 378/1000 [06:06<10:04,  1.03it/s]

[377] Raw: 'The final answer is' → Cleaned: None

 38%|███▊      | 379/1000 [06:07<09:57,  1.04it/s]

[378] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 38%|███▊      | 380/1000 [06:08<09:49,  1.05it/s]

[379] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 38%|███▊      | 381/1000 [06:09<09:46,  1.06it/s]

[380] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 38%|███▊      | 382/1000 [06:10<09:40,  1.07it/s]

[381] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 38%|███▊      | 383/1000 [06:11<09:37,  1.07it/s]

[382] Raw: 'The final answer is' → Cleaned: None

 38%|███▊      | 384/1000 [06:12<09:38,  1.07it/s]

[383] Raw: 'The final answer is' → Cleaned: None

 38%|███▊      | 385/1000 [06:12<09:30,  1.08it/s]

[384] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 39%|███▊      | 386/1000 [06:13<09:24,  1.09it/s]

[385] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 39%|███▊      | 387/1000 [06:14<09:33,  1.07it/s]

[386] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 39%|███▉      | 388/1000 [06:15<09:56,  1.03it/s]

[387] Raw: '2
[The company's environmental policy is' → Cleaned: 2

 39%|███▉      | 389/1000 [06:17<10:30,  1.03s/it]

[388] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 39%|███▉      | 390/1000 [06:17<10:08,  1.00it/s]

[389] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 39%|███▉      | 391/1000 [06:18<09:54,  1.02it/s]

[390] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 39%|███▉      | 392/1000 [06:19<09:46,  1.04it/s]

[391] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 39%|███▉      | 393/1000 [06:20<09:41,  1.04it/s]

[392] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 39%|███▉      | 394/1000 [06:21<09:46,  1.03it/s]

[393] Raw: 'The final answer is' → Cleaned: None

 40%|███▉      | 395/1000 [06:22<09:36,  1.05it/s]

[394] Raw: '2
[The Corporation's operating segments are' → Cleaned: 2

 40%|███▉      | 396/1000 [06:23<09:33,  1.05it/s]

[395] Raw: '2
[The Company's environmental goals are' → Cleaned: 2

 40%|███▉      | 397/1000 [06:24<09:27,  1.06it/s]

[396] Raw: '2
[Our goal is to be a' → Cleaned: 2

 40%|███▉      | 398/1000 [06:25<09:19,  1.08it/s]

[397] Raw: '3
[The company is committed to reducing' → Cleaned: None

 40%|███▉      | 399/1000 [06:26<09:16,  1.08it/s]

[398] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 40%|████      | 400/1000 [06:27<09:50,  1.02it/s]

[399] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 40%|████      | 401/1000 [06:28<10:01,  1.00s/it]

[400] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 40%|████      | 402/1000 [06:29<10:09,  1.02s/it]

[401] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 40%|████      | 403/1000 [06:30<09:49,  1.01it/s]

[402] Raw: '2
[The Company's environmental performance is' → Cleaned: 2

 40%|████      | 404/1000 [06:31<09:43,  1.02it/s]

[403] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 40%|████      | 405/1000 [06:32<09:30,  1.04it/s]

[404] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 41%|████      | 406/1000 [06:33<09:24,  1.05it/s]

[405] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 41%|████      | 407/1000 [06:34<09:17,  1.06it/s]

[406] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 41%|████      | 408/1000 [06:35<09:22,  1.05it/s]

[407] Raw: 'The final answer is' → Cleaned: None

 41%|████      | 409/1000 [06:36<09:17,  1.06it/s]

[408] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 41%|████      | 410/1000 [06:37<09:13,  1.07it/s]

[409] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 41%|████      | 411/1000 [06:37<09:06,  1.08it/s]

[410] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 41%|████      | 412/1000 [06:38<09:02,  1.08it/s]

[411] Raw: 'The final answer is' → Cleaned: None

 41%|████▏     | 413/1000 [06:39<09:35,  1.02it/s]

[412] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 41%|████▏     | 414/1000 [06:41<09:54,  1.01s/it]

[413] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 42%|████▏     | 415/1000 [06:42<09:54,  1.02s/it]

[414] Raw: 'The final answer is' → Cleaned: None

 42%|████▏     | 416/1000 [06:43<09:37,  1.01it/s]

[415] Raw: 'The final answer is' → Cleaned: None

 42%|████▏     | 417/1000 [06:43<09:22,  1.04it/s]

[416] Raw: '1
[Our goal is to minimize our' → Cleaned: 1

 42%|████▏     | 418/1000 [06:44<09:15,  1.05it/s]

[417] Raw: 'The final answer is' → Cleaned: None

 42%|████▏     | 419/1000 [06:45<09:08,  1.06it/s]

[418] Raw: 'The final answer is' → Cleaned: None

 42%|████▏     | 420/1000 [06:46<09:05,  1.06it/s]

[419] Raw: '2
[The Company's environmental performance is' → Cleaned: 2

 42%|████▏     | 421/1000 [06:47<09:03,  1.07it/s]

[420] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 42%|████▏     | 422/1000 [06:48<08:57,  1.08it/s]

[421] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 42%|████▏     | 423/1000 [06:49<08:56,  1.08it/s]

[422] Raw: 'The final answer is' → Cleaned: None

 42%|████▏     | 424/1000 [06:50<08:51,  1.08it/s]

[423] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 42%|████▎     | 425/1000 [06:51<08:53,  1.08it/s]

[424] Raw: '0
[The Company is committed to reducing' → Cleaned: 0

 43%|████▎     | 426/1000 [06:52<09:26,  1.01it/s]

[425] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 43%|████▎     | 427/1000 [06:53<09:50,  1.03s/it]

[426] Raw: '1
[Our goal is to be a' → Cleaned: 1

 43%|████▎     | 428/1000 [06:54<09:29,  1.00it/s]

[427] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 43%|████▎     | 429/1000 [06:55<09:12,  1.03it/s]

[428] Raw: '2
[The company's environmental policy is' → Cleaned: 2

 43%|████▎     | 430/1000 [06:56<09:01,  1.05it/s]

[429] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 43%|████▎     | 431/1000 [06:57<08:55,  1.06it/s]

[430] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 43%|████▎     | 432/1000 [06:58<08:52,  1.07it/s]

[431] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 43%|████▎     | 433/1000 [06:59<08:49,  1.07it/s]

[432] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 43%|████▎     | 434/1000 [07:00<08:49,  1.07it/s]

[433] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 44%|████▎     | 435/1000 [07:00<08:46,  1.07it/s]

[434] Raw: '0
[They demonstrate how we will meet' → Cleaned: 0

 44%|████▎     | 436/1000 [07:01<08:46,  1.07it/s]

[435] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 44%|████▎     | 437/1000 [07:02<08:46,  1.07it/s]

[436] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 44%|████▍     | 438/1000 [07:03<08:40,  1.08it/s]

[437] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 44%|████▍     | 439/1000 [07:04<09:10,  1.02it/s]

[438] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 44%|████▍     | 440/1000 [07:05<09:29,  1.02s/it]

[439] Raw: '3
[The company is committed to reducing' → Cleaned: None

 44%|████▍     | 441/1000 [07:06<09:12,  1.01it/s]

[440] Raw: '3
[The company's commitment to sustainability' → Cleaned: None

 44%|████▍     | 442/1000 [07:07<08:58,  1.04it/s]

[441] Raw: 'The final answer is' → Cleaned: None

 44%|████▍     | 443/1000 [07:08<08:47,  1.06it/s]

[442] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 44%|████▍     | 444/1000 [07:09<08:43,  1.06it/s]

[443] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 44%|████▍     | 445/1000 [07:10<08:42,  1.06it/s]

[444] Raw: '0
[Our goal is to create a' → Cleaned: 0

 45%|████▍     | 446/1000 [07:11<08:46,  1.05it/s]

[445] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 45%|████▍     | 447/1000 [07:12<08:43,  1.06it/s]

[446] Raw: 'The final answer is' → Cleaned: None

 45%|████▍     | 448/1000 [07:13<08:41,  1.06it/s]

[447] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 45%|████▍     | 449/1000 [07:14<08:38,  1.06it/s]

[448] Raw: '3
[The Company is committed to reducing' → Cleaned: None

 45%|████▌     | 450/1000 [07:15<08:31,  1.08it/s]

[449] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 45%|████▌     | 451/1000 [07:16<08:25,  1.09it/s]

[450] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 45%|████▌     | 452/1000 [07:17<08:51,  1.03it/s]

[451] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 45%|████▌     | 453/1000 [07:18<09:20,  1.02s/it]

[452] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 45%|████▌     | 454/1000 [07:19<09:02,  1.01it/s]

[453] Raw: 'The final answer is' → Cleaned: None

 46%|████▌     | 455/1000 [07:20<08:48,  1.03it/s]

[454] Raw: 'The final answer is' → Cleaned: None

 46%|████▌     | 456/1000 [07:21<08:41,  1.04it/s]

[455] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 46%|████▌     | 457/1000 [07:22<08:35,  1.05it/s]

[456] Raw: '3
[The Company is committed to reducing' → Cleaned: None

 46%|████▌     | 458/1000 [07:22<08:28,  1.07it/s]

[457] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 46%|████▌     | 459/1000 [07:23<08:26,  1.07it/s]

[458] Raw: '0
[Our Board of Directors is responsible' → Cleaned: 0

 46%|████▌     | 460/1000 [07:24<08:22,  1.07it/s]

[459] Raw: '2
[The company's environmental, social' → Cleaned: 2

 46%|████▌     | 461/1000 [07:25<08:20,  1.08it/s]

[460] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 46%|████▌     | 462/1000 [07:26<08:19,  1.08it/s]

[461] Raw: 'The final answer is' → Cleaned: None

 46%|████▋     | 463/1000 [07:27<08:18,  1.08it/s]

[462] Raw: '2
[The company's environmental, social' → Cleaned: 2

 46%|████▋     | 464/1000 [07:28<08:14,  1.08it/s]

[463] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 46%|████▋     | 465/1000 [07:29<08:38,  1.03it/s]

[464] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 47%|████▋     | 466/1000 [07:30<09:06,  1.02s/it]

[465] Raw: '0
[Our goal is to be a' → Cleaned: 0

 47%|████▋     | 467/1000 [07:31<08:48,  1.01it/s]

[466] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 47%|████▋     | 468/1000 [07:32<08:36,  1.03it/s]

[467] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 47%|████▋     | 469/1000 [07:33<08:27,  1.05it/s]

[468] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 47%|████▋     | 470/1000 [07:34<08:24,  1.05it/s]

[469] Raw: 'The final answer is' → Cleaned: None

 47%|████▋     | 471/1000 [07:35<08:17,  1.06it/s]

[470] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 47%|████▋     | 472/1000 [07:36<08:13,  1.07it/s]

[471] Raw: '0
[The company has a strong track' → Cleaned: 0

 47%|████▋     | 473/1000 [07:37<08:13,  1.07it/s]

[472] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 47%|████▋     | 474/1000 [07:38<08:12,  1.07it/s]

[473] Raw: '1
[The Company's environmental, social' → Cleaned: 1

 48%|████▊     | 475/1000 [07:39<08:08,  1.07it/s]

[474] Raw: 'The final answer is' → Cleaned: None

 48%|████▊     | 476/1000 [07:40<08:06,  1.08it/s]

[475] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 48%|████▊     | 477/1000 [07:40<08:10,  1.07it/s]

[476] Raw: 'The final answer is' → Cleaned: None

 48%|████▊     | 478/1000 [07:42<08:28,  1.03it/s]

[477] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 48%|████▊     | 479/1000 [07:43<08:59,  1.03s/it]

[478] Raw: 'The final answer is' → Cleaned: None

 48%|████▊     | 480/1000 [07:44<08:38,  1.00it/s]

[479] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 48%|████▊     | 481/1000 [07:45<08:31,  1.02it/s]

[480] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 48%|████▊     | 482/1000 [07:45<08:20,  1.03it/s]

[481] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 48%|████▊     | 483/1000 [07:46<08:13,  1.05it/s]

[482] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 48%|████▊     | 484/1000 [07:47<08:08,  1.06it/s]

[483] Raw: '1
[The Company's environmental policies and' → Cleaned: 1

 48%|████▊     | 485/1000 [07:48<07:54,  1.08it/s]

[484] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 49%|████▊     | 486/1000 [07:49<07:56,  1.08it/s]

[485] Raw: '2
[The company's environmental policy is' → Cleaned: 2

 49%|████▊     | 487/1000 [07:50<07:55,  1.08it/s]

[486] Raw: '3
[The Company's environmental policy is' → Cleaned: None

 49%|████▉     | 488/1000 [07:51<07:52,  1.08it/s]

[487] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 49%|████▉     | 489/1000 [07:52<07:52,  1.08it/s]

[488] Raw: 'The final answer is' → Cleaned: None

 49%|████▉     | 490/1000 [07:53<08:00,  1.06it/s]

[489] Raw: '3
[The Company's environmental performance is' → Cleaned: None

 49%|████▉     | 491/1000 [07:54<08:22,  1.01it/s]

[490] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 49%|████▉     | 492/1000 [07:55<08:48,  1.04s/it]

[491] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 49%|████▉     | 493/1000 [07:56<08:32,  1.01s/it]

[492] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 49%|████▉     | 494/1000 [07:57<08:16,  1.02it/s]

[493] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 50%|████▉     | 495/1000 [07:58<08:07,  1.04it/s]

[494] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 50%|████▉     | 496/1000 [07:59<08:00,  1.05it/s]

[495] Raw: '3
[Our goal is to reduce our' → Cleaned: None

 50%|████▉     | 497/1000 [08:00<07:54,  1.06it/s]

[496] Raw: '0
[The company's board of directors' → Cleaned: 0

 50%|████▉     | 498/1000 [08:01<07:53,  1.06it/s]

[497] Raw: '1
[The Company's environmental, social' → Cleaned: 1

 50%|████▉     | 499/1000 [08:02<07:52,  1.06it/s]

[498] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 50%|█████     | 500/1000 [08:03<07:46,  1.07it/s]

[499] Raw: '0
[The company's board of directors' → Cleaned: 0

 50%|█████     | 501/1000 [08:04<07:45,  1.07it/s]

[500] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 50%|█████     | 502/1000 [08:04<07:41,  1.08it/s]

[501] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 50%|█████     | 503/1000 [08:06<08:04,  1.03it/s]

[502] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 50%|█████     | 504/1000 [08:07<08:14,  1.00it/s]

[503] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 50%|█████     | 505/1000 [08:08<08:23,  1.02s/it]

[504] Raw: 'The final answer is' → Cleaned: None

 51%|█████     | 506/1000 [08:09<08:07,  1.01it/s]

[505] Raw: '0
[Our goal is to be a' → Cleaned: 0

 51%|█████     | 507/1000 [08:09<07:57,  1.03it/s]

[506] Raw: 'The final answer is' → Cleaned: None

 51%|█████     | 508/1000 [08:10<07:56,  1.03it/s]

[507] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 51%|█████     | 509/1000 [08:11<07:49,  1.05it/s]

[508] Raw: '0
[Our commitment to transparency and accountability' → Cleaned: 0

 51%|█████     | 510/1000 [08:12<07:46,  1.05it/s]

[509] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 51%|█████     | 511/1000 [08:13<07:41,  1.06it/s]

[510] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 51%|█████     | 512/1000 [08:14<07:37,  1.07it/s]

[511] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 51%|█████▏    | 513/1000 [08:15<07:31,  1.08it/s]

[512] Raw: '2
[The company's commitment to sustainability' → Cleaned: 2

 51%|█████▏    | 514/1000 [08:16<07:31,  1.08it/s]

[513] Raw: 'The final answer is' → Cleaned: None

 52%|█████▏    | 515/1000 [08:17<07:30,  1.08it/s]

[514] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 52%|█████▏    | 516/1000 [08:18<07:55,  1.02it/s]

[515] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 52%|█████▏    | 517/1000 [08:19<08:13,  1.02s/it]

[516] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 52%|█████▏    | 518/1000 [08:20<08:06,  1.01s/it]

[517] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 52%|█████▏    | 519/1000 [08:21<07:50,  1.02it/s]

[518] Raw: '3
[The Company's environmental policy is' → Cleaned: None

 52%|█████▏    | 520/1000 [08:22<07:39,  1.04it/s]

[519] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 52%|█████▏    | 521/1000 [08:23<07:34,  1.05it/s]

[520] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 52%|█████▏    | 522/1000 [08:24<07:20,  1.08it/s]

[521] Raw: '3
[The company's environmental goals are' → Cleaned: None

 52%|█████▏    | 523/1000 [08:25<07:21,  1.08it/s]

[522] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 52%|█████▏    | 524/1000 [08:26<07:20,  1.08it/s]

[523] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 52%|█████▎    | 525/1000 [08:27<07:25,  1.07it/s]

[524] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 53%|█████▎    | 526/1000 [08:27<07:20,  1.08it/s]

[525] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 53%|█████▎    | 527/1000 [08:28<07:17,  1.08it/s]

[526] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 53%|█████▎    | 528/1000 [08:29<07:18,  1.08it/s]

[527] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 53%|█████▎    | 529/1000 [08:30<07:43,  1.02it/s]

[528] Raw: '2
[The company's environmental, social' → Cleaned: 2

 53%|█████▎    | 530/1000 [08:32<07:59,  1.02s/it]

[529] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 53%|█████▎    | 531/1000 [08:32<07:47,  1.00it/s]

[530] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 53%|█████▎    | 532/1000 [08:33<07:33,  1.03it/s]

[531] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 53%|█████▎    | 533/1000 [08:34<07:25,  1.05it/s]

[532] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 53%|█████▎    | 534/1000 [08:35<07:21,  1.06it/s]

[533] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 54%|█████▎    | 535/1000 [08:36<07:19,  1.06it/s]

[534] Raw: '2
[The company's commitment to sustainability' → Cleaned: 2

 54%|█████▎    | 536/1000 [08:37<07:16,  1.06it/s]

[535] Raw: 'The final answer is' → Cleaned: None

 54%|█████▎    | 537/1000 [08:38<07:12,  1.07it/s]

[536] Raw: 'The final answer is' → Cleaned: None

 54%|█████▍    | 538/1000 [08:39<07:09,  1.08it/s]

[537] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 54%|█████▍    | 539/1000 [08:40<07:11,  1.07it/s]

[538] Raw: 'The final answer is' → Cleaned: None

 54%|█████▍    | 540/1000 [08:41<07:09,  1.07it/s]

[539] Raw: 'The final answer is' → Cleaned: None

 54%|█████▍    | 541/1000 [08:42<07:04,  1.08it/s]

[540] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 54%|█████▍    | 542/1000 [08:43<07:28,  1.02it/s]

[541] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 54%|█████▍    | 543/1000 [08:44<07:48,  1.02s/it]

[542] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 54%|█████▍    | 544/1000 [08:45<07:32,  1.01it/s]

[543] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 55%|█████▍    | 545/1000 [08:46<07:20,  1.03it/s]

[544] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 55%|█████▍    | 546/1000 [08:47<07:13,  1.05it/s]

[545] Raw: '2
[The company's commitment to sustainability' → Cleaned: 2

 55%|█████▍    | 547/1000 [08:48<07:11,  1.05it/s]

[546] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 55%|█████▍    | 548/1000 [08:49<07:07,  1.06it/s]

[547] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 55%|█████▍    | 549/1000 [08:49<07:00,  1.07it/s]

[548] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 55%|█████▌    | 550/1000 [08:50<07:04,  1.06it/s]

[549] Raw: '0
[Our company is committed to conducting' → Cleaned: 0

 55%|█████▌    | 551/1000 [08:51<07:02,  1.06it/s]

[550] Raw: '2
[The company's environmental, social' → Cleaned: 2

 55%|█████▌    | 552/1000 [08:52<07:00,  1.07it/s]

[551] Raw: 'The final answer is' → Cleaned: None

 55%|█████▌    | 553/1000 [08:53<06:55,  1.08it/s]

[552] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 55%|█████▌    | 554/1000 [08:54<06:55,  1.07it/s]

[553] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 56%|█████▌    | 555/1000 [08:55<07:28,  1.01s/it]

[554] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 56%|█████▌    | 556/1000 [08:57<07:45,  1.05s/it]

[555] Raw: '3
[The Company's environmental, social' → Cleaned: None

 56%|█████▌    | 557/1000 [08:57<07:25,  1.01s/it]

[556] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 56%|█████▌    | 558/1000 [08:58<07:13,  1.02it/s]

[557] Raw: 'The final answer is' → Cleaned: None

 56%|█████▌    | 559/1000 [08:59<07:04,  1.04it/s]

[558] Raw: 'The final answer is' → Cleaned: None

 56%|█████▌    | 560/1000 [09:00<06:59,  1.05it/s]

[559] Raw: 'The final answer is' → Cleaned: None

 56%|█████▌    | 561/1000 [09:01<06:56,  1.05it/s]

[560] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 56%|█████▌    | 562/1000 [09:02<06:54,  1.06it/s]

[561] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 56%|█████▋    | 563/1000 [09:03<06:50,  1.07it/s]

[562] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 56%|█████▋    | 564/1000 [09:04<06:46,  1.07it/s]

[563] Raw: '3
[Our goal is to reduce our' → Cleaned: None

 56%|█████▋    | 565/1000 [09:05<06:44,  1.08it/s]

[564] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 57%|█████▋    | 566/1000 [09:06<06:40,  1.08it/s]

[565] Raw: 'The final answer is' → Cleaned: None

 57%|█████▋    | 567/1000 [09:07<06:39,  1.08it/s]

[566] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 57%|█████▋    | 568/1000 [09:08<07:00,  1.03it/s]

[567] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 57%|█████▋    | 569/1000 [09:09<07:23,  1.03s/it]

[568] Raw: '2
[The company's environmental, social' → Cleaned: 2

 57%|█████▋    | 570/1000 [09:10<07:15,  1.01s/it]

[569] Raw: 'The final answer is' → Cleaned: None

 57%|█████▋    | 571/1000 [09:11<07:00,  1.02it/s]

[570] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 57%|█████▋    | 572/1000 [09:12<06:54,  1.03it/s]

[571] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 57%|█████▋    | 573/1000 [09:13<06:49,  1.04it/s]

[572] Raw: '0
[The Company's environmental, social' → Cleaned: 0

 57%|█████▋    | 574/1000 [09:14<06:46,  1.05it/s]

[573] Raw: '0
[Our goal is to be a' → Cleaned: 0

 57%|█████▊    | 575/1000 [09:15<06:42,  1.06it/s]

[574] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 58%|█████▊    | 576/1000 [09:15<06:40,  1.06it/s]

[575] Raw: '1
[Our goal is to reduce our' → Cleaned: 1

 58%|█████▊    | 577/1000 [09:16<06:37,  1.06it/s]

[576] Raw: '0
[The Company is committed to reducing' → Cleaned: 0

 58%|█████▊    | 578/1000 [09:17<06:30,  1.08it/s]

[577] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 58%|█████▊    | 579/1000 [09:18<06:27,  1.09it/s]

[578] Raw: '2
[The Company's major business operations' → Cleaned: 2

 58%|█████▊    | 580/1000 [09:19<06:40,  1.05it/s]

[579] Raw: '1
[The Corporation's financial statements are' → Cleaned: 1

 58%|█████▊    | 581/1000 [09:20<06:53,  1.01it/s]

[580] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 58%|█████▊    | 582/1000 [09:21<07:13,  1.04s/it]

[581] Raw: '1
[The Company's environmental policies and' → Cleaned: 1

 58%|█████▊    | 583/1000 [09:22<06:59,  1.01s/it]

[582] Raw: '3
[The company's environmental, social' → Cleaned: None

 58%|█████▊    | 584/1000 [09:23<06:48,  1.02it/s]

[583] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 58%|█████▊    | 585/1000 [09:24<06:37,  1.04it/s]

[584] Raw: 'The final answer is' → Cleaned: None

 59%|█████▊    | 586/1000 [09:25<06:34,  1.05it/s]

[585] Raw: '2
[Our commitment to sustainability is reflected' → Cleaned: 2

 59%|█████▊    | 587/1000 [09:26<06:30,  1.06it/s]

[586] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 59%|█████▉    | 588/1000 [09:27<06:29,  1.06it/s]

[587] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 59%|█████▉    | 589/1000 [09:28<06:26,  1.06it/s]

[588] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 59%|█████▉    | 590/1000 [09:29<06:22,  1.07it/s]

[589] Raw: '2
[The company's environmental policy is' → Cleaned: 2

 59%|█████▉    | 591/1000 [09:30<06:18,  1.08it/s]

[590] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 59%|█████▉    | 592/1000 [09:31<06:17,  1.08it/s]

[591] Raw: 'The final answer is' → Cleaned: None

 59%|█████▉    | 593/1000 [09:32<06:34,  1.03it/s]

[592] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 59%|█████▉    | 594/1000 [09:33<06:48,  1.01s/it]

[593] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 60%|█████▉    | 595/1000 [09:34<06:53,  1.02s/it]

[594] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 60%|█████▉    | 596/1000 [09:35<06:40,  1.01it/s]

[595] Raw: 'The final answer is' → Cleaned: None

 60%|█████▉    | 597/1000 [09:36<06:29,  1.03it/s]

[596] Raw: '0
[The Company's commitment to sustainability' → Cleaned: 0

 60%|█████▉    | 598/1000 [09:37<06:22,  1.05it/s]

[597] Raw: 'The final answer is' → Cleaned: None

 60%|█████▉    | 599/1000 [09:38<06:19,  1.06it/s]

[598] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 60%|██████    | 600/1000 [09:39<06:15,  1.07it/s]

[599] Raw: '2
[The Company's environmental performance is' → Cleaned: 2

 60%|██████    | 601/1000 [09:39<06:13,  1.07it/s]

[600] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 60%|██████    | 602/1000 [09:40<06:10,  1.08it/s]

[601] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 60%|██████    | 603/1000 [09:41<06:10,  1.07it/s]

[602] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 60%|██████    | 604/1000 [09:42<06:05,  1.08it/s]

[603] Raw: '3
[The company's environmental, social' → Cleaned: None

 60%|██████    | 605/1000 [09:43<06:05,  1.08it/s]

[604] Raw: 'The final answer is' → Cleaned: None

 61%|██████    | 606/1000 [09:44<06:20,  1.04it/s]

[605] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 61%|██████    | 607/1000 [09:45<06:32,  1.00it/s]

[606] Raw: '3
[The Company’s environmental, social' → Cleaned: None

 61%|██████    | 608/1000 [09:46<06:37,  1.02s/it]

[607] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 61%|██████    | 609/1000 [09:47<06:25,  1.01it/s]

[608] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 61%|██████    | 610/1000 [09:48<06:15,  1.04it/s]

[609] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 61%|██████    | 611/1000 [09:49<06:06,  1.06it/s]

[610] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 61%|██████    | 612/1000 [09:50<06:02,  1.07it/s]

[611] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 61%|██████▏   | 613/1000 [09:51<06:01,  1.07it/s]

[612] Raw: '0
[Our commitment to sustainability is reflected' → Cleaned: 0

 61%|██████▏   | 614/1000 [09:52<06:01,  1.07it/s]

[613] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 62%|██████▏   | 615/1000 [09:53<05:58,  1.07it/s]

[614] Raw: '3
[The Company's commitment to sustainability' → Cleaned: None

 62%|██████▏   | 616/1000 [09:54<05:56,  1.08it/s]

[615] Raw: '1
[Our goal is to minimize our' → Cleaned: 1

 62%|██████▏   | 617/1000 [09:55<05:55,  1.08it/s]

[616] Raw: 'The final answer is' → Cleaned: None

 62%|██████▏   | 618/1000 [09:56<05:51,  1.09it/s]

[617] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 62%|██████▏   | 619/1000 [09:57<06:11,  1.03it/s]

[618] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 62%|██████▏   | 620/1000 [09:58<06:23,  1.01s/it]

[619] Raw: 'The final answer is' → Cleaned: None

 62%|██████▏   | 621/1000 [09:59<06:23,  1.01s/it]

[620] Raw: 'The final answer is' → Cleaned: None

 62%|██████▏   | 622/1000 [10:00<06:11,  1.02it/s]

[621] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 62%|██████▏   | 623/1000 [10:01<06:01,  1.04it/s]

[622] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 62%|██████▏   | 624/1000 [10:02<06:00,  1.04it/s]

[623] Raw: '2
[The company's commitment to sustainability' → Cleaned: 2

 62%|██████▎   | 625/1000 [10:02<05:55,  1.06it/s]

[624] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 63%|██████▎   | 626/1000 [10:03<05:50,  1.07it/s]

[625] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 63%|██████▎   | 627/1000 [10:04<05:51,  1.06it/s]

[626] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 63%|██████▎   | 628/1000 [10:05<05:47,  1.07it/s]

[627] Raw: '0
[The company's commitment to sustainability' → Cleaned: 0

 63%|██████▎   | 629/1000 [10:06<05:44,  1.08it/s]

[628] Raw: '0
[The Company also expects to continue' → Cleaned: 0

 63%|██████▎   | 630/1000 [10:07<05:42,  1.08it/s]

[629] Raw: '3
[Our goal is to reduce our' → Cleaned: None

 63%|██████▎   | 631/1000 [10:08<05:40,  1.09it/s]

[630] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 63%|██████▎   | 632/1000 [10:09<06:01,  1.02it/s]

[631] Raw: '2
[Our company has a long history' → Cleaned: 2

 63%|██████▎   | 633/1000 [10:10<06:13,  1.02s/it]

[632] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 63%|██████▎   | 634/1000 [10:11<06:05,  1.00it/s]

[633] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 64%|██████▎   | 635/1000 [10:12<05:56,  1.02it/s]

[634] Raw: 'The final answer is' → Cleaned: None

 64%|██████▎   | 636/1000 [10:13<05:48,  1.05it/s]

[635] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 64%|██████▎   | 637/1000 [10:14<05:44,  1.05it/s]

[636] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 64%|██████▍   | 638/1000 [10:15<05:42,  1.06it/s]

[637] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 64%|██████▍   | 639/1000 [10:16<05:38,  1.07it/s]

[638] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 64%|██████▍   | 640/1000 [10:17<05:38,  1.06it/s]

[639] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 64%|██████▍   | 641/1000 [10:18<05:33,  1.08it/s]

[640] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 64%|██████▍   | 642/1000 [10:19<05:29,  1.09it/s]

[641] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 64%|██████▍   | 643/1000 [10:19<05:29,  1.08it/s]

[642] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 64%|██████▍   | 644/1000 [10:20<05:29,  1.08it/s]

[643] Raw: '1
[Our goal is to reduce our' → Cleaned: 1

 64%|██████▍   | 645/1000 [10:21<05:46,  1.02it/s]

[644] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 65%|██████▍   | 646/1000 [10:23<06:09,  1.04s/it]

[645] Raw: '2
[The Company has a long history' → Cleaned: 2

 65%|██████▍   | 647/1000 [10:24<05:56,  1.01s/it]

[646] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 65%|██████▍   | 648/1000 [10:25<05:46,  1.02it/s]

[647] Raw: 'The final answer is' → Cleaned: None

 65%|██████▍   | 649/1000 [10:25<05:41,  1.03it/s]

[648] Raw: '3
[We are committed to reducing our' → Cleaned: None

 65%|██████▌   | 650/1000 [10:26<05:36,  1.04it/s]

[649] Raw: '2
[The company's environmental goals are' → Cleaned: 2

 65%|██████▌   | 651/1000 [10:27<05:31,  1.05it/s]

[650] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 65%|██████▌   | 652/1000 [10:28<05:28,  1.06it/s]

[651] Raw: '2
[The company has a strong commitment' → Cleaned: 2

 65%|██████▌   | 653/1000 [10:29<05:24,  1.07it/s]

[652] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 65%|██████▌   | 654/1000 [10:30<05:20,  1.08it/s]

[653] Raw: '2
[The company's environmental, social' → Cleaned: 2

 66%|██████▌   | 655/1000 [10:31<05:17,  1.09it/s]

[654] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 66%|██████▌   | 656/1000 [10:32<05:17,  1.08it/s]

[655] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 66%|██████▌   | 657/1000 [10:33<05:15,  1.09it/s]

[656] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 66%|██████▌   | 658/1000 [10:34<05:33,  1.03it/s]

[657] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 66%|██████▌   | 659/1000 [10:35<05:48,  1.02s/it]

[658] Raw: '3
[Our goal is to minimize our' → Cleaned: None

 66%|██████▌   | 660/1000 [10:36<05:37,  1.01it/s]

[659] Raw: 'The final answer is' → Cleaned: None

 66%|██████▌   | 661/1000 [10:37<05:30,  1.02it/s]

[660] Raw: 'The final answer is' → Cleaned: None

 66%|██████▌   | 662/1000 [10:38<05:24,  1.04it/s]

[661] Raw: '2
[The Company’s assumption for the' → Cleaned: 2

 66%|██████▋   | 663/1000 [10:39<05:19,  1.05it/s]

[662] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 66%|██████▋   | 664/1000 [10:40<05:16,  1.06it/s]

[663] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 66%|██████▋   | 665/1000 [10:41<05:13,  1.07it/s]

[664] Raw: '0
[The company's commitment to diversity' → Cleaned: 0

 67%|██████▋   | 666/1000 [10:42<05:11,  1.07it/s]

[665] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 67%|██████▋   | 667/1000 [10:42<05:08,  1.08it/s]

[666] Raw: '0
[The Company’s Board of Directors' → Cleaned: 0

 67%|██████▋   | 668/1000 [10:43<05:06,  1.08it/s]

[667] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 67%|██████▋   | 669/1000 [10:44<05:06,  1.08it/s]

[668] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 67%|██████▋   | 670/1000 [10:45<05:05,  1.08it/s]

[669] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 67%|██████▋   | 671/1000 [10:46<05:25,  1.01it/s]

[670] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 67%|██████▋   | 672/1000 [10:48<05:41,  1.04s/it]

[671] Raw: 'The final answer is' → Cleaned: None

 67%|██████▋   | 673/1000 [10:48<05:28,  1.00s/it]

[672] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 67%|██████▋   | 674/1000 [10:49<05:19,  1.02it/s]

[673] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 68%|██████▊   | 675/1000 [10:50<05:15,  1.03it/s]

[674] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 68%|██████▊   | 676/1000 [10:51<05:10,  1.04it/s]

[675] Raw: '2
[The Company's environmental performance is' → Cleaned: 2

 68%|██████▊   | 677/1000 [10:52<05:06,  1.05it/s]

[676] Raw: '3
[The company has a strong commitment' → Cleaned: None

 68%|██████▊   | 678/1000 [10:53<05:03,  1.06it/s]

[677] Raw: '3
[Our company has a strong commitment' → Cleaned: None

 68%|██████▊   | 679/1000 [10:54<04:58,  1.07it/s]

[678] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 68%|██████▊   | 680/1000 [10:55<04:55,  1.08it/s]

[679] Raw: '3
[The company has a long history' → Cleaned: None

 68%|██████▊   | 681/1000 [10:56<04:58,  1.07it/s]

[680] Raw: 'The final answer is' → Cleaned: None

 68%|██████▊   | 682/1000 [10:57<04:56,  1.07it/s]

[681] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 68%|██████▊   | 683/1000 [10:58<04:55,  1.07it/s]

[682] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 68%|██████▊   | 684/1000 [10:59<05:04,  1.04it/s]

[683] Raw: '2
[The company's environmental policy is' → Cleaned: 2

 68%|██████▊   | 685/1000 [11:00<05:25,  1.03s/it]

[684] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 69%|██████▊   | 686/1000 [11:01<05:14,  1.00s/it]

[685] Raw: 'The final answer is' → Cleaned: None

 69%|██████▊   | 687/1000 [11:02<05:04,  1.03it/s]

[686] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 69%|██████▉   | 688/1000 [11:03<05:00,  1.04it/s]

[687] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 69%|██████▉   | 689/1000 [11:04<04:58,  1.04it/s]

[688] Raw: '0
[The company's board of directors' → Cleaned: 0

 69%|██████▉   | 690/1000 [11:05<04:55,  1.05it/s]

[689] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 69%|██████▉   | 691/1000 [11:06<04:52,  1.06it/s]

[690] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 69%|██████▉   | 692/1000 [11:06<04:49,  1.06it/s]

[691] Raw: 'The final answer is' → Cleaned: None

 69%|██████▉   | 693/1000 [11:07<04:47,  1.07it/s]

[692] Raw: '2
[Our goal is to create a' → Cleaned: 2

 69%|██████▉   | 694/1000 [11:08<04:45,  1.07it/s]

[693] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 70%|██████▉   | 695/1000 [11:09<04:42,  1.08it/s]

[694] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 70%|██████▉   | 696/1000 [11:10<04:51,  1.04it/s]

[695] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 70%|██████▉   | 697/1000 [11:11<05:01,  1.01it/s]

[696] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 70%|██████▉   | 698/1000 [11:12<05:10,  1.03s/it]

[697] Raw: 'The final answer is' → Cleaned: None

 70%|██████▉   | 699/1000 [11:13<05:01,  1.00s/it]

[698] Raw: '3
[The company is committed to reducing' → Cleaned: None

 70%|███████   | 700/1000 [11:14<04:53,  1.02it/s]

[699] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 70%|███████   | 701/1000 [11:15<04:48,  1.04it/s]

[700] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 70%|███████   | 702/1000 [11:16<04:45,  1.04it/s]

[701] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 70%|███████   | 703/1000 [11:17<04:40,  1.06it/s]

[702] Raw: '1
[Our goal is to minimize our' → Cleaned: 1

 70%|███████   | 704/1000 [11:18<04:38,  1.06it/s]

[703] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 70%|███████   | 705/1000 [11:19<04:35,  1.07it/s]

[704] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 71%|███████   | 706/1000 [11:20<04:33,  1.08it/s]

[705] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 71%|███████   | 707/1000 [11:21<04:30,  1.08it/s]

[706] Raw: 'The final answer is' → Cleaned: None

 71%|███████   | 708/1000 [11:22<04:29,  1.08it/s]

[707] Raw: '0
[The company's commitment to sustainability' → Cleaned: 0

 71%|███████   | 709/1000 [11:23<04:42,  1.03it/s]

[708] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 71%|███████   | 710/1000 [11:24<04:49,  1.00it/s]

[709] Raw: '3
[The company's environmental performance is' → Cleaned: None

 71%|███████   | 711/1000 [11:25<04:55,  1.02s/it]

[710] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 71%|███████   | 712/1000 [11:26<04:44,  1.01it/s]

[711] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 71%|███████▏  | 713/1000 [11:27<04:38,  1.03it/s]

[712] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 71%|███████▏  | 714/1000 [11:28<04:33,  1.05it/s]

[713] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 72%|███████▏  | 715/1000 [11:29<04:31,  1.05it/s]

[714] Raw: 'The final answer is' → Cleaned: None

 72%|███████▏  | 716/1000 [11:30<04:29,  1.05it/s]

[715] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 72%|███████▏  | 717/1000 [11:31<04:26,  1.06it/s]

[716] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 72%|███████▏  | 718/1000 [11:31<04:24,  1.07it/s]

[717] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 72%|███████▏  | 719/1000 [11:32<04:22,  1.07it/s]

[718] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 72%|███████▏  | 720/1000 [11:33<04:19,  1.08it/s]

[719] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 72%|███████▏  | 721/1000 [11:34<04:16,  1.09it/s]

[720] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 72%|███████▏  | 722/1000 [11:35<04:28,  1.04it/s]

[721] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 72%|███████▏  | 723/1000 [11:36<04:38,  1.01s/it]

[722] Raw: 'The final answer is' → Cleaned: None

 72%|███████▏  | 724/1000 [11:37<04:40,  1.02s/it]

[723] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 72%|███████▎  | 725/1000 [11:38<04:31,  1.01it/s]

[724] Raw: '3
[The company has a strong commitment' → Cleaned: None

 73%|███████▎  | 726/1000 [11:39<04:26,  1.03it/s]

[725] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 73%|███████▎  | 727/1000 [11:40<04:22,  1.04it/s]

[726] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 73%|███████▎  | 728/1000 [11:41<04:18,  1.05it/s]

[727] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 73%|███████▎  | 729/1000 [11:42<04:14,  1.06it/s]

[728] Raw: 'The final answer is' → Cleaned: None

 73%|███████▎  | 730/1000 [11:43<04:12,  1.07it/s]

[729] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 73%|███████▎  | 731/1000 [11:44<04:10,  1.07it/s]

[730] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 73%|███████▎  | 732/1000 [11:45<04:08,  1.08it/s]

[731] Raw: 'The final answer is' → Cleaned: None

 73%|███████▎  | 733/1000 [11:46<04:06,  1.08it/s]

[732] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 73%|███████▎  | 734/1000 [11:47<04:00,  1.10it/s]

[733] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 74%|███████▎  | 735/1000 [11:48<04:16,  1.03it/s]

[734] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 74%|███████▎  | 736/1000 [11:49<04:26,  1.01s/it]

[735] Raw: '1
[Our goal is to create long' → Cleaned: 1

 74%|███████▎  | 737/1000 [11:50<04:23,  1.00s/it]

[736] Raw: '2
[The Company's commitment to sustainability' → Cleaned: 2

 74%|███████▍  | 738/1000 [11:51<04:17,  1.02it/s]

[737] Raw: '0
[The Board of Directors is responsible' → Cleaned: 0

 74%|███████▍  | 739/1000 [11:52<04:12,  1.04it/s]

[738] Raw: 'The final answer is' → Cleaned: None

 74%|███████▍  | 740/1000 [11:53<04:09,  1.04it/s]

[739] Raw: '3
[The Company's operations are subject' → Cleaned: None

 74%|███████▍  | 741/1000 [11:54<04:07,  1.04it/s]

[740] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 74%|███████▍  | 742/1000 [11:54<04:03,  1.06it/s]

[741] Raw: '3
[The company's environmental, social' → Cleaned: None

 74%|███████▍  | 743/1000 [11:55<04:02,  1.06it/s]

[742] Raw: 'The final answer is' → Cleaned: None

 74%|███████▍  | 744/1000 [11:56<03:59,  1.07it/s]

[743] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 74%|███████▍  | 745/1000 [11:57<03:57,  1.07it/s]

[744] Raw: 'The final answer is' → Cleaned: None

 75%|███████▍  | 746/1000 [11:58<03:54,  1.08it/s]

[745] Raw: '3
[The Company is committed to reducing' → Cleaned: None

 75%|███████▍  | 747/1000 [11:59<03:51,  1.09it/s]

[746] Raw: '0
[The company has a strong track' → Cleaned: 0

 75%|███████▍  | 748/1000 [12:00<04:05,  1.03it/s]

[747] Raw: '3
[The Company's environmental policy is' → Cleaned: None

 75%|███████▍  | 749/1000 [12:01<04:16,  1.02s/it]

[748] Raw: '3
[The Company is committed to reducing' → Cleaned: None

 75%|███████▌  | 750/1000 [12:02<04:08,  1.01it/s]

[749] Raw: '0
[The company's board of directors' → Cleaned: 0

 75%|███████▌  | 751/1000 [12:03<04:02,  1.03it/s]

[750] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 75%|███████▌  | 752/1000 [12:04<03:57,  1.04it/s]

[751] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 75%|███████▌  | 753/1000 [12:05<03:53,  1.06it/s]

[752] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 75%|███████▌  | 754/1000 [12:06<03:55,  1.05it/s]

[753] Raw: '1
[Our goal is to minimize our' → Cleaned: 1

 76%|███████▌  | 755/1000 [12:07<03:52,  1.06it/s]

[754] Raw: '0
[The Company's environmental policy is' → Cleaned: 0

 76%|███████▌  | 756/1000 [12:08<03:49,  1.06it/s]

[755] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 76%|███████▌  | 757/1000 [12:09<03:47,  1.07it/s]

[756] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 76%|███████▌  | 758/1000 [12:10<03:46,  1.07it/s]

[757] Raw: '3
[Our company is committed to reducing' → Cleaned: None

 76%|███████▌  | 759/1000 [12:11<03:43,  1.08it/s]

[758] Raw: '3
[The Company's operations are subject' → Cleaned: None

 76%|███████▌  | 760/1000 [12:11<03:42,  1.08it/s]

[759] Raw: '3
[The Company's operations are subject' → Cleaned: None

 76%|███████▌  | 761/1000 [12:13<03:53,  1.02it/s]

[760] Raw: '3
[The company's environmental performance is' → Cleaned: None

 76%|███████▌  | 762/1000 [12:14<04:03,  1.03s/it]

[761] Raw: '2
[The company's environmental, social' → Cleaned: 2

 76%|███████▋  | 763/1000 [12:15<03:56,  1.00it/s]

[762] Raw: '1
[Our goal is to minimize our' → Cleaned: 1

 76%|███████▋  | 764/1000 [12:16<03:49,  1.03it/s]

[763] Raw: '3
[The Company will also ensure that' → Cleaned: None

 76%|███████▋  | 765/1000 [12:16<03:45,  1.04it/s]

[764] Raw: 'The final answer is' → Cleaned: None

 77%|███████▋  | 766/1000 [12:17<03:42,  1.05it/s]

[765] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 77%|███████▋  | 767/1000 [12:18<03:39,  1.06it/s]

[766] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 77%|███████▋  | 768/1000 [12:19<03:36,  1.07it/s]

[767] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 77%|███████▋  | 769/1000 [12:20<03:33,  1.08it/s]

[768] Raw: '2
[The company's commitment to diversity' → Cleaned: 2

 77%|███████▋  | 770/1000 [12:21<03:32,  1.08it/s]

[769] Raw: 'The final answer is' → Cleaned: None

 77%|███████▋  | 771/1000 [12:22<03:32,  1.08it/s]

[770] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 77%|███████▋  | 772/1000 [12:23<03:31,  1.08it/s]

[771] Raw: '1
[The Company's operations are subject' → Cleaned: 1

 77%|███████▋  | 773/1000 [12:24<03:30,  1.08it/s]

[772] Raw: 'The final answer is' → Cleaned: None

 77%|███████▋  | 774/1000 [12:25<03:42,  1.01it/s]

[773] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 78%|███████▊  | 775/1000 [12:26<03:51,  1.03s/it]

[774] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 78%|███████▊  | 776/1000 [12:27<03:43,  1.00it/s]

[775] Raw: 'The final answer is' → Cleaned: None

 78%|███████▊  | 777/1000 [12:28<03:37,  1.03it/s]

[776] Raw: '3
[The Company's operations are subject' → Cleaned: None

 78%|███████▊  | 778/1000 [12:29<03:32,  1.04it/s]

[777] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 78%|███████▊  | 779/1000 [12:30<03:28,  1.06it/s]

[778] Raw: '2
[Our goal is to reduce our' → Cleaned: 2

 78%|███████▊  | 780/1000 [12:31<03:26,  1.06it/s]

[779] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 78%|███████▊  | 781/1000 [12:32<03:24,  1.07it/s]

[780] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 78%|███████▊  | 782/1000 [12:33<03:24,  1.07it/s]

[781] Raw: 'The final answer is' → Cleaned: None

 78%|███████▊  | 783/1000 [12:34<03:21,  1.08it/s]

[782] Raw: '3
[The Company's environmental, social' → Cleaned: None

 78%|███████▊  | 784/1000 [12:34<03:20,  1.08it/s]

[783] Raw: '3
[The Company's environmental policy is' → Cleaned: None

 78%|███████▊  | 785/1000 [12:35<03:19,  1.08it/s]

[784] Raw: 'The final answer is' → Cleaned: None

 79%|███████▊  | 786/1000 [12:36<03:19,  1.07it/s]

[785] Raw: '0
[The Company’s environmental policy is' → Cleaned: 0

 79%|███████▊  | 787/1000 [12:37<03:29,  1.02it/s]

[786] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 79%|███████▉  | 788/1000 [12:39<03:41,  1.04s/it]

[787] Raw: '2
[The Company's business and financial' → Cleaned: 2

 79%|███████▉  | 789/1000 [12:40<03:31,  1.00s/it]

[788] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 79%|███████▉  | 790/1000 [12:40<03:26,  1.02it/s]

[789] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 79%|███████▉  | 791/1000 [12:41<03:22,  1.03it/s]

[790] Raw: '0
[The company has a strong track' → Cleaned: 0

 79%|███████▉  | 792/1000 [12:42<03:19,  1.04it/s]

[791] Raw: '2
[Our commitment to sustainability is reflected' → Cleaned: 2

 79%|███████▉  | 793/1000 [12:43<03:16,  1.05it/s]

[792] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 79%|███████▉  | 794/1000 [12:44<03:13,  1.06it/s]

[793] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 80%|███████▉  | 795/1000 [12:45<03:11,  1.07it/s]

[794] Raw: '2
[The Company has not been required' → Cleaned: 2

 80%|███████▉  | 796/1000 [12:46<03:09,  1.07it/s]

[795] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 80%|███████▉  | 797/1000 [12:47<03:08,  1.08it/s]

[796] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 80%|███████▉  | 798/1000 [12:48<03:07,  1.07it/s]

[797] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 80%|███████▉  | 799/1000 [12:49<03:11,  1.05it/s]

[798] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 80%|████████  | 800/1000 [12:50<03:18,  1.01it/s]

[799] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 80%|████████  | 801/1000 [12:51<03:27,  1.05s/it]

[800] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 80%|████████  | 802/1000 [12:52<03:20,  1.01s/it]

[801] Raw: '0
[The company's commitment to diversity' → Cleaned: 0

 80%|████████  | 803/1000 [12:53<03:14,  1.01it/s]

[802] Raw: '1
[The company's environmental performance is' → Cleaned: 1

 80%|████████  | 804/1000 [12:54<03:12,  1.02it/s]

[803] Raw: '2
[The company's environmental, social' → Cleaned: 2

 80%|████████  | 805/1000 [12:55<03:07,  1.04it/s]

[804] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 81%|████████  | 806/1000 [12:56<03:04,  1.05it/s]

[805] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 81%|████████  | 807/1000 [12:57<03:01,  1.06it/s]

[806] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 81%|████████  | 808/1000 [12:58<02:59,  1.07it/s]

[807] Raw: 'The final answer is' → Cleaned: None

 81%|████████  | 809/1000 [12:59<02:57,  1.07it/s]

[808] Raw: '0
[Our goal is to be a' → Cleaned: 0

 81%|████████  | 810/1000 [12:59<02:56,  1.08it/s]

[809] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 81%|████████  | 811/1000 [13:00<02:53,  1.09it/s]

[810] Raw: '0
[The Company's environmental policy is' → Cleaned: 0

 81%|████████  | 812/1000 [13:01<03:00,  1.04it/s]

[811] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 81%|████████▏ | 813/1000 [13:03<03:06,  1.00it/s]

[812] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 81%|████████▏ | 814/1000 [13:04<03:11,  1.03s/it]

[813] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 82%|████████▏ | 815/1000 [13:05<03:03,  1.01it/s]

[814] Raw: 'The final answer is' → Cleaned: None

 82%|████████▏ | 816/1000 [13:05<02:58,  1.03it/s]

[815] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 82%|████████▏ | 817/1000 [13:06<02:55,  1.04it/s]

[816] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 82%|████████▏ | 818/1000 [13:07<02:52,  1.05it/s]

[817] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 82%|████████▏ | 819/1000 [13:08<02:50,  1.06it/s]

[818] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 82%|████████▏ | 820/1000 [13:09<02:49,  1.06it/s]

[819] Raw: '1
[The Company's environmental, social' → Cleaned: 1

 82%|████████▏ | 821/1000 [13:10<02:47,  1.07it/s]

[820] Raw: 'The final answer is' → Cleaned: None

 82%|████████▏ | 822/1000 [13:11<02:45,  1.08it/s]

[821] Raw: '0
[The Company's commitment to sustainability' → Cleaned: 0

 82%|████████▏ | 823/1000 [13:12<02:44,  1.08it/s]

[822] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 82%|████████▏ | 824/1000 [13:13<02:43,  1.07it/s]

[823] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 82%|████████▎ | 825/1000 [13:14<02:52,  1.02it/s]

[824] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 83%|████████▎ | 826/1000 [13:15<02:57,  1.02s/it]

[825] Raw: 'The final answer is' → Cleaned: None

 83%|████████▎ | 827/1000 [13:16<02:55,  1.02s/it]

[826] Raw: '3
[The Company's environmental performance is' → Cleaned: None

 83%|████████▎ | 828/1000 [13:17<02:49,  1.01it/s]

[827] Raw: 'The final answer is' → Cleaned: None

 83%|████████▎ | 829/1000 [13:18<02:45,  1.03it/s]

[828] Raw: '2
[The company's commitment to sustainability' → Cleaned: 2

 83%|████████▎ | 830/1000 [13:19<02:42,  1.05it/s]

[829] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 83%|████████▎ | 831/1000 [13:20<02:39,  1.06it/s]

[830] Raw: '2
[Our goal is to be a' → Cleaned: 2

 83%|████████▎ | 832/1000 [13:21<02:38,  1.06it/s]

[831] Raw: '2
[Our goal is to create a' → Cleaned: 2

 83%|████████▎ | 833/1000 [13:22<02:37,  1.06it/s]

[832] Raw: 'The final answer is' → Cleaned: None

 83%|████████▎ | 834/1000 [13:23<02:36,  1.06it/s]

[833] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 84%|████████▎ | 835/1000 [13:24<02:34,  1.07it/s]

[834] Raw: '2
[The Corporation's environmental policies and' → Cleaned: 2

 84%|████████▎ | 836/1000 [13:24<02:33,  1.07it/s]

[835] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 84%|████████▎ | 837/1000 [13:25<02:30,  1.08it/s]

[836] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 84%|████████▍ | 838/1000 [13:26<02:38,  1.02it/s]

[837] Raw: '3
[The company's environmental performance is' → Cleaned: None

 84%|████████▍ | 839/1000 [13:28<02:42,  1.01s/it]

[838] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 84%|████████▍ | 840/1000 [13:29<02:40,  1.00s/it]

[839] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 84%|████████▍ | 841/1000 [13:29<02:34,  1.03it/s]

[840] Raw: 'The final answer is' → Cleaned: None

 84%|████████▍ | 842/1000 [13:30<02:31,  1.04it/s]

[841] Raw: 'The final answer is' → Cleaned: None

 84%|████████▍ | 843/1000 [13:31<02:30,  1.05it/s]

[842] Raw: 'The final answer is' → Cleaned: None

 84%|████████▍ | 844/1000 [13:32<02:27,  1.06it/s]

[843] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 84%|████████▍ | 845/1000 [13:33<02:26,  1.06it/s]

[844] Raw: '1
[Our goal is to minimize our' → Cleaned: 1

 85%|████████▍ | 846/1000 [13:34<02:24,  1.07it/s]

[845] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 85%|████████▍ | 847/1000 [13:35<02:22,  1.08it/s]

[846] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 85%|████████▍ | 848/1000 [13:36<02:20,  1.08it/s]

[847] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 85%|████████▍ | 849/1000 [13:37<02:19,  1.09it/s]

[848] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 85%|████████▌ | 850/1000 [13:38<02:18,  1.09it/s]

[849] Raw: '2
[The company's environmental, social' → Cleaned: 2

 85%|████████▌ | 851/1000 [13:39<02:24,  1.03it/s]

[850] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 85%|████████▌ | 852/1000 [13:40<02:29,  1.01s/it]

[851] Raw: '3
[The company has a strong commitment' → Cleaned: None

 85%|████████▌ | 853/1000 [13:41<02:26,  1.01it/s]

[852] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 85%|████████▌ | 854/1000 [13:42<02:22,  1.03it/s]

[853] Raw: 'The final answer is' → Cleaned: None

 86%|████████▌ | 855/1000 [13:43<02:19,  1.04it/s]

[854] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 86%|████████▌ | 856/1000 [13:44<02:17,  1.05it/s]

[855] Raw: 'The final answer is' → Cleaned: None

 86%|████████▌ | 857/1000 [13:45<02:15,  1.06it/s]

[856] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 86%|████████▌ | 858/1000 [13:46<02:13,  1.06it/s]

[857] Raw: '2
[Our Technology Center directs a development' → Cleaned: 2

 86%|████████▌ | 859/1000 [13:46<02:11,  1.07it/s]

[858] Raw: '3
[Our goal is to minimize our' → Cleaned: None

 86%|████████▌ | 860/1000 [13:47<02:10,  1.07it/s]

[859] Raw: 'The final answer is' → Cleaned: None

 86%|████████▌ | 861/1000 [13:48<02:09,  1.07it/s]

[860] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 86%|████████▌ | 862/1000 [13:49<02:07,  1.08it/s]

[861] Raw: '3
[The Company’s environmental performance is' → Cleaned: None

 86%|████████▋ | 863/1000 [13:50<02:06,  1.09it/s]

[862] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 86%|████████▋ | 864/1000 [13:51<02:12,  1.03it/s]

[863] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 86%|████████▋ | 865/1000 [13:52<02:19,  1.04s/it]

[864] Raw: '1
[Our company is committed to reducing' → Cleaned: 1

 87%|████████▋ | 866/1000 [13:53<02:14,  1.01s/it]

[865] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 87%|████████▋ | 867/1000 [13:54<02:11,  1.01it/s]

[866] Raw: '2
[The revolving term of the credit' → Cleaned: 2

 87%|████████▋ | 868/1000 [13:55<02:08,  1.03it/s]

[867] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 87%|████████▋ | 869/1000 [13:56<02:06,  1.04it/s]

[868] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 87%|████████▋ | 870/1000 [13:57<02:03,  1.05it/s]

[869] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 87%|████████▋ | 871/1000 [13:58<02:02,  1.06it/s]

[870] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 87%|████████▋ | 872/1000 [13:59<01:59,  1.07it/s]

[871] Raw: '0
[Our company has a strong commitment' → Cleaned: 0

 87%|████████▋ | 873/1000 [14:00<01:58,  1.07it/s]

[872] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 87%|████████▋ | 874/1000 [14:01<01:56,  1.08it/s]

[873] Raw: 'The final answer is' → Cleaned: None

 88%|████████▊ | 875/1000 [14:02<01:55,  1.08it/s]

[874] Raw: '1
[Our goal is to minimize our' → Cleaned: 1

 88%|████████▊ | 876/1000 [14:03<01:54,  1.08it/s]

[875] Raw: '3
[The Company's environmental policy is' → Cleaned: None

 88%|████████▊ | 877/1000 [14:04<01:59,  1.03it/s]

[876] Raw: 'The final answer is' → Cleaned: None

 88%|████████▊ | 878/1000 [14:05<02:05,  1.03s/it]

[877] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 88%|████████▊ | 879/1000 [14:06<02:01,  1.00s/it]

[878] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 88%|████████▊ | 880/1000 [14:07<01:57,  1.02it/s]

[879] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 88%|████████▊ | 881/1000 [14:08<01:55,  1.03it/s]

[880] Raw: '3
[The Company's environmental policy is' → Cleaned: None

 88%|████████▊ | 882/1000 [14:09<01:53,  1.04it/s]

[881] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 88%|████████▊ | 883/1000 [14:10<01:51,  1.05it/s]

[882] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 88%|████████▊ | 884/1000 [14:11<01:49,  1.06it/s]

[883] Raw: '1
[Our goal is to minimize our' → Cleaned: 1

 88%|████████▊ | 885/1000 [14:11<01:47,  1.07it/s]

[884] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 89%|████████▊ | 886/1000 [14:12<01:45,  1.08it/s]

[885] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 89%|████████▊ | 887/1000 [14:13<01:43,  1.09it/s]

[886] Raw: 'The final answer is' → Cleaned: None

 89%|████████▉ | 888/1000 [14:14<01:42,  1.09it/s]

[887] Raw: '1
[The Company's environmental policy is' → Cleaned: 1

 89%|████████▉ | 889/1000 [14:15<01:42,  1.08it/s]

[888] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 89%|████████▉ | 890/1000 [14:16<01:47,  1.03it/s]

[889] Raw: '2
[Our goal is to be a' → Cleaned: 2

 89%|████████▉ | 891/1000 [14:17<01:52,  1.03s/it]

[890] Raw: '3
[The company is committed to reducing' → Cleaned: None

 89%|████████▉ | 892/1000 [14:18<01:47,  1.00it/s]

[891] Raw: 'The final answer is' → Cleaned: None

 89%|████████▉ | 893/1000 [14:19<01:44,  1.02it/s]

[892] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 89%|████████▉ | 894/1000 [14:20<01:42,  1.04it/s]

[893] Raw: 'The final answer is' → Cleaned: None

 90%|████████▉ | 895/1000 [14:21<01:40,  1.05it/s]

[894] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 90%|████████▉ | 896/1000 [14:22<01:37,  1.06it/s]

[895] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 90%|████████▉ | 897/1000 [14:23<01:35,  1.08it/s]

[896] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 90%|████████▉ | 898/1000 [14:24<01:33,  1.09it/s]

[897] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 90%|████████▉ | 899/1000 [14:25<01:33,  1.09it/s]

[898] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 90%|█████████ | 900/1000 [14:26<01:31,  1.09it/s]

[899] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 90%|█████████ | 901/1000 [14:27<01:31,  1.09it/s]

[900] Raw: '1
[The Company's environmental, social' → Cleaned: 1

 90%|█████████ | 902/1000 [14:27<01:32,  1.06it/s]

[901] Raw: 'The final answer is' → Cleaned: None

 90%|█████████ | 903/1000 [14:29<01:34,  1.02it/s]

[902] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 90%|█████████ | 904/1000 [14:30<01:39,  1.04s/it]

[903] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 90%|█████████ | 905/1000 [14:31<01:35,  1.01s/it]

[904] Raw: '1
[Our business position will also depend' → Cleaned: 1

 91%|█████████ | 906/1000 [14:32<01:32,  1.02it/s]

[905] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 91%|█████████ | 907/1000 [14:33<01:29,  1.03it/s]

[906] Raw: 'The final answer is' → Cleaned: None

 91%|█████████ | 908/1000 [14:33<01:28,  1.04it/s]

[907] Raw: 'The final answer is' → Cleaned: None

 91%|█████████ | 909/1000 [14:34<01:26,  1.05it/s]

[908] Raw: '2
[The company's environmental, social' → Cleaned: 2

 91%|█████████ | 910/1000 [14:35<01:24,  1.07it/s]

[909] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 91%|█████████ | 911/1000 [14:36<01:22,  1.07it/s]

[910] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 91%|█████████ | 912/1000 [14:37<01:21,  1.08it/s]

[911] Raw: 'The final answer is' → Cleaned: None

 91%|█████████▏| 913/1000 [14:38<01:20,  1.08it/s]

[912] Raw: '1
[The Company's environmental policies and' → Cleaned: 1

 91%|█████████▏| 914/1000 [14:39<01:19,  1.09it/s]

[913] Raw: '0
[The company has a strong commitment' → Cleaned: 0

 92%|█████████▏| 915/1000 [14:40<01:20,  1.05it/s]

[914] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 92%|█████████▏| 916/1000 [14:41<01:22,  1.02it/s]

[915] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 92%|█████████▏| 917/1000 [14:42<01:24,  1.02s/it]

[916] Raw: 'The final answer is' → Cleaned: None

 92%|█████████▏| 918/1000 [14:43<01:21,  1.01it/s]

[917] Raw: '3
[The company's environmental performance is' → Cleaned: None

 92%|█████████▏| 919/1000 [14:44<01:18,  1.03it/s]

[918] Raw: '3
[The company's environmental performance is' → Cleaned: None

 92%|█████████▏| 920/1000 [14:45<01:16,  1.05it/s]

[919] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 92%|█████████▏| 921/1000 [14:46<01:14,  1.06it/s]

[920] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 92%|█████████▏| 922/1000 [14:47<01:12,  1.07it/s]

[921] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 92%|█████████▏| 923/1000 [14:48<01:11,  1.08it/s]

[922] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 92%|█████████▏| 924/1000 [14:49<01:10,  1.09it/s]

[923] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 92%|█████████▎| 925/1000 [14:49<01:09,  1.09it/s]

[924] Raw: 'The final answer is' → Cleaned: None

 93%|█████████▎| 926/1000 [14:50<01:08,  1.08it/s]

[925] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 93%|█████████▎| 927/1000 [14:51<01:07,  1.08it/s]

[926] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 93%|█████████▎| 928/1000 [14:52<01:09,  1.03it/s]

[927] Raw: 'The final answer is' → Cleaned: None

 93%|█████████▎| 929/1000 [14:54<01:12,  1.01s/it]

[928] Raw: 'The final answer is' → Cleaned: None

 93%|█████████▎| 930/1000 [14:55<01:13,  1.05s/it]

[929] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 93%|█████████▎| 931/1000 [14:56<01:09,  1.01s/it]

[930] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 93%|█████████▎| 932/1000 [14:57<01:07,  1.01it/s]

[931] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 93%|█████████▎| 933/1000 [14:57<01:04,  1.04it/s]

[932] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 93%|█████████▎| 934/1000 [14:58<01:03,  1.04it/s]

[933] Raw: '2
[The company's environmental, social' → Cleaned: 2

 94%|█████████▎| 935/1000 [14:59<01:01,  1.05it/s]

[934] Raw: '2
[The company's environmental performance is' → Cleaned: 2

 94%|█████████▎| 936/1000 [15:00<01:00,  1.06it/s]

[935] Raw: '2
[The Company is committed to reducing' → Cleaned: 2

 94%|█████████▎| 937/1000 [15:01<00:58,  1.07it/s]

[936] Raw: 'The final answer is' → Cleaned: None

 94%|█████████▍| 938/1000 [15:02<00:57,  1.08it/s]

[937] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 94%|█████████▍| 939/1000 [15:03<00:56,  1.08it/s]

[938] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 94%|█████████▍| 940/1000 [15:04<00:55,  1.09it/s]

[939] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 94%|█████████▍| 941/1000 [15:05<00:57,  1.03it/s]

[940] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 94%|█████████▍| 942/1000 [15:06<00:58,  1.00s/it]

[941] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 94%|█████████▍| 943/1000 [15:07<00:57,  1.01s/it]

[942] Raw: 'The final answer is' → Cleaned: None

 94%|█████████▍| 944/1000 [15:08<00:55,  1.01it/s]

[943] Raw: '3
[The company's environmental, social' → Cleaned: None

 94%|█████████▍| 945/1000 [15:09<00:53,  1.04it/s]

[944] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 95%|█████████▍| 946/1000 [15:10<00:51,  1.05it/s]

[945] Raw: '0
[Our goal is to be a' → Cleaned: 0

 95%|█████████▍| 947/1000 [15:11<00:50,  1.05it/s]

[946] Raw: '2
[Our company has a strong commitment' → Cleaned: 2

 95%|█████████▍| 948/1000 [15:12<00:49,  1.06it/s]

[947] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 95%|█████████▍| 949/1000 [15:13<00:47,  1.07it/s]

[948] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 95%|█████████▌| 950/1000 [15:14<00:46,  1.07it/s]

[949] Raw: '0
[Our company is committed to reducing' → Cleaned: 0

 95%|█████████▌| 951/1000 [15:14<00:45,  1.09it/s]

[950] Raw: 'The final answer is' → Cleaned: None

 95%|█████████▌| 952/1000 [15:15<00:44,  1.09it/s]

[951] Raw: 'The final answer is' → Cleaned: None

 95%|█████████▌| 953/1000 [15:16<00:43,  1.09it/s]

[952] Raw: '3
[The company is committed to reducing' → Cleaned: None

 95%|█████████▌| 954/1000 [15:17<00:45,  1.02it/s]

[953] Raw: 'The final answer is' → Cleaned: None

 96%|█████████▌| 955/1000 [15:19<00:45,  1.01s/it]

[954] Raw: '2
[The low end of the range' → Cleaned: 2

 96%|█████████▌| 956/1000 [15:20<00:44,  1.01s/it]

[955] Raw: 'The final answer is' → Cleaned: None

 96%|█████████▌| 957/1000 [15:20<00:41,  1.02it/s]

[956] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 96%|█████████▌| 958/1000 [15:21<00:40,  1.04it/s]

[957] Raw: 'The final answer is' → Cleaned: None

 96%|█████████▌| 959/1000 [15:22<00:38,  1.05it/s]

[958] Raw: '3
[The Company's environmental, social' → Cleaned: None

 96%|█████████▌| 960/1000 [15:23<00:37,  1.07it/s]

[959] Raw: '0
[The Company's Board of Directors' → Cleaned: 0

 96%|█████████▌| 961/1000 [15:24<00:36,  1.06it/s]

[960] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 96%|█████████▌| 962/1000 [15:25<00:35,  1.07it/s]

[961] Raw: '2
[The Company's environmental, social' → Cleaned: 2

 96%|█████████▋| 963/1000 [15:26<00:34,  1.07it/s]

[962] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 96%|█████████▋| 964/1000 [15:27<00:33,  1.08it/s]

[963] Raw: '2
[The company's environmental policy is' → Cleaned: 2

 96%|█████████▋| 965/1000 [15:28<00:32,  1.09it/s]

[964] Raw: '3
[Our company is committed to reducing' → Cleaned: None

 97%|█████████▋| 966/1000 [15:29<00:31,  1.09it/s]

[965] Raw: 'The final answer is' → Cleaned: None

 97%|█████████▋| 967/1000 [15:30<00:32,  1.01it/s]

[966] Raw: '0
[Our goal is to create a' → Cleaned: 0

 97%|█████████▋| 968/1000 [15:31<00:32,  1.02s/it]

[967] Raw: 'The final answer is' → Cleaned: None

 97%|█████████▋| 969/1000 [15:32<00:31,  1.01s/it]

[968] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 97%|█████████▋| 970/1000 [15:33<00:29,  1.02it/s]

[969] Raw: '2
[The company's environmental, social' → Cleaned: 2

 97%|█████████▋| 971/1000 [15:34<00:28,  1.03it/s]

[970] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 97%|█████████▋| 972/1000 [15:35<00:26,  1.05it/s]

[971] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 97%|█████████▋| 973/1000 [15:36<00:25,  1.05it/s]

[972] Raw: '1
[The Corporation believes that any payments' → Cleaned: 1

 97%|█████████▋| 974/1000 [15:37<00:24,  1.06it/s]

[973] Raw: '3
[The company's environmental, social' → Cleaned: None

 98%|█████████▊| 975/1000 [15:37<00:23,  1.07it/s]

[974] Raw: 'The final answer is' → Cleaned: None

 98%|█████████▊| 976/1000 [15:38<00:22,  1.08it/s]

[975] Raw: 'The final answer is' → Cleaned: None

 98%|█████████▊| 977/1000 [15:39<00:21,  1.09it/s]

[976] Raw: 'The final answer is' → Cleaned: None

 98%|█████████▊| 978/1000 [15:40<00:20,  1.09it/s]

[977] Raw: '2
[Our company is committed to reducing' → Cleaned: 2

 98%|█████████▊| 979/1000 [15:41<00:19,  1.08it/s]

[978] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

 98%|█████████▊| 980/1000 [15:42<00:19,  1.02it/s]

[979] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

 98%|█████████▊| 981/1000 [15:43<00:19,  1.03s/it]

[980] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 98%|█████████▊| 982/1000 [15:44<00:17,  1.00it/s]

[981] Raw: 'The final answer is' → Cleaned: None

 98%|█████████▊| 983/1000 [15:45<00:16,  1.02it/s]

[982] Raw: '2
[The company is committed to reducing' → Cleaned: 2

 98%|█████████▊| 984/1000 [15:46<00:15,  1.04it/s]

[983] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 98%|█████████▊| 985/1000 [15:47<00:14,  1.06it/s]

[984] Raw: '1
[The Company's environmental policies and' → Cleaned: 1

 99%|█████████▊| 986/1000 [15:48<00:13,  1.07it/s]

[985] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 99%|█████████▊| 987/1000 [15:49<00:12,  1.07it/s]

[986] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 99%|█████████▉| 988/1000 [15:50<00:11,  1.08it/s]

[987] Raw: '2
[The Company's operations are subject' → Cleaned: 2

 99%|█████████▉| 989/1000 [15:51<00:10,  1.09it/s]

[988] Raw: '0
[Our Greenhouse Gas Task Force' → Cleaned: 0

 99%|█████████▉| 990/1000 [15:52<00:09,  1.09it/s]

[989] Raw: '1
[The Company is committed to reducing' → Cleaned: 1

 99%|█████████▉| 991/1000 [15:53<00:08,  1.09it/s]

[990] Raw: 'The final answer is' → Cleaned: None

 99%|█████████▉| 992/1000 [15:53<00:07,  1.09it/s]

[991] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

 99%|█████████▉| 993/1000 [15:55<00:06,  1.02it/s]

[992] Raw: '1
[Our company has a strong commitment' → Cleaned: 1

 99%|█████████▉| 994/1000 [15:56<00:06,  1.02s/it]

[993] Raw: '2
[Our goal is to minimize our' → Cleaned: 2

100%|█████████▉| 995/1000 [15:57<00:04,  1.00it/s]

[994] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

100%|█████████▉| 996/1000 [15:58<00:03,  1.02it/s]

[995] Raw: '2
[The Company's environmental policy is' → Cleaned: 2

100%|█████████▉| 997/1000 [15:59<00:02,  1.04it/s]

[996] Raw: '1
[The company has a strong commitment' → Cleaned: 1

100%|█████████▉| 998/1000 [15:59<00:01,  1.06it/s]

[997] Raw: '2
[The Company's environmental policies and' → Cleaned: 2

100%|█████████▉| 999/1000 [16:00<00:00,  1.07it/s]

[998] Raw: '3
[The company is committed to reducing' → Cleaned: None

100%|██████████| 1000/1000 [16:01<00:00,  1.04it/s]

[999] Raw: '2
[The Company's environmental, social' → Cleaned: 2

In [ ]:
evaluate(y_true, y_pred)

Overall Accuracy: 0.447
Accuracy for label 0: 0.468
Accuracy for label 1: 0.703
Accuracy for label 2: 0.668
Accuracy for label 3: 0.000
Macro F1-score: 0.347

Classification Report:
              precision    recall  f1-score   support

           0      0.918     0.468     0.620       190
           1      0.073     0.703     0.132        37
           2      0.609     0.668     0.637       497
           3      0.000     0.000     0.000       276

    accuracy                          0.447      1000
   macro avg      0.400     0.460     0.347      1000
weighted avg      0.480     0.447     0.439      1000


Confusion Matrix:
[[ 89  45  56]
 [  0  26  11]
 [  5 160 332]]

### Fine Tuning

In [ ]:
login(token="...")

In [22]:
output_dir="trained_weigths"
modules = ["q_proj", "v_proj"]
output_dir="/content/drive/My Drive/Thesis/llama-3.1-fine-tuned-model"
hub_model_id = "Adrakou/llama-3.1-fine-tuned"

peft_config = LoraConfig(
    lora_alpha=16,
    lora_dropout=0,
    r=8,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=modules
)

training_arguments = TrainingArguments(
    output_dir=output_dir,
    num_train_epochs=10,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    gradient_checkpointing=True,
    optim="paged_adamw_32bit",
    logging_steps=1,
    learning_rate=2e-4,
    weight_decay=0.001,
    fp16=True,
    bf16=False,
    max_grad_norm=0.3,
    max_steps=-1,
    warmup_ratio=0.03,
    group_by_length=False,
    lr_scheduler_type="cosine",
    eval_strategy="steps",
    eval_steps = 400,
    report_to="none",
    push_to_hub=True,
    hub_model_id=hub_model_id,
    hub_strategy="end",
)

trainer = SFTTrainer(
    model=model,
    args=training_arguments,
    train_dataset=train_data,
    eval_dataset=val_data,
    peft_config=peft_config,
    dataset_text_field="text",
    tokenizer=tokenizer,
    max_seq_length=max_seq_length,
    packing=False,
    dataset_kwargs={
        "add_special_tokens": False,
        "append_concat_token": False,
    }
)

Map:   0%|          | 0/1762 [00:00<?, ? examples/s]

Map:   0%|          | 0/441 [00:00<?, ? examples/s]

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

In [23]:
trainer.train()

TrainOutput(global_step=2200, training_loss=0.5357320745424791, metrics={'train_runtime': 13522.4346, 'train_samples_per_second': 1.303, 'train_steps_per_second': 0.163, 'total_flos': 8.917542947519693e+16, 'train_loss': 0.5357320745424791, 'epoch': 9.95800227014756})

In [24]:
trainer.save_model()
tokenizer.save_pretrained(output_dir)

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...uned-model/tokenizer.json: 100%|##########| 17.2MB / 17.2MB

  ...adapter_model.safetensors:   4%|4         |  558kB / 13.6MB

  ...d-model/training_args.bin:   4%|4         |   219B / 5.37kB

('/content/drive/My Drive/Thesis/llama-3.1-fine-tuned-model/tokenizer_config.json',
 '/content/drive/My Drive/Thesis/llama-3.1-fine-tuned-model/special_tokens_map.json',
 '/content/drive/My Drive/Thesis/llama-3.1-fine-tuned-model/tokenizer.json')

In [25]:
trainer.push_to_hub()
tokenizer.push_to_hub(hub_model_id)

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...d-model/training_args.bin: 100%|##########| 5.37kB / 5.37kB

  ...adapter_model.safetensors: 100%|##########| 13.6MB / 13.6MB

  ...uned-model/tokenizer.json:  92%|#########2| 15.9MB / 17.2MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

README.md: 0.00B [00:00, ?B/s]

Processing Files (0 / 0)      : |          |  0.00B /  0.00B

New Data Upload               : |          |  0.00B /  0.00B

  ...mpwr0y5alq/tokenizer.json: 100%|##########| 17.2MB / 17.2MB

No files have been modified since last commit. Skipping to prevent empty commit.
WARNING:huggingface_hub.hf_api:No files have been modified since last commit. Skipping to prevent empty commit.

CommitInfo(commit_url='https://huggingface.co/Adrakou/llama-3.1-fine-tuned/commit/59ccca19a1a1f965cbb337ae84c4d83b68938bed', commit_message='Upload tokenizer', commit_description='', oid='59ccca19a1a1f965cbb337ae84c4d83b68938bed', pr_url=None, repo_url=RepoUrl('https://huggingface.co/Adrakou/llama-3.1-fine-tuned', endpoint='https://huggingface.co', repo_type='model', repo_id='Adrakou/llama-3.1-fine-tuned'), pr_revision=None, pr_num=None)

In [26]:
y_pred = predict(test, model, tokenizer)
evaluate(y_true, y_pred)

Device set to use cuda:0
  0%|          | 0/1000 [00:00<?, ?it/s]`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.
  0%|          | 1/1000 [00:01<27:27,  1.65s/it]

[0] Raw: '1 Labels: 1 (5) =' → Cleaned: 1

  0%|          | 2/1000 [00:02<24:25,  1.47s/it]

[1] Raw: '2 Labels: 0, 3,' → Cleaned: 2

  0%|          | 3/1000 [00:04<23:26,  1.41s/it]

[2] Raw: '0
Reference: 0
Date:' → Cleaned: 0

  0%|          | 4/1000 [00:05<23:07,  1.39s/it]

[3] Raw: '2
Tags: molybdenum' → Cleaned: 2

  0%|          | 5/1000 [00:07<22:50,  1.38s/it]

[4] Raw: '2
Refer: 2' → Cleaned: 2

  1%|          | 6/1000 [00:08<24:01,  1.45s/it]

[5] Raw: '3
Reference: 0
Has label' → Cleaned: 0

  1%|          | 7/1000 [00:10<25:44,  1.55s/it]

[6] Raw: '2
Reference: 3
Label:' → Cleaned: 2

  1%|          | 8/1000 [00:11<24:38,  1.49s/it]

[7] Raw: '0
Reference: 0
Reference:' → Cleaned: 0

  1%|          | 9/1000 [00:13<24:06,  1.46s/it]

[8] Raw: '3
Reference: 3 for social.' → Cleaned: None

  1%|          | 10/1000 [00:14<23:28,  1.42s/it]You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset

[9] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

  1%|          | 11/1000 [00:15<23:13,  1.41s/it]

[10] Raw: '2
Refer: 0
Volatility' → Cleaned: 2

  1%|          | 12/1000 [00:17<22:57,  1.39s/it]

[11] Raw: '0
Reference: 0
Other text' → Cleaned: 0

  1%|▏         | 13/1000 [00:18<22:48,  1.39s/it]

[12] Raw: '2 Labels: 2
Text:' → Cleaned: 2

  1%|▏         | 14/1000 [00:19<22:42,  1.38s/it]

[13] Raw: '2
Refer:  [The Company also' → Cleaned: 2

  2%|▏         | 15/1000 [00:21<24:36,  1.50s/it]

[14] Raw: '2
Reference: 3
 =' → Cleaned: 2

  2%|▏         | 16/1000 [00:23<25:11,  1.54s/it]

[15] Raw: '3
Reference: 3 = social =' → Cleaned: None

  2%|▏         | 17/1000 [00:24<24:17,  1.48s/it]

[16] Raw: '3
Reference: 3 = 33' → Cleaned: None

  2%|▏         | 18/1000 [00:26<23:43,  1.45s/it]

[17] Raw: '3

[The Company has a significant amount' → Cleaned: None

  2%|▏         | 19/1000 [00:27<23:26,  1.43s/it]

[18] Raw: '2
Tags: non-esg =' → Cleaned: 2

  2%|▏         | 20/1000 [00:28<23:07,  1.42s/it]

[19] Raw: '2
Refer: 3 Class:' → Cleaned: 2

  2%|▏         | 21/1000 [00:30<22:52,  1.40s/it]

[20] Raw: '2
Reference: 3
            [' → Cleaned: 2

  2%|▏         | 22/1000 [00:31<22:48,  1.40s/it]

[21] Raw: '3
Reference: 3 for social.' → Cleaned: None

  2%|▏         | 23/1000 [00:33<23:20,  1.43s/it]

[22] Raw: '3
Reference: 3 = social =' → Cleaned: None

  2%|▏         | 24/1000 [00:34<25:18,  1.56s/it]

[23] Raw: '1

[The Company's Board of Directors' → Cleaned: 1

  2%|▎         | 25/1000 [00:36<24:28,  1.51s/it]

[24] Raw: '2
Refer:  Net cash flows provided' → Cleaned: 2

  3%|▎         | 26/1000 [00:37<23:48,  1.47s/it]

[25] Raw: '2
Reference:  [We have a' → Cleaned: 2

  3%|▎         | 27/1000 [00:39<23:20,  1.44s/it]

[26] Raw: '0
Reference: 0
Link text' → Cleaned: 0

  3%|▎         | 28/1000 [00:40<22:59,  1.42s/it]

[27] Raw: '3
Refer: 3 for social =' → Cleaned: None

  3%|▎         | 29/1000 [00:41<22:37,  1.40s/it]

[28] Raw: '3
Reference: 3 = 9' → Cleaned: None

  3%|▎         | 30/1000 [00:43<22:27,  1.39s/it]

[29] Raw: '3
Reference: 3 = social =' → Cleaned: None

  3%|▎         | 31/1000 [00:44<22:11,  1.37s/it]

[30] Raw: '1 Labels: 1 (1 times)' → Cleaned: 1

  3%|▎         | 32/1000 [00:46<23:43,  1.47s/it]

[31] Raw: '1
Reference: 1
['We' → Cleaned: 1

  3%|▎         | 33/1000 [00:47<24:40,  1.53s/it]

[32] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

  3%|▎         | 34/1000 [00:49<23:48,  1.48s/it]

[33] Raw: '2
[The Company has a significant amount' → Cleaned: 2

  4%|▎         | 35/1000 [00:50<23:13,  1.44s/it]

[34] Raw: '3
Reference: 3 = social =' → Cleaned: None

  4%|▎         | 36/1000 [00:52<22:47,  1.42s/it]

[35] Raw: '3
Refer: 3 for social =' → Cleaned: None

  4%|▎         | 37/1000 [00:53<22:41,  1.41s/it]

[36] Raw: '2
Reference: 3
 =' → Cleaned: 2

  4%|▍         | 38/1000 [00:54<22:22,  1.40s/it]

[37] Raw: '0
Reference: 0
Label:' → Cleaned: 0

  4%|▍         | 39/1000 [00:56<22:05,  1.38s/it]

[38] Raw: '2
[We have a long-standing commitment' → Cleaned: 2

  4%|▍         | 40/1000 [00:57<21:54,  1.37s/it]

[39] Raw: '0
Reference:  [We are working' → Cleaned: 0

  4%|▍         | 41/1000 [00:59<23:50,  1.49s/it]

[40] Raw: '2
Reference: 2 (non-es' → Cleaned: 2

  4%|▍         | 42/1000 [01:00<23:37,  1.48s/it]

[41] Raw: '2
['We are also working with the' → Cleaned: 2

  4%|▍         | 43/1000 [01:02<23:03,  1.45s/it]

[42] Raw: '2
Reference:  [We also have' → Cleaned: 2

  4%|▍         | 44/1000 [01:03<22:33,  1.42s/it]

[43] Raw: '2
Refer: competition in this space to' → Cleaned: 2

  4%|▍         | 45/1000 [01:04<22:13,  1.40s/it]

[44] Raw: '1
[The Company's operating segments are' → Cleaned: 1

  5%|▍         | 46/1000 [01:06<21:56,  1.38s/it]

[45] Raw: '1
Reference: [The Company has a' → Cleaned: 1

  5%|▍         | 47/1000 [01:07<21:47,  1.37s/it]

[46] Raw: '1
Reference: 0
 =' → Cleaned: 1

  5%|▍         | 48/1000 [01:08<21:35,  1.36s/it]

[47] Raw: '3
Reference: 3 = social =' → Cleaned: None

  5%|▍         | 49/1000 [01:10<22:19,  1.41s/it]

[48] Raw: '0
Reference: 0
Label:' → Cleaned: 0

  5%|▌         | 50/1000 [01:12<24:22,  1.54s/it]

[49] Raw: '2 = 0.0333 =' → Cleaned: 2

  5%|▌         | 51/1000 [01:13<23:43,  1.50s/it]

[50] Raw: '3
[The Company has a significant amount' → Cleaned: None

  5%|▌         | 52/1000 [01:14<22:59,  1.46s/it]

[51] Raw: '2
Reference: 3
 =' → Cleaned: 2

  5%|▌         | 53/1000 [01:16<22:42,  1.44s/it]

[52] Raw: '0 Labels: 0
Text:' → Cleaned: 0

  5%|▌         | 54/1000 [01:17<22:15,  1.41s/it]

[53] Raw: '3
Reference: 3 = social =' → Cleaned: None

  6%|▌         | 55/1000 [01:18<21:51,  1.39s/it]

[54] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

  6%|▌         | 56/1000 [01:20<21:38,  1.38s/it]

[55] Raw: '1
Reference: 1
Tag:' → Cleaned: 1

  6%|▌         | 57/1000 [01:21<21:24,  1.36s/it]

[56] Raw: '2

[Liquids production averaged 144' → Cleaned: 2

  6%|▌         | 58/1000 [01:23<23:05,  1.47s/it]

[57] Raw: '3
Reference: 3 = social =' → Cleaned: None

  6%|▌         | 59/1000 [01:25<24:07,  1.54s/it]

[58] Raw: '0
Reference: 0
Other text' → Cleaned: 0

  6%|▌         | 60/1000 [01:26<23:11,  1.48s/it]

[59] Raw: '0 Labels: 0
Text:' → Cleaned: 0

  6%|▌         | 61/1000 [01:27<22:33,  1.44s/it]

[60] Raw: '2
Refer:  [The Company's' → Cleaned: 2

  6%|▌         | 62/1000 [01:29<22:05,  1.41s/it]

[61] Raw: '2

[The Company's consolidated financial statements' → Cleaned: 2

  6%|▋         | 63/1000 [01:30<21:43,  1.39s/it]

[62] Raw: '0
Reference: 0
Other text' → Cleaned: 0

  6%|▋         | 64/1000 [01:31<21:44,  1.39s/it]

[63] Raw: '0
Reference: 0
Text:' → Cleaned: 0

  6%|▋         | 65/1000 [01:33<21:41,  1.39s/it]

[64] Raw: '2 = 0.0000 =' → Cleaned: 2

  7%|▋         | 66/1000 [01:34<21:27,  1.38s/it]

[65] Raw: '3
Reference: 3 for social.' → Cleaned: None

  7%|▋         | 67/1000 [01:36<23:15,  1.50s/it]

[66] Raw: '0
Reference: 0
Other text' → Cleaned: 0

  7%|▋         | 68/1000 [01:37<23:00,  1.48s/it]

[67] Raw: '3
Reference: 3 = social =' → Cleaned: None

  7%|▋         | 69/1000 [01:39<22:19,  1.44s/it]

[68] Raw: '3

[We are working with our suppliers' → Cleaned: None

  7%|▋         | 70/1000 [01:40<21:51,  1.41s/it]

[69] Raw: '3
Reference: 3 = social =' → Cleaned: None

  7%|▋         | 71/1000 [01:41<21:30,  1.39s/it]

[70] Raw: '3
Reference: 3 Sales promotions are' → Cleaned: None

  7%|▋         | 72/1000 [01:43<20:59,  1.36s/it]

[71] Raw: '2 = 0 environmental 1 governance' → Cleaned: 2

  7%|▋         | 73/1000 [01:44<20:57,  1.36s/it]

[72] Raw: '1
Reference:  [We are also' → Cleaned: 1

  7%|▋         | 74/1000 [01:45<20:50,  1.35s/it]

[73] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

  8%|▊         | 75/1000 [01:47<21:18,  1.38s/it]

[74] Raw: '2
Reference: 3
[The' → Cleaned: 2

  8%|▊         | 76/1000 [01:49<23:09,  1.50s/it]

[75] Raw: '2

[The Company's policy is to' → Cleaned: 2

  8%|▊         | 77/1000 [01:50<22:46,  1.48s/it]

[76] Raw: '2
Refer: 2 for non-es' → Cleaned: 2

  8%|▊         | 78/1000 [01:51<22:09,  1.44s/it]

[77] Raw: '0

[We’re also working to reduce' → Cleaned: 0

  8%|▊         | 79/1000 [01:53<21:53,  1.43s/it]

[78] Raw: '3
Reference: 3 for social.' → Cleaned: None

  8%|▊         | 80/1000 [01:54<21:39,  1.41s/it]

[79] Raw: '2
['We are also working with our' → Cleaned: 2

  8%|▊         | 81/1000 [01:55<21:28,  1.40s/it]

[80] Raw: '3
Reference: 3 for social,' → Cleaned: None

  8%|▊         | 82/1000 [01:57<21:18,  1.39s/it]

[81] Raw: '2
[The Company has a significant amount' → Cleaned: 2

  8%|▊         | 83/1000 [01:58<21:16,  1.39s/it]

[82] Raw: '0
Reference: 0
Label:' → Cleaned: 0

  8%|▊         | 84/1000 [02:00<22:43,  1.49s/it]

[83] Raw: '2
[We have a long-standing commitment' → Cleaned: 2

  8%|▊         | 85/1000 [02:02<23:37,  1.55s/it]

[84] Raw: '2

[We are working to reduce the' → Cleaned: 2

  9%|▊         | 86/1000 [02:03<22:52,  1.50s/it]

[85] Raw: '2
[The Company has a non-stat' → Cleaned: 2

  9%|▊         | 87/1000 [02:04<22:15,  1.46s/it]

[86] Raw: '3
Reference: 3 = social =' → Cleaned: None

  9%|▉         | 88/1000 [02:06<21:53,  1.44s/it]

[87] Raw: '3
Reference: 3 for social.' → Cleaned: None

  9%|▉         | 89/1000 [02:07<21:28,  1.41s/it]

[88] Raw: '1 Labels: 1

[The Company' → Cleaned: 1

  9%|▉         | 90/1000 [02:09<21:11,  1.40s/it]

[89] Raw: '2
Reference: 3
 =' → Cleaned: 2

  9%|▉         | 91/1000 [02:10<21:09,  1.40s/it]

[90] Raw: '3
Refer: 3 for social.' → Cleaned: None

  9%|▉         | 92/1000 [02:11<21:09,  1.40s/it]

[91] Raw: '3
Reference: 3 = social =' → Cleaned: None

  9%|▉         | 93/1000 [02:13<22:59,  1.52s/it]

[92] Raw: '3
Reference: 3 = social' → Cleaned: None

  9%|▉         | 94/1000 [02:15<22:32,  1.49s/it]

[93] Raw: '3

[We are working with the World' → Cleaned: None

 10%|▉         | 95/1000 [02:16<21:53,  1.45s/it]

[94] Raw: '0 read more » = 0
Products' → Cleaned: 0

 10%|▉         | 96/1000 [02:17<21:38,  1.44s/it]

[95] Raw: '2
Refer: 2 for non-es' → Cleaned: 2

 10%|▉         | 97/1000 [02:19<21:20,  1.42s/it]

[96] Raw: '3
Refer: Voluntary Principles On The' → Cleaned: None

 10%|▉         | 98/1000 [02:20<21:06,  1.40s/it]

[97] Raw: '0
Reference: 0
Has label' → Cleaned: 0

 10%|▉         | 99/1000 [02:21<20:59,  1.40s/it]

[98] Raw: '3
Reference: 3 = social =' → Cleaned: None

 10%|█         | 100/1000 [02:23<20:56,  1.40s/it]

[99] Raw: '0 Labels: 0 = 1' → Cleaned: 0

 10%|█         | 101/1000 [02:24<21:55,  1.46s/it]

[100] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 10%|█         | 102/1000 [02:26<23:06,  1.54s/it]

[101] Raw: '3
Refer: 3 for social.' → Cleaned: None

 10%|█         | 103/1000 [02:28<22:15,  1.49s/it]

[102] Raw: '3
Reference: 3 = social =' → Cleaned: None

 10%|█         | 104/1000 [02:29<21:43,  1.45s/it]

[103] Raw: '2
Reference: 2
Class:' → Cleaned: 2

 10%|█         | 105/1000 [02:30<21:19,  1.43s/it]

[104] Raw: '2
Reference: 3
Type:' → Cleaned: 2

 11%|█         | 106/1000 [02:32<21:02,  1.41s/it]

[105] Raw: '2
[The Company has a long-standing' → Cleaned: 2

 11%|█         | 107/1000 [02:33<20:51,  1.40s/it]

[106] Raw: '2
Tags: financials Source:' → Cleaned: 2

 11%|█         | 108/1000 [02:34<20:37,  1.39s/it]

[107] Raw: '2 = 0.0333 =' → Cleaned: 2

 11%|█         | 109/1000 [02:36<20:30,  1.38s/it]

[108] Raw: '3
Reference: 3 = 14' → Cleaned: None

 11%|█         | 110/1000 [02:37<22:02,  1.49s/it]

[109] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 11%|█         | 111/1000 [02:39<22:11,  1.50s/it]

[110] Raw: '3
Reference: 3 = 0' → Cleaned: 0

 11%|█         | 112/1000 [02:40<21:34,  1.46s/it]

[111] Raw: '2 = 0.0333 =' → Cleaned: 2

 11%|█▏        | 113/1000 [02:42<21:02,  1.42s/it]

[112] Raw: '1

[We are working to reduce the' → Cleaned: 1

 11%|█▏        | 114/1000 [02:43<20:40,  1.40s/it]

[113] Raw: '3

[We are working to reduce our' → Cleaned: None

 12%|█▏        | 115/1000 [02:44<20:30,  1.39s/it]

[114] Raw: '2
Reference: [We are also working' → Cleaned: 2

 12%|█▏        | 116/1000 [02:46<20:15,  1.38s/it]

[115] Raw: '3
Reference: 3 = 0' → Cleaned: 0

 12%|█▏        | 117/1000 [02:47<20:04,  1.36s/it]

[116] Raw: '3

[We are working with our suppliers' → Cleaned: None

 12%|█▏        | 118/1000 [02:49<20:33,  1.40s/it]

[117] Raw: '3
Refer: 3 for social;' → Cleaned: None

 12%|█▏        | 119/1000 [02:50<22:12,  1.51s/it]

[118] Raw: '2
[We are working to reduce our' → Cleaned: 2

 12%|█▏        | 120/1000 [02:52<21:31,  1.47s/it]

[119] Raw: '3
Refer: 3 for social =' → Cleaned: None

 12%|█▏        | 121/1000 [02:53<21:07,  1.44s/it]

[120] Raw: '2
[The Company’s policy is to' → Cleaned: 2

 12%|█▏        | 122/1000 [02:54<20:42,  1.42s/it]

[121] Raw: '1
['We are also working with our' → Cleaned: 1

 12%|█▏        | 123/1000 [02:56<20:24,  1.40s/it]

[122] Raw: '3
Reference: 3 = social =' → Cleaned: None

 12%|█▏        | 124/1000 [02:57<20:13,  1.38s/it]

[123] Raw: '2
Tags: financials Share: [' → Cleaned: 2

 12%|█▎        | 125/1000 [02:58<19:59,  1.37s/it]

[124] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 13%|█▎        | 126/1000 [03:00<19:58,  1.37s/it]

[125] Raw: '2
Reference: 3
[The' → Cleaned: 2

 13%|█▎        | 127/1000 [03:01<21:00,  1.44s/it]

[126] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 13%|█▎        | 128/1000 [03:03<22:16,  1.53s/it]

[127] Raw: '2
Reference: 3
[The' → Cleaned: 2

 13%|█▎        | 129/1000 [03:05<21:31,  1.48s/it]

[128] Raw: '3
Reference: 3 = social =' → Cleaned: None

 13%|█▎        | 130/1000 [03:06<21:01,  1.45s/it]

[129] Raw: '2
Tags: financials Source:' → Cleaned: 2

 13%|█▎        | 131/1000 [03:07<20:36,  1.42s/it]

[130] Raw: '0
Tags: environmental environmental-protection energy' → Cleaned: 0

 13%|█▎        | 132/1000 [03:09<20:18,  1.40s/it]

[131] Raw: '2
Refer: 3
Touchstone' → Cleaned: 2

 13%|█▎        | 133/1000 [03:10<20:07,  1.39s/it]

[132] Raw: '2
Reference: 3' → Cleaned: 2

 13%|█▎        | 134/1000 [03:11<19:53,  1.38s/it]

[133] Raw: '3

[The Company has a long-standing' → Cleaned: None

 14%|█▎        | 135/1000 [03:13<19:45,  1.37s/it]

[134] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 14%|█▎        | 136/1000 [03:15<21:34,  1.50s/it]

[135] Raw: '2
Tags: finance, non-esg' → Cleaned: 2

 14%|█▎        | 137/1000 [03:16<21:39,  1.51s/it]

[136] Raw: '3
Reference: 3 = social =' → Cleaned: None

 14%|█▍        | 138/1000 [03:17<21:01,  1.46s/it]

[137] Raw: '2
Reference: 2 for non-es' → Cleaned: 2

 14%|█▍        | 139/1000 [03:19<20:34,  1.43s/it]

[138] Raw: '1
[We are working with our suppliers' → Cleaned: 1

 14%|█▍        | 140/1000 [03:20<20:20,  1.42s/it]

[139] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 14%|█▍        | 141/1000 [03:22<20:02,  1.40s/it]

[140] Raw: '2
["We are also working with the' → Cleaned: 2

 14%|█▍        | 142/1000 [03:23<19:50,  1.39s/it]

[141] Raw: '2 = 0.0333 =' → Cleaned: 2

 14%|█▍        | 143/1000 [03:24<19:43,  1.38s/it]

[142] Raw: '2 = 0.0334 =' → Cleaned: 2

 14%|█▍        | 144/1000 [03:26<20:13,  1.42s/it]

[143] Raw: '2
Reference: 3
 =' → Cleaned: 2

 14%|█▍        | 145/1000 [03:28<22:04,  1.55s/it]

[144] Raw: '0
Tags: electricity usage, conservatively' → Cleaned: 0

 15%|█▍        | 146/1000 [03:29<21:15,  1.49s/it]

[145] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 15%|█▍        | 147/1000 [03:30<20:37,  1.45s/it]

[146] Raw: '2
Reference: 3.55' → Cleaned: 2

 15%|█▍        | 148/1000 [03:32<20:08,  1.42s/it]

[147] Raw: '0
Reference: 0
 =' → Cleaned: 0

 15%|█▍        | 149/1000 [03:33<19:47,  1.40s/it]

[148] Raw: '0 read more » [The Company has a' → Cleaned: 0

 15%|█▌        | 150/1000 [03:34<19:40,  1.39s/it]

[149] Raw: '2
["We are also working with our' → Cleaned: 2

 15%|█▌        | 151/1000 [03:36<19:33,  1.38s/it]

[150] Raw: '3
Refer: 3 for social' → Cleaned: None

 15%|█▌        | 152/1000 [03:37<19:24,  1.37s/it]

[151] Raw: '3
Reference: 3 = social =' → Cleaned: None

 15%|█▌        | 153/1000 [03:39<20:43,  1.47s/it]

[152] Raw: '3
Refer: 3 for social.' → Cleaned: None

 15%|█▌        | 154/1000 [03:40<21:29,  1.52s/it]

[153] Raw: '2
Reference: 3
Text:' → Cleaned: 2

 16%|█▌        | 155/1000 [03:42<20:46,  1.48s/it]

[154] Raw: '2 Labels: 0, 3,' → Cleaned: 2

 16%|█▌        | 156/1000 [03:43<20:14,  1.44s/it]

[155] Raw: '2
Reference:  For the twelve months' → Cleaned: 2

 16%|█▌        | 157/1000 [03:45<19:52,  1.41s/it]

[156] Raw: '2
Reference:  [We are also' → Cleaned: 2

 16%|█▌        | 158/1000 [03:46<19:32,  1.39s/it]

[157] Raw: '1

[The Company’s Board of Directors' → Cleaned: 1

 16%|█▌        | 159/1000 [03:47<19:18,  1.38s/it]

[158] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 16%|█▌        | 160/1000 [03:49<19:12,  1.37s/it]

[159] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 16%|█▌        | 161/1000 [03:50<19:04,  1.36s/it]

[160] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 16%|█▌        | 162/1000 [03:52<20:49,  1.49s/it]

[161] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 16%|█▋        | 163/1000 [03:53<20:44,  1.49s/it]

[162] Raw: '3

[The Company has a long-standing' → Cleaned: None

 16%|█▋        | 164/1000 [03:55<20:10,  1.45s/it]

[163] Raw: '2
Reference: 3
[The' → Cleaned: 2

 16%|█▋        | 165/1000 [03:56<19:45,  1.42s/it]

[164] Raw: '3
Labels: 0, 1' → Cleaned: 0

 17%|█▋        | 166/1000 [03:57<19:25,  1.40s/it]

[165] Raw: '2
[The Company has a significant amount' → Cleaned: 2

 17%|█▋        | 167/1000 [03:59<19:13,  1.38s/it]

[166] Raw: '2
Reference:  [The Company's' → Cleaned: 2

 17%|█▋        | 168/1000 [04:00<19:00,  1.37s/it]

[167] Raw: '3
Reference: 3 = social =' → Cleaned: None

 17%|█▋        | 169/1000 [04:01<18:49,  1.36s/it]

[168] Raw: '3
Reference: [We are also seeking' → Cleaned: None

 17%|█▋        | 170/1000 [04:03<19:20,  1.40s/it]

[169] Raw: '2
Reference:  [The Company is' → Cleaned: 2

 17%|█▋        | 171/1000 [04:05<21:10,  1.53s/it]

[170] Raw: '3
Reference: 3 for serious injuries' → Cleaned: None

 17%|█▋        | 172/1000 [04:06<20:29,  1.49s/it]

[171] Raw: '2 Labels: 2
Text:' → Cleaned: 2

 17%|█▋        | 173/1000 [04:07<19:58,  1.45s/it]

[172] Raw: '2 = 0.0334 =' → Cleaned: 2

 17%|█▋        | 174/1000 [04:09<19:30,  1.42s/it]

[173] Raw: '3

[We are working to reduce the' → Cleaned: None

 18%|█▊        | 175/1000 [04:10<19:13,  1.40s/it]

[174] Raw: '2
[We have a long-standing commitment' → Cleaned: 2

 18%|█▊        | 176/1000 [04:11<18:54,  1.38s/it]

[175] Raw: '3

[The Company's net sales for' → Cleaned: None

 18%|█▊        | 177/1000 [04:13<18:46,  1.37s/it]

[176] Raw: '2 Labels: 2
Text:' → Cleaned: 2

 18%|█▊        | 178/1000 [04:14<18:40,  1.36s/it]

[177] Raw: '0 read more > Another 20 percent is' → Cleaned: 0

 18%|█▊        | 179/1000 [04:16<19:49,  1.45s/it]

[178] Raw: '2
Reference: 3' → Cleaned: 2

 18%|█▊        | 180/1000 [04:17<20:43,  1.52s/it]

[179] Raw: '3
Reference: 3 = social' → Cleaned: None

 18%|█▊        | 181/1000 [04:19<20:04,  1.47s/it]

[180] Raw: '2
Reference: 3
Gradient:' → Cleaned: 2

 18%|█▊        | 182/1000 [04:20<19:37,  1.44s/it]

[181] Raw: '2 = 0 = 3 =' → Cleaned: 2

 18%|█▊        | 183/1000 [04:21<19:15,  1.41s/it]

[182] Raw: '2
Reference: 3' → Cleaned: 2

 18%|█▊        | 184/1000 [04:23<18:58,  1.40s/it]

[183] Raw: '2
['We are also working with our' → Cleaned: 2

 18%|█▊        | 185/1000 [04:24<18:53,  1.39s/it]

[184] Raw: '3

[We are working to reduce the' → Cleaned: None

 19%|█▊        | 186/1000 [04:26<18:42,  1.38s/it]

[185] Raw: '1

[We have a long-standing commitment' → Cleaned: 1

 19%|█▊        | 187/1000 [04:27<18:36,  1.37s/it]

[186] Raw: '2
Reference: 3
 =' → Cleaned: 2

 19%|█▉        | 188/1000 [04:29<20:09,  1.49s/it]

[187] Raw: '2
Reference: 3
Other text' → Cleaned: 2

 19%|█▉        | 189/1000 [04:30<20:02,  1.48s/it]

[188] Raw: '3
Reference: 3 for social.' → Cleaned: None

 19%|█▉        | 190/1000 [04:32<19:33,  1.45s/it]

[189] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 19%|█▉        | 191/1000 [04:33<19:09,  1.42s/it]

[190] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 19%|█▉        | 192/1000 [04:34<18:50,  1.40s/it]

[191] Raw: '2
Reference: 3
Other text' → Cleaned: 2

 19%|█▉        | 193/1000 [04:36<18:40,  1.39s/it]

[192] Raw: '3
Reference: 3 for social,' → Cleaned: None

 19%|█▉        | 194/1000 [04:37<18:26,  1.37s/it]

[193] Raw: '3
Reference: 3 = social' → Cleaned: None

 20%|█▉        | 195/1000 [04:38<18:21,  1.37s/it]

[194] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 20%|█▉        | 196/1000 [04:40<18:57,  1.41s/it]

[195] Raw: '3
Reference: 3 = social =' → Cleaned: None

 20%|█▉        | 197/1000 [04:42<20:38,  1.54s/it]

[196] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 20%|█▉        | 198/1000 [04:43<19:56,  1.49s/it]

[197] Raw: '0
Reference: 0
Link text' → Cleaned: 0

 20%|█▉        | 199/1000 [04:44<19:18,  1.45s/it]

[198] Raw: '2
Reference: 3
 =' → Cleaned: 2

 20%|██        | 200/1000 [04:46<18:58,  1.42s/it]

[199] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 20%|██        | 201/1000 [04:47<18:39,  1.40s/it]

[200] Raw: '3
Reference: 3 = social =' → Cleaned: None

 20%|██        | 202/1000 [04:48<18:26,  1.39s/it]

[201] Raw: '3 Users: 0 = 0 Users' → Cleaned: 0

 20%|██        | 203/1000 [04:50<18:17,  1.38s/it]

[202] Raw: '3
Labels: free-text, esg' → Cleaned: None

 20%|██        | 204/1000 [04:51<18:11,  1.37s/it]

[203] Raw: '3
Reference:  Cabot has elected' → Cleaned: None

 20%|██        | 205/1000 [04:53<19:20,  1.46s/it]

[204] Raw: '3
Reference: 3 = social =' → Cleaned: None

 21%|██        | 206/1000 [04:55<20:25,  1.54s/it]

[205] Raw: '3
Refer: 3 for social.' → Cleaned: None

 21%|██        | 207/1000 [04:56<19:44,  1.49s/it]

[206] Raw: '2 = 0.81 per pound of' → Cleaned: 2

 21%|██        | 208/1000 [04:57<19:07,  1.45s/it]

[207] Raw: '1
Reference: 1
Has label' → Cleaned: 1

 21%|██        | 209/1000 [04:59<18:43,  1.42s/it]

[208] Raw: '1 read more
[We are working with' → Cleaned: 1

 21%|██        | 210/1000 [05:00<18:26,  1.40s/it]

[209] Raw: '2 = 0.0333 =' → Cleaned: 2

 21%|██        | 211/1000 [05:01<18:14,  1.39s/it]

[210] Raw: '2
Reference: 3
 =' → Cleaned: 2

 21%|██        | 212/1000 [05:03<18:03,  1.37s/it]

[211] Raw: '3
Reference: 3 for social.' → Cleaned: None

 21%|██▏       | 213/1000 [05:04<17:57,  1.37s/it]

[212] Raw: '3
Refer: 3 for social =' → Cleaned: None

 21%|██▏       | 214/1000 [05:06<19:35,  1.50s/it]

[213] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 22%|██▏       | 215/1000 [05:07<19:28,  1.49s/it]

[214] Raw: '2
Tags: conversion notices, terms,' → Cleaned: 2

 22%|██▏       | 216/1000 [05:09<18:54,  1.45s/it]

[215] Raw: '3
Reference: 3 = social =' → Cleaned: None

 22%|██▏       | 217/1000 [05:10<18:34,  1.42s/it]

[216] Raw: '3
Refer: 3 for social.' → Cleaned: None

 22%|██▏       | 218/1000 [05:11<18:19,  1.41s/it]

[217] Raw: '1 read more
[The Company’s Board' → Cleaned: 1

 22%|██▏       | 219/1000 [05:13<18:13,  1.40s/it]

[218] Raw: '2
['We are also working with the' → Cleaned: 2

 22%|██▏       | 220/1000 [05:14<18:05,  1.39s/it]

[219] Raw: '2
[The Corporation's Board of Directors' → Cleaned: 2

 22%|██▏       | 221/1000 [05:15<17:53,  1.38s/it]

[220] Raw: '2
Reference: 3
Sales to' → Cleaned: 2

 22%|██▏       | 222/1000 [05:17<18:31,  1.43s/it]

[221] Raw: '2
Reference:  Total assets increased by' → Cleaned: 2

 22%|██▏       | 223/1000 [05:19<19:51,  1.53s/it]

[222] Raw: '3
Reference: 3 = social =' → Cleaned: None

 22%|██▏       | 224/1000 [05:20<19:07,  1.48s/it]

[223] Raw: '3
Reference: 3 = social =' → Cleaned: None

 22%|██▎       | 225/1000 [05:21<18:34,  1.44s/it]

[224] Raw: '2
Reference: 0
Other text' → Cleaned: 2

 23%|██▎       | 226/1000 [05:23<18:10,  1.41s/it]

[225] Raw: '3

[We are working to reduce the' → Cleaned: None

 23%|██▎       | 227/1000 [05:24<18:00,  1.40s/it]

[226] Raw: '3
Reference: 3 = social' → Cleaned: None

 23%|██▎       | 228/1000 [05:26<17:51,  1.39s/it]

[227] Raw: '2
Reference: 2 (non-es' → Cleaned: 2

 23%|██▎       | 229/1000 [05:27<17:44,  1.38s/it]

[228] Raw: '3
Reference: 0
Other text' → Cleaned: 0

 23%|██▎       | 230/1000 [05:28<17:33,  1.37s/it]

[229] Raw: '3
Reference: 3 for social.' → Cleaned: None

 23%|██▎       | 231/1000 [05:30<18:47,  1.47s/it]

[230] Raw: '2
Reference: 0
[The' → Cleaned: 2

 23%|██▎       | 232/1000 [05:32<19:20,  1.51s/it]

[231] Raw: '0
Reference: 0
Date:' → Cleaned: 0

 23%|██▎       | 233/1000 [05:33<18:44,  1.47s/it]

[232] Raw: '3
[We are working with our suppliers' → Cleaned: None

 23%|██▎       | 234/1000 [05:34<18:13,  1.43s/it]

[233] Raw: '3
Reference:  For example, in' → Cleaned: None

 24%|██▎       | 235/1000 [05:36<17:58,  1.41s/it]

[234] Raw: '2
Reference: 3
Other text' → Cleaned: 2

 24%|██▎       | 236/1000 [05:37<17:42,  1.39s/it]

[235] Raw: '1
Reference: 1 = governance' → Cleaned: 1

 24%|██▎       | 237/1000 [05:38<17:30,  1.38s/it]

[236] Raw: '3
Reference: 3 = social =' → Cleaned: None

 24%|██▍       | 238/1000 [05:40<17:19,  1.36s/it]

[237] Raw: '1
Reference: 3
Date:' → Cleaned: 1

 24%|██▍       | 239/1000 [05:41<17:11,  1.36s/it]

[238] Raw: '2
["We are also working with our' → Cleaned: 2

 24%|██▍       | 240/1000 [05:43<18:42,  1.48s/it]

[239] Raw: '3
["We are working with the World' → Cleaned: None

 24%|██▍       | 241/1000 [05:44<18:35,  1.47s/it]

[240] Raw: '3
Reference: 3 = social' → Cleaned: None

 24%|██▍       | 242/1000 [05:46<18:13,  1.44s/it]

[241] Raw: '3
Reference:  [The Company is' → Cleaned: None

 24%|██▍       | 243/1000 [05:47<17:55,  1.42s/it]

[242] Raw: '2

[The Company's consolidated financial statements' → Cleaned: 2

 24%|██▍       | 244/1000 [05:48<17:40,  1.40s/it]

[243] Raw: '2
["We have a long-standing commitment' → Cleaned: 2

 24%|██▍       | 245/1000 [05:50<17:27,  1.39s/it]

[244] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 25%|██▍       | 246/1000 [05:51<17:22,  1.38s/it]

[245] Raw: '2 = 0.0005 =' → Cleaned: 2

 25%|██▍       | 247/1000 [05:52<17:09,  1.37s/it]

[246] Raw: '2
Tags: shopping, sale, business' → Cleaned: 2

 25%|██▍       | 248/1000 [05:54<17:43,  1.41s/it]

[247] Raw: '3
Reference: 3 for social.' → Cleaned: None

 25%|██▍       | 249/1000 [05:56<19:08,  1.53s/it]

[248] Raw: '3
Reference: 3 = social' → Cleaned: None

 25%|██▌       | 250/1000 [05:57<18:31,  1.48s/it]

[249] Raw: '3

[We are working with our suppliers' → Cleaned: None

 25%|██▌       | 251/1000 [05:58<18:06,  1.45s/it]

[250] Raw: '2
[The Company's net income for' → Cleaned: 2

 25%|██▌       | 252/1000 [06:00<17:41,  1.42s/it]

[251] Raw: '2
Reference: 3
[We' → Cleaned: 2

 25%|██▌       | 253/1000 [06:01<17:23,  1.40s/it]

[252] Raw: '3
Refer: 3 for social =' → Cleaned: None

 25%|██▌       | 254/1000 [06:02<17:07,  1.38s/it]

[253] Raw: '0
Reference: 0
 =' → Cleaned: 0

 26%|██▌       | 255/1000 [06:04<17:01,  1.37s/it]

[254] Raw: '3
Reference: 3 = 14' → Cleaned: None

 26%|██▌       | 256/1000 [06:05<16:54,  1.36s/it]

[255] Raw: '1

[We are working to reduce the' → Cleaned: 1

 26%|██▌       | 257/1000 [06:07<18:04,  1.46s/it]

[256] Raw: '2
Reference: 3
 =' → Cleaned: 2

 26%|██▌       | 258/1000 [06:09<18:46,  1.52s/it]

[257] Raw: '3
Reference: [Raytheon also supports' → Cleaned: None

 26%|██▌       | 259/1000 [06:10<18:08,  1.47s/it]

[258] Raw: '3
Reference: 3 metric tons of' → Cleaned: None

 26%|██▌       | 260/1000 [06:11<17:44,  1.44s/it]

[259] Raw: '2
['We are also working with our' → Cleaned: 2

 26%|██▌       | 261/1000 [06:13<17:23,  1.41s/it]

[260] Raw: '3
Reference: 3 = social =' → Cleaned: None

 26%|██▌       | 262/1000 [06:14<17:07,  1.39s/it]

[261] Raw: '2
Reference: 3
 =' → Cleaned: 2

 26%|██▋       | 263/1000 [06:15<16:56,  1.38s/it]

[262] Raw: '3
Reference: 3 = 0' → Cleaned: 0

 26%|██▋       | 264/1000 [06:17<16:47,  1.37s/it]

[263] Raw: '3
Reference: 3 = social =' → Cleaned: None

 26%|██▋       | 265/1000 [06:18<16:39,  1.36s/it]

[264] Raw: '3
Reference: 3 = social =' → Cleaned: None

 27%|██▋       | 266/1000 [06:20<17:59,  1.47s/it]

[265] Raw: '1

[We are working with our suppliers' → Cleaned: 1

 27%|██▋       | 267/1000 [06:21<18:02,  1.48s/it]

[266] Raw: '0
Tags: environmental environmental-impact free' → Cleaned: 0

 27%|██▋       | 268/1000 [06:23<17:49,  1.46s/it]

[267] Raw: '2
Reference: 3
[The' → Cleaned: 2

 27%|██▋       | 269/1000 [06:24<17:21,  1.42s/it]

[268] Raw: '1
Reference: 3
Has text' → Cleaned: 1

 27%|██▋       | 270/1000 [06:25<17:07,  1.41s/it]

[269] Raw: '3

[We are working with our suppliers' → Cleaned: None

 27%|██▋       | 271/1000 [06:27<16:55,  1.39s/it]

[270] Raw: '0 read more » [The 2018' → Cleaned: 0

 27%|██▋       | 272/1000 [06:28<16:44,  1.38s/it]

[271] Raw: '2
Reference:  [We are also' → Cleaned: 2

 27%|██▋       | 273/1000 [06:29<16:35,  1.37s/it]

[272] Raw: '3
Reference: 3 = social =' → Cleaned: None

 27%|██▋       | 274/1000 [06:31<17:06,  1.41s/it]

[273] Raw: '0
Reference: 0
Tags:' → Cleaned: 0

 28%|██▊       | 275/1000 [06:33<18:30,  1.53s/it]

[274] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 28%|██▊       | 276/1000 [06:34<17:48,  1.48s/it]

[275] Raw: '3
Reference: 3 = social' → Cleaned: None

 28%|██▊       | 277/1000 [06:35<17:32,  1.46s/it]

[276] Raw: '2 Labels: 2
Text:' → Cleaned: 2

 28%|██▊       | 278/1000 [06:37<17:08,  1.42s/it]

[277] Raw: '3
Reference: 3 = social' → Cleaned: None

 28%|██▊       | 279/1000 [06:38<16:50,  1.40s/it]

[278] Raw: '3
Reference: 3 = social =' → Cleaned: None

 28%|██▊       | 280/1000 [06:39<16:34,  1.38s/it]

[279] Raw: '3

[We are working to reduce the' → Cleaned: None

 28%|██▊       | 281/1000 [06:41<16:26,  1.37s/it]

[280] Raw: '2
Reference: 3
 =' → Cleaned: 2

 28%|██▊       | 282/1000 [06:42<16:18,  1.36s/it]

[281] Raw: '1
Reference: 1
 =' → Cleaned: 1

 28%|██▊       | 283/1000 [06:44<17:29,  1.46s/it]

[282] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 28%|██▊       | 284/1000 [06:46<18:03,  1.51s/it]

[283] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 28%|██▊       | 285/1000 [06:47<17:29,  1.47s/it]

[284] Raw: '3
Reference: 0
Label:' → Cleaned: 0

 29%|██▊       | 286/1000 [06:48<17:02,  1.43s/it]

[285] Raw: '3
Labels: 0, 1' → Cleaned: 0

 29%|██▊       | 287/1000 [06:50<16:42,  1.41s/it]

[286] Raw: '2
Reference:  [The Company's' → Cleaned: 2

 29%|██▉       | 288/1000 [06:51<16:27,  1.39s/it]

[287] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 29%|██▉       | 289/1000 [06:52<16:15,  1.37s/it]

[288] Raw: '1 read more
[We are working with' → Cleaned: 1

 29%|██▉       | 290/1000 [06:54<16:09,  1.37s/it]

[289] Raw: '2
Reference: 3
Other text' → Cleaned: 2

 29%|██▉       | 291/1000 [06:55<16:10,  1.37s/it]

[290] Raw: '2
Refer: 0
Amount =' → Cleaned: 2

 29%|██▉       | 292/1000 [06:57<17:31,  1.48s/it]

[291] Raw: '3
Reference: 3 = social =' → Cleaned: None

 29%|██▉       | 293/1000 [06:58<17:29,  1.48s/it]

[292] Raw: '3

[The Company has a long-standing' → Cleaned: None

 29%|██▉       | 294/1000 [07:00<16:55,  1.44s/it]

[293] Raw: '3
Reference: 3 for social.' → Cleaned: None

 30%|██▉       | 295/1000 [07:01<16:33,  1.41s/it]

[294] Raw: '3

[We are working to reduce our' → Cleaned: None

 30%|██▉       | 296/1000 [07:02<16:08,  1.38s/it]

[295] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 30%|██▉       | 297/1000 [07:04<16:00,  1.37s/it]

[296] Raw: '2
Reference: 3
 =' → Cleaned: 2

 30%|██▉       | 298/1000 [07:05<15:51,  1.36s/it]

[297] Raw: '0 Labels: 0
Text:' → Cleaned: 0

 30%|██▉       | 299/1000 [07:06<15:48,  1.35s/it]

[298] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 30%|███       | 300/1000 [07:08<16:02,  1.38s/it]

[299] Raw: '3
Reference: 3 = 9' → Cleaned: None

 30%|███       | 301/1000 [07:09<17:28,  1.50s/it]

[300] Raw: '2
Refer: 2 for non-es' → Cleaned: 2

 30%|███       | 302/1000 [07:11<16:59,  1.46s/it]

[301] Raw: '2
Reference: 3
[The' → Cleaned: 2

 30%|███       | 303/1000 [07:12<16:32,  1.42s/it]

[302] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 30%|███       | 304/1000 [07:13<16:14,  1.40s/it]

[303] Raw: '2

[We are also working with the' → Cleaned: 2

 30%|███       | 305/1000 [07:15<16:00,  1.38s/it]

[304] Raw: '1
Reference:  [The training was' → Cleaned: 1

 31%|███       | 306/1000 [07:16<15:48,  1.37s/it]

[305] Raw: '2
Reference: 3
[iPad' → Cleaned: 2

 31%|███       | 307/1000 [07:18<15:48,  1.37s/it]

[306] Raw: '3
["We are also working with our' → Cleaned: None

 31%|███       | 308/1000 [07:19<15:45,  1.37s/it]

[307] Raw: '0 read more » 0
[The' → Cleaned: 0

 31%|███       | 309/1000 [07:20<16:26,  1.43s/it]

[308] Raw: '2
Reference: 3
Other text' → Cleaned: 2

 31%|███       | 310/1000 [07:22<17:30,  1.52s/it]

[309] Raw: '2
Reference:  [Desktop net sales' → Cleaned: 2

 31%|███       | 311/1000 [07:24<16:56,  1.48s/it]

[310] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 31%|███       | 312/1000 [07:25<16:36,  1.45s/it]

[311] Raw: '2
Reference: 3
[We' → Cleaned: 2

 31%|███▏      | 313/1000 [07:26<16:08,  1.41s/it]

[312] Raw: '3

[The Company has a long-standing' → Cleaned: None

 31%|███▏      | 314/1000 [07:28<15:52,  1.39s/it]

[313] Raw: '3
Reference: 3 = social =' → Cleaned: None

 32%|███▏      | 315/1000 [07:29<15:41,  1.37s/it]

[314] Raw: '3
Reference: 3 = social' → Cleaned: None

 32%|███▏      | 316/1000 [07:30<15:36,  1.37s/it]

[315] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 32%|███▏      | 317/1000 [07:32<15:32,  1.37s/it]

[316] Raw: '3
Reference: 3 = social =' → Cleaned: None

 32%|███▏      | 318/1000 [07:33<16:44,  1.47s/it]

[317] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 32%|███▏      | 319/1000 [07:35<17:03,  1.50s/it]

[318] Raw: '3

[The Company has a long-standing' → Cleaned: None

 32%|███▏      | 320/1000 [07:36<16:27,  1.45s/it]

[319] Raw: '3

[We are working to reduce our' → Cleaned: None

 32%|███▏      | 321/1000 [07:38<16:01,  1.42s/it]

[320] Raw: '2
Reference: 3
[The' → Cleaned: 2

 32%|███▏      | 322/1000 [07:39<15:46,  1.40s/it]

[321] Raw: '3
Labels: esg, governance,' → Cleaned: None

 32%|███▏      | 323/1000 [07:40<15:32,  1.38s/it]

[322] Raw: '3
Reference:  For example, in' → Cleaned: None

 32%|███▏      | 324/1000 [07:42<15:24,  1.37s/it]

[323] Raw: '2
Reference:  [We have a' → Cleaned: 2

 32%|███▎      | 325/1000 [07:43<15:17,  1.36s/it]

[324] Raw: '1
Reference: 3
 =' → Cleaned: 1

 33%|███▎      | 326/1000 [07:44<15:15,  1.36s/it]

[325] Raw: '2
Reference: 3
Gradient:' → Cleaned: 2

 33%|███▎      | 327/1000 [07:46<16:28,  1.47s/it]

[326] Raw: '2

[The Corporation's Heavy Truck business' → Cleaned: 2

 33%|███▎      | 328/1000 [07:48<16:25,  1.47s/it]

[327] Raw: '2 = 0.0005 =' → Cleaned: 2

 33%|███▎      | 329/1000 [07:49<16:01,  1.43s/it]

[328] Raw: '3
Reference: 3 for social.' → Cleaned: None

 33%|███▎      | 330/1000 [07:50<15:43,  1.41s/it]

[329] Raw: '2 = 0.0500 =' → Cleaned: 2

 33%|███▎      | 331/1000 [07:52<15:26,  1.38s/it]

[330] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 33%|███▎      | 332/1000 [07:53<15:15,  1.37s/it]

[331] Raw: '2
Reference:  [We are also' → Cleaned: 2

 33%|███▎      | 333/1000 [07:54<15:05,  1.36s/it]

[332] Raw: '1
Reference: 1
Label:' → Cleaned: 1

 33%|███▎      | 334/1000 [07:56<15:06,  1.36s/it]

[333] Raw: '3
Reference: 3 = social =' → Cleaned: None

 34%|███▎      | 335/1000 [07:57<15:26,  1.39s/it]

[334] Raw: '2
Reference: 3' → Cleaned: 2

 34%|███▎      | 336/1000 [07:59<16:46,  1.52s/it]

[335] Raw: '2
[We have a long-standing commitment' → Cleaned: 2

 34%|███▎      | 337/1000 [08:00<16:14,  1.47s/it]

[336] Raw: '1
[We are also working with the' → Cleaned: 1

 34%|███▍      | 338/1000 [08:02<15:46,  1.43s/it]

[337] Raw: '2
Tags: component, inflation, returns' → Cleaned: 2

 34%|███▍      | 339/1000 [08:03<15:26,  1.40s/it]

[338] Raw: '3
Reference: 3 = social' → Cleaned: None

 34%|███▍      | 340/1000 [08:04<15:15,  1.39s/it]

[339] Raw: '2
Reference: [The Company's net' → Cleaned: 2

 34%|███▍      | 341/1000 [08:06<15:09,  1.38s/it]

[340] Raw: '0
Reference: 0
Link text' → Cleaned: 0

 34%|███▍      | 342/1000 [08:07<15:04,  1.37s/it]

[341] Raw: '3
Reference: 3 = social =' → Cleaned: None

 34%|███▍      | 343/1000 [08:08<14:57,  1.37s/it]

[342] Raw: '3
Reference: 3 = 36' → Cleaned: None

 34%|███▍      | 344/1000 [08:10<15:45,  1.44s/it]

[343] Raw: '3
Reference: 3 = 27' → Cleaned: None

 34%|███▍      | 345/1000 [08:12<16:29,  1.51s/it]

[344] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 35%|███▍      | 346/1000 [08:13<15:57,  1.46s/it]

[345] Raw: '1 read more
[The Company has a' → Cleaned: 1

 35%|███▍      | 347/1000 [08:14<15:36,  1.43s/it]

[346] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 35%|███▍      | 348/1000 [08:16<15:15,  1.40s/it]

[347] Raw: '3
Reference: 3 = 33' → Cleaned: None

 35%|███▍      | 349/1000 [08:17<15:03,  1.39s/it]

[348] Raw: '3
Reference: 3 = 33' → Cleaned: None

 35%|███▌      | 350/1000 [08:18<14:57,  1.38s/it]

[349] Raw: '3

[We are also working with the' → Cleaned: None

 35%|███▌      | 351/1000 [08:20<14:46,  1.37s/it]

[350] Raw: '3
Reference: 3 = social =' → Cleaned: None

 35%|███▌      | 352/1000 [08:21<14:40,  1.36s/it]

[351] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 35%|███▌      | 353/1000 [08:23<15:54,  1.48s/it]

[352] Raw: '3
Reference: 3 = social =' → Cleaned: None

 35%|███▌      | 354/1000 [08:24<16:06,  1.50s/it]

[353] Raw: '3
Reference: 3 for social.' → Cleaned: None

 36%|███▌      | 355/1000 [08:26<15:44,  1.46s/it]

[354] Raw: '0
Reference: 0
Tags:' → Cleaned: 0

 36%|███▌      | 356/1000 [08:27<15:19,  1.43s/it]

[355] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 36%|███▌      | 357/1000 [08:28<15:01,  1.40s/it]

[356] Raw: '0
Reference: 0
[We' → Cleaned: 0

 36%|███▌      | 358/1000 [08:30<14:51,  1.39s/it]

[357] Raw: '1
[The Company’s Board of Directors' → Cleaned: 1

 36%|███▌      | 359/1000 [08:31<14:44,  1.38s/it]

[358] Raw: '3

[We are working to reduce our' → Cleaned: None

 36%|███▌      | 360/1000 [08:33<14:41,  1.38s/it]

[359] Raw: '2
['We are also working with our' → Cleaned: 2

 36%|███▌      | 361/1000 [08:34<14:57,  1.40s/it]

[360] Raw: '2
Reference: 3
 =' → Cleaned: 2

 36%|███▌      | 362/1000 [08:36<16:12,  1.52s/it]

[361] Raw: '1
[We are working with our suppliers' → Cleaned: 1

 36%|███▋      | 363/1000 [08:37<15:37,  1.47s/it]

[362] Raw: '2
Reference: 3
Type:' → Cleaned: 2

 36%|███▋      | 364/1000 [08:38<15:11,  1.43s/it]

[363] Raw: '3
Reference: 3 = 33' → Cleaned: None

 36%|███▋      | 365/1000 [08:40<14:52,  1.41s/it]

[364] Raw: '3
Reference: 3 = social =' → Cleaned: None

 37%|███▋      | 366/1000 [08:41<14:43,  1.39s/it]

[365] Raw: '2
Refer: 10-K  Filed' → Cleaned: 2

 37%|███▋      | 367/1000 [08:43<14:32,  1.38s/it]

[366] Raw: '3
Reference: 3 = social =' → Cleaned: None

 37%|███▋      | 368/1000 [08:44<14:24,  1.37s/it]

[367] Raw: '3
Reference: 3 = social =' → Cleaned: None

 37%|███▋      | 369/1000 [08:45<14:21,  1.37s/it]

[368] Raw: '2
Refer: Return ONLY the numerical label' → Cleaned: 2

 37%|███▋      | 370/1000 [08:47<15:07,  1.44s/it]

[369] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 37%|███▋      | 371/1000 [08:49<15:56,  1.52s/it]

[370] Raw: '3
Reference: 3 = social =' → Cleaned: None

 37%|███▋      | 372/1000 [08:50<15:21,  1.47s/it]

[371] Raw: '2

[We are also working with our' → Cleaned: 2

 37%|███▋      | 373/1000 [08:51<14:56,  1.43s/it]

[372] Raw: '2
Reference: 3
Other text' → Cleaned: 2

 37%|███▋      | 374/1000 [08:53<14:37,  1.40s/it]

[373] Raw: '2
Reference:  WPL's non' → Cleaned: 2

 38%|███▊      | 375/1000 [08:54<14:28,  1.39s/it]

[374] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 38%|███▊      | 376/1000 [08:55<14:29,  1.39s/it]

[375] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 38%|███▊      | 377/1000 [08:57<14:20,  1.38s/it]

[376] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 38%|███▊      | 378/1000 [08:58<14:14,  1.37s/it]

[377] Raw: '3
Reference: 3 for social.' → Cleaned: None

 38%|███▊      | 379/1000 [09:00<15:23,  1.49s/it]

[378] Raw: '2 Labels: 2
Text:' → Cleaned: 2

 38%|███▊      | 380/1000 [09:01<15:27,  1.50s/it]

[379] Raw: '2
Reference: 3' → Cleaned: 2

 38%|███▊      | 381/1000 [09:03<14:59,  1.45s/it]

[380] Raw: '2 = 0.0005 =' → Cleaned: 2

 38%|███▊      | 382/1000 [09:04<14:39,  1.42s/it]

[381] Raw: '3
Reference: 3 for social.' → Cleaned: None

 38%|███▊      | 383/1000 [09:05<14:27,  1.41s/it]

[382] Raw: '2
Reference: 3
Tag:' → Cleaned: 2

 38%|███▊      | 384/1000 [09:07<14:15,  1.39s/it]

[383] Raw: '2

[The Company has a significant amount' → Cleaned: 2

 38%|███▊      | 385/1000 [09:08<14:05,  1.38s/it]

[384] Raw: '2
Reference:  [We are also' → Cleaned: 2

 39%|███▊      | 386/1000 [09:09<13:56,  1.36s/it]

[385] Raw: '2
Reference:  Total operating costs increased' → Cleaned: 2

 39%|███▊      | 387/1000 [09:11<14:09,  1.39s/it]

[386] Raw: '3

[We have a long-standing commitment' → Cleaned: None

 39%|███▉      | 388/1000 [09:13<15:21,  1.51s/it]

[387] Raw: '3
Reference: 3 = social =' → Cleaned: None

 39%|███▉      | 389/1000 [09:14<14:52,  1.46s/it]

[388] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 39%|███▉      | 390/1000 [09:15<14:31,  1.43s/it]

[389] Raw: '2
['We are also working with our' → Cleaned: 2

 39%|███▉      | 391/1000 [09:17<14:18,  1.41s/it]

[390] Raw: '2
[The Company’s Board of Directors' → Cleaned: 2

 39%|███▉      | 392/1000 [09:18<14:07,  1.39s/it]

[391] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 39%|███▉      | 393/1000 [09:19<13:59,  1.38s/it]

[392] Raw: '1
Reference: 1 (govern' → Cleaned: 1

 39%|███▉      | 394/1000 [09:21<13:51,  1.37s/it]

[393] Raw: '3
Reference: 3 = 1' → Cleaned: 1

 40%|███▉      | 395/1000 [09:22<13:45,  1.36s/it]

[394] Raw: '2

[The Corporation's Board of Directors' → Cleaned: 2

 40%|███▉      | 396/1000 [09:24<14:25,  1.43s/it]

[395] Raw: '3
Reference: 3 for social.' → Cleaned: None

 40%|███▉      | 397/1000 [09:25<15:22,  1.53s/it]

[396] Raw: '3

[We have a long-standing commitment' → Cleaned: None

 40%|███▉      | 398/1000 [09:27<14:47,  1.47s/it]

[397] Raw: '3
Reference: 3 = 3' → Cleaned: None

 40%|███▉      | 399/1000 [09:28<14:23,  1.44s/it]

[398] Raw: '3
Refer: 3 for social,' → Cleaned: None

 40%|████      | 400/1000 [09:30<14:05,  1.41s/it]

[399] Raw: '2
Reference: 3
 =' → Cleaned: 2

 40%|████      | 401/1000 [09:31<13:53,  1.39s/it]

[400] Raw: '2
['We are also working with our' → Cleaned: 2

 40%|████      | 402/1000 [09:32<13:42,  1.37s/it]

[401] Raw: '1
Reference: [The Board, its' → Cleaned: 1

 40%|████      | 403/1000 [09:34<13:35,  1.37s/it]

[402] Raw: '3
Reference: 3 = 14' → Cleaned: None

 40%|████      | 404/1000 [09:35<13:33,  1.36s/it]

[403] Raw: '3
Reference: 3 = social =' → Cleaned: None

 40%|████      | 405/1000 [09:37<14:46,  1.49s/it]

[404] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 41%|████      | 406/1000 [09:38<14:52,  1.50s/it]

[405] Raw: '2
Reference: 2 (for non' → Cleaned: 2

 41%|████      | 407/1000 [09:40<14:27,  1.46s/it]

[406] Raw: '2
Reference: [The Revolving Credit' → Cleaned: 2

 41%|████      | 408/1000 [09:41<14:11,  1.44s/it]

[407] Raw: '2 = 0.0500 =' → Cleaned: 2

 41%|████      | 409/1000 [09:42<13:52,  1.41s/it]

[408] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 41%|████      | 410/1000 [09:44<13:38,  1.39s/it]

[409] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 41%|████      | 411/1000 [09:45<13:29,  1.37s/it]

[410] Raw: '1

[We are working to reduce the' → Cleaned: 1

 41%|████      | 412/1000 [09:46<13:22,  1.36s/it]

[411] Raw: '2
Reference:  [The Company's' → Cleaned: 2

 41%|████▏     | 413/1000 [09:48<13:32,  1.38s/it]

[412] Raw: '2
Reference: [We are also working' → Cleaned: 2

 41%|████▏     | 414/1000 [09:50<14:39,  1.50s/it]

[413] Raw: '3
Reference: 3 = $0' → Cleaned: 0

 42%|████▏     | 415/1000 [09:51<14:17,  1.47s/it]

[414] Raw: '3
Labels: 0, 1' → Cleaned: 0

 42%|████▏     | 416/1000 [09:52<13:54,  1.43s/it]

[415] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 42%|████▏     | 417/1000 [09:54<13:40,  1.41s/it]

[416] Raw: '1
[We have a policy requiring employees' → Cleaned: 1

 42%|████▏     | 418/1000 [09:55<13:34,  1.40s/it]

[417] Raw: '2 = 0.0333 =' → Cleaned: 2

 42%|████▏     | 419/1000 [09:56<13:25,  1.39s/it]

[418] Raw: '3
Reference: 3 = social =' → Cleaned: None

 42%|████▏     | 420/1000 [09:58<13:17,  1.38s/it]

[419] Raw: '3
Reference: 3 for social.' → Cleaned: None

 42%|████▏     | 421/1000 [09:59<13:10,  1.37s/it]

[420] Raw: '3

[We are also working with our' → Cleaned: None

 42%|████▏     | 422/1000 [10:01<13:45,  1.43s/it]

[421] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 42%|████▏     | 423/1000 [10:02<14:39,  1.52s/it]

[422] Raw: '2
Reference: 3
 =' → Cleaned: 2

 42%|████▏     | 424/1000 [10:04<14:05,  1.47s/it]

[423] Raw: '3
Reference: 3 = social;' → Cleaned: None

 42%|████▎     | 425/1000 [10:05<13:40,  1.43s/it]

[424] Raw: '0 Labels: 0 [The 201' → Cleaned: 0

 43%|████▎     | 426/1000 [10:06<13:20,  1.40s/it]

[425] Raw: '0
Reference: 0
Has label' → Cleaned: 0

 43%|████▎     | 427/1000 [10:08<13:14,  1.39s/it]

[426] Raw: '3
Refer: [We are also working' → Cleaned: None

 43%|████▎     | 428/1000 [10:09<13:06,  1.38s/it]

[427] Raw: '0
Reference: 0
Date:' → Cleaned: 0

 43%|████▎     | 429/1000 [10:10<13:02,  1.37s/it]

[428] Raw: '3
Reference: 3 = social =' → Cleaned: None

 43%|████▎     | 430/1000 [10:12<12:57,  1.36s/it]

[429] Raw: '3
Reference: 3 for social.' → Cleaned: None

 43%|████▎     | 431/1000 [10:13<13:54,  1.47s/it]

[430] Raw: '3
Reference: 3 = 33' → Cleaned: None

 43%|████▎     | 432/1000 [10:15<14:15,  1.51s/it]

[431] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 43%|████▎     | 433/1000 [10:16<13:44,  1.45s/it]

[432] Raw: '2
Reference: 3
[We' → Cleaned: 2

 43%|████▎     | 434/1000 [10:18<13:26,  1.42s/it]

[433] Raw: '2
['We are also working with our' → Cleaned: 2

 44%|████▎     | 435/1000 [10:19<13:10,  1.40s/it]

[434] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 44%|████▎     | 436/1000 [10:20<13:01,  1.38s/it]

[435] Raw: '3
Reference: 3 = social,' → Cleaned: None

 44%|████▎     | 437/1000 [10:22<12:54,  1.38s/it]

[436] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 44%|████▍     | 438/1000 [10:23<12:46,  1.36s/it]

[437] Raw: '3
Reference: 3 = social =' → Cleaned: None

 44%|████▍     | 439/1000 [10:25<12:41,  1.36s/it]

[438] Raw: '3
Reference: 3 = social =' → Cleaned: None

 44%|████▍     | 440/1000 [10:26<13:49,  1.48s/it]

[439] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 44%|████▍     | 441/1000 [10:28<13:43,  1.47s/it]

[440] Raw: '3
Reference: 3 = social =' → Cleaned: None

 44%|████▍     | 442/1000 [10:29<13:19,  1.43s/it]

[441] Raw: '3
Reference: 3 = 27' → Cleaned: None

 44%|████▍     | 443/1000 [10:30<13:02,  1.40s/it]

[442] Raw: '2

[We are working to reduce our' → Cleaned: 2

 44%|████▍     | 444/1000 [10:32<12:50,  1.39s/it]

[443] Raw: '3
Reference: 3 = social =' → Cleaned: None

 44%|████▍     | 445/1000 [10:33<12:45,  1.38s/it]

[444] Raw: '0 Labels: 0
Text:' → Cleaned: 0

 45%|████▍     | 446/1000 [10:34<12:45,  1.38s/it]

[445] Raw: '2
Refer: 2 for non-es' → Cleaned: 2

 45%|████▍     | 447/1000 [10:36<12:38,  1.37s/it]

[446] Raw: '3
Reference: 3 = social =' → Cleaned: None

 45%|████▍     | 448/1000 [10:37<12:59,  1.41s/it]

[447] Raw: '2
Reference: [The Companys' → Cleaned: 2

 45%|████▍     | 449/1000 [10:39<14:04,  1.53s/it]

[448] Raw: '3
Reference: 3 = social' → Cleaned: None

 45%|████▌     | 450/1000 [10:41<13:34,  1.48s/it]

[449] Raw: '2
Refer: 3K18-' → Cleaned: 2

 45%|████▌     | 451/1000 [10:42<13:09,  1.44s/it]

[450] Raw: '2
Reference:  [We have a' → Cleaned: 2

 45%|████▌     | 452/1000 [10:43<12:54,  1.41s/it]

[451] Raw: '2
Reference:  [The Company’s' → Cleaned: 2

 45%|████▌     | 453/1000 [10:45<12:41,  1.39s/it]

[452] Raw: '3
Reference: 3 = social =' → Cleaned: None

 45%|████▌     | 454/1000 [10:46<12:33,  1.38s/it]

[453] Raw: '2

[We are working to reduce the' → Cleaned: 2

 46%|████▌     | 455/1000 [10:47<12:28,  1.37s/it]

[454] Raw: '3
Reference: 3 = social =' → Cleaned: None

 46%|████▌     | 456/1000 [10:49<12:25,  1.37s/it]

[455] Raw: '1
[The Company has a policy of' → Cleaned: 1

 46%|████▌     | 457/1000 [10:50<13:11,  1.46s/it]

[456] Raw: '3
Reference: 3 = social' → Cleaned: None

 46%|████▌     | 458/1000 [10:52<13:42,  1.52s/it]

[457] Raw: '' → Cleaned: None

 46%|████▌     | 459/1000 [10:53<13:12,  1.46s/it]

[458] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 46%|████▌     | 460/1000 [10:55<12:53,  1.43s/it]

[459] Raw: '3

[We are working to reduce our' → Cleaned: None

 46%|████▌     | 461/1000 [10:56<12:46,  1.42s/it]

[460] Raw: '3
Reference: 3 = social =' → Cleaned: None

 46%|████▌     | 462/1000 [10:57<12:34,  1.40s/it]

[461] Raw: '3
Reference: 3 = social =' → Cleaned: None

 46%|████▋     | 463/1000 [10:59<12:25,  1.39s/it]

[462] Raw: '3
Reference: 3 = social =' → Cleaned: None

 46%|████▋     | 464/1000 [11:00<12:17,  1.38s/it]

[463] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 46%|████▋     | 465/1000 [11:01<12:15,  1.37s/it]

[464] Raw: '0
Reference: 0
Link text' → Cleaned: 0

 47%|████▋     | 466/1000 [11:03<13:12,  1.48s/it]

[465] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 47%|████▋     | 467/1000 [11:05<13:10,  1.48s/it]

[466] Raw: '1
Reference: 1
['We' → Cleaned: 1

 47%|████▋     | 468/1000 [11:06<12:48,  1.44s/it]

[467] Raw: '1

[We are working with our suppliers' → Cleaned: 1

 47%|████▋     | 469/1000 [11:07<12:30,  1.41s/it]

[468] Raw: '2
Refer: Net cash used in financing' → Cleaned: 2

 47%|████▋     | 470/1000 [11:09<12:20,  1.40s/it]

[469] Raw: '2
Reference: 3
 =' → Cleaned: 2

 47%|████▋     | 471/1000 [11:10<12:09,  1.38s/it]

[470] Raw: '2
Refer: 3C11-' → Cleaned: 2

 47%|████▋     | 472/1000 [11:11<12:02,  1.37s/it]

[471] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 47%|████▋     | 473/1000 [11:13<12:00,  1.37s/it]

[472] Raw: '0
Refer: 0' → Cleaned: 0

 47%|████▋     | 474/1000 [11:14<12:19,  1.41s/it]

[473] Raw: '2
Tags: finance cash debt sale agreement' → Cleaned: 2

 48%|████▊     | 475/1000 [11:16<13:19,  1.52s/it]

[474] Raw: '0 read more » [The 2009' → Cleaned: 0

 48%|████▊     | 476/1000 [11:17<12:51,  1.47s/it]

[475] Raw: '2
Tags: trading-platform, fixed-income' → Cleaned: 2

 48%|████▊     | 477/1000 [11:19<12:29,  1.43s/it]

[476] Raw: '2
Reference: 3
Field services' → Cleaned: 2

 48%|████▊     | 478/1000 [11:20<12:14,  1.41s/it]

[477] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 48%|████▊     | 479/1000 [11:21<12:06,  1.39s/it]

[478] Raw: '2
Reference: 3
 =' → Cleaned: 2

 48%|████▊     | 480/1000 [11:23<11:57,  1.38s/it]

[479] Raw: '1
['We are also working with the' → Cleaned: 1

 48%|████▊     | 481/1000 [11:24<11:51,  1.37s/it]

[480] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 48%|████▊     | 482/1000 [11:26<11:43,  1.36s/it]

[481] Raw: '3
Reference: 3 = social =' → Cleaned: None

 48%|████▊     | 483/1000 [11:27<12:23,  1.44s/it]

[482] Raw: '2
Reference: 3' → Cleaned: 2

 48%|████▊     | 484/1000 [11:29<13:07,  1.53s/it]

[483] Raw: '2
Reference:  [The Company's' → Cleaned: 2

 48%|████▊     | 485/1000 [11:30<12:30,  1.46s/it]

[484] Raw: '2
Other  = 2
[' → Cleaned: 2

 49%|████▊     | 486/1000 [11:32<12:12,  1.42s/it]

[485] Raw: '3
Reference: 3 = social' → Cleaned: None

 49%|████▊     | 487/1000 [11:33<11:56,  1.40s/it]

[486] Raw: '3
Reference: 3 = 14' → Cleaned: None

 49%|████▉     | 488/1000 [11:34<11:48,  1.38s/it]

[487] Raw: '2
Reference: 3
 =' → Cleaned: 2

 49%|████▉     | 489/1000 [11:36<11:41,  1.37s/it]

[488] Raw: '3
Reference: 3 = 14' → Cleaned: None

 49%|████▉     | 490/1000 [11:37<11:34,  1.36s/it]

[489] Raw: '1

[We are working to reduce the' → Cleaned: 1

 49%|████▉     | 491/1000 [11:38<11:32,  1.36s/it]

[490] Raw: '2
[The Company's net loss for' → Cleaned: 2

 49%|████▉     | 492/1000 [11:40<12:32,  1.48s/it]

[491] Raw: '2 = 0.0005 =' → Cleaned: 2

 49%|████▉     | 493/1000 [11:42<12:46,  1.51s/it]

[492] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 49%|████▉     | 494/1000 [11:43<12:22,  1.47s/it]

[493] Raw: '0
Reference: 0
[We' → Cleaned: 0

 50%|████▉     | 495/1000 [11:44<12:03,  1.43s/it]

[494] Raw: '2
Reference: 3
 =' → Cleaned: 2

 50%|████▉     | 496/1000 [11:46<11:48,  1.41s/it]

[495] Raw: '3

[We are working with the World' → Cleaned: None

 50%|████▉     | 497/1000 [11:47<11:39,  1.39s/it]

[496] Raw: '0
Reference: 0
Link text' → Cleaned: 0

 50%|████▉     | 498/1000 [11:48<11:30,  1.38s/it]

[497] Raw: '1
[The Company’s Board of Directors' → Cleaned: 1

 50%|████▉     | 499/1000 [11:50<11:23,  1.37s/it]

[498] Raw: '2
Reference: 3
 =' → Cleaned: 2

 50%|█████     | 500/1000 [11:51<11:30,  1.38s/it]

[499] Raw: '0
[The Company has a long-standing' → Cleaned: 0

 50%|█████     | 501/1000 [11:53<12:30,  1.50s/it]

[500] Raw: '2
Reference: 3
Label:' → Cleaned: 2

 50%|█████     | 502/1000 [11:54<12:07,  1.46s/it]

[501] Raw: '2 Labels: 0, 3,' → Cleaned: 2

 50%|█████     | 503/1000 [11:56<11:48,  1.42s/it]

[502] Raw: '1
[We have a long-standing commitment' → Cleaned: 1

 50%|█████     | 504/1000 [11:57<11:38,  1.41s/it]

[503] Raw: '2
Refer:  Ford Credit projects full' → Cleaned: 2

 50%|█████     | 505/1000 [11:58<11:28,  1.39s/it]

[504] Raw: '3
Reference: 3 = social =' → Cleaned: None

 51%|█████     | 506/1000 [12:00<11:20,  1.38s/it]

[505] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 51%|█████     | 507/1000 [12:01<11:16,  1.37s/it]

[506] Raw: '2 = 0.0005 =' → Cleaned: 2

 51%|█████     | 508/1000 [12:02<11:16,  1.38s/it]

[507] Raw: '2
["We are also working with the' → Cleaned: 2

 51%|█████     | 509/1000 [12:04<11:50,  1.45s/it]

[508] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 51%|█████     | 510/1000 [12:06<12:35,  1.54s/it]

[509] Raw: '3
Reference:  Global industry vehicle sales' → Cleaned: None

 51%|█████     | 511/1000 [12:07<12:06,  1.49s/it]

[510] Raw: '2
Reference: 3
[The' → Cleaned: 2

 51%|█████     | 512/1000 [12:08<11:44,  1.44s/it]

[511] Raw: '2
Reference: 3' → Cleaned: 2

 51%|█████▏    | 513/1000 [12:10<11:28,  1.41s/it]

[512] Raw: '3
Reference: 3 = social =' → Cleaned: None

 51%|█████▏    | 514/1000 [12:11<11:15,  1.39s/it]

[513] Raw: '3
Tags: materials-science | student' → Cleaned: None

 52%|█████▏    | 515/1000 [12:13<11:09,  1.38s/it]

[514] Raw: '3
Reference:  Fines paid in' → Cleaned: None

 52%|█████▏    | 516/1000 [12:14<11:02,  1.37s/it]

[515] Raw: '1
[The Company’s Board of Directors' → Cleaned: 1

 52%|█████▏    | 517/1000 [12:15<10:55,  1.36s/it]

[516] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 52%|█████▏    | 518/1000 [12:17<11:44,  1.46s/it]

[517] Raw: '3
Reference: 3 = social =' → Cleaned: None

 52%|█████▏    | 519/1000 [12:18<11:58,  1.49s/it]

[518] Raw: '3

[The Company has a significant amount' → Cleaned: None

 52%|█████▏    | 520/1000 [12:20<11:30,  1.44s/it]

[519] Raw: '1 Labels: 1, 3 Stats' → Cleaned: 1

 52%|█████▏    | 521/1000 [12:21<11:15,  1.41s/it]

[520] Raw: '1
Reference:  [We are also' → Cleaned: 1

 52%|█████▏    | 522/1000 [12:22<10:59,  1.38s/it]

[521] Raw: '3
Reference: 3 = social =' → Cleaned: None

 52%|█████▏    | 523/1000 [12:24<10:54,  1.37s/it]

[522] Raw: '1

[We have a long-standing commitment' → Cleaned: 1

 52%|█████▏    | 524/1000 [12:25<10:46,  1.36s/it]

[523] Raw: '2
Reference: 0' → Cleaned: 2

 52%|█████▎    | 525/1000 [12:27<10:57,  1.38s/it]

[524] Raw: '2

[We are working to reduce our' → Cleaned: 2

 53%|█████▎    | 526/1000 [12:28<10:49,  1.37s/it]

[525] Raw: '1
Reference: 1 = governance' → Cleaned: 1

 53%|█████▎    | 527/1000 [12:30<11:42,  1.48s/it]

[526] Raw: '3
Reference: 3 = social =' → Cleaned: None

 53%|█████▎    | 528/1000 [12:31<11:37,  1.48s/it]

[527] Raw: '3
Refer: 3 for social' → Cleaned: None

 53%|█████▎    | 529/1000 [12:32<11:18,  1.44s/it]

[528] Raw: '2
Refer: F2018 on p' → Cleaned: 2

 53%|█████▎    | 530/1000 [12:34<11:04,  1.41s/it]

[529] Raw: '2
Reference: 12.0%' → Cleaned: 2

 53%|█████▎    | 531/1000 [12:35<10:53,  1.39s/it]

[530] Raw: '3
Reference: 3 = social =' → Cleaned: None

 53%|█████▎    | 532/1000 [12:36<10:45,  1.38s/it]

[531] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 53%|█████▎    | 533/1000 [12:38<10:39,  1.37s/it]

[532] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 53%|█████▎    | 534/1000 [12:39<10:34,  1.36s/it]

[533] Raw: '2
Reference: 3.3' → Cleaned: 2

 54%|█████▎    | 535/1000 [12:41<10:49,  1.40s/it]

[534] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 54%|█████▎    | 536/1000 [12:42<11:44,  1.52s/it]

[535] Raw: '2
Reference:  Total cash costs per' → Cleaned: 2

 54%|█████▎    | 537/1000 [12:44<11:18,  1.47s/it]

[536] Raw: '2

[We are working with our suppliers' → Cleaned: 2

 54%|█████▍    | 538/1000 [12:45<11:01,  1.43s/it]

[537] Raw: '2
Reference: 3
Tag:' → Cleaned: 2

 54%|█████▍    | 539/1000 [12:47<10:51,  1.41s/it]

[538] Raw: '3
Reference: 3 = social' → Cleaned: None

 54%|█████▍    | 540/1000 [12:48<10:41,  1.39s/it]

[539] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 54%|█████▍    | 541/1000 [12:49<10:31,  1.38s/it]

[540] Raw: '2
Tags: sales, iPods,' → Cleaned: 2

 54%|█████▍    | 542/1000 [12:51<10:23,  1.36s/it]

[541] Raw: '1

[We are working to reduce our' → Cleaned: 1

 54%|█████▍    | 543/1000 [12:52<10:21,  1.36s/it]

[542] Raw: '0
Reference: 0
Link text' → Cleaned: 0

 54%|█████▍    | 544/1000 [12:54<10:55,  1.44s/it]

[543] Raw: '1
Reference: 1
['We' → Cleaned: 1

 55%|█████▍    | 545/1000 [12:55<11:31,  1.52s/it]

[544] Raw: '3
Labels: 0, 1' → Cleaned: 0

 55%|█████▍    | 546/1000 [12:57<11:09,  1.48s/it]

[545] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 55%|█████▍    | 547/1000 [12:58<10:53,  1.44s/it]

[546] Raw: '2
Reference: 40 Table of Contents' → Cleaned: 2

 55%|█████▍    | 548/1000 [12:59<10:38,  1.41s/it]

[547] Raw: '2
[The Company's operating segments are' → Cleaned: 2

 55%|█████▍    | 549/1000 [13:01<10:27,  1.39s/it]

[548] Raw: '2
Reference:  [The Company's' → Cleaned: 2

 55%|█████▌    | 550/1000 [13:02<10:19,  1.38s/it]

[549] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 55%|█████▌    | 551/1000 [13:03<10:16,  1.37s/it]

[550] Raw: '3
Reference: 3 = social =' → Cleaned: None

 55%|█████▌    | 552/1000 [13:05<10:13,  1.37s/it]

[551] Raw: '2
Reference: 3
Other revenues' → Cleaned: 2

 55%|█████▌    | 553/1000 [13:06<11:06,  1.49s/it]

[552] Raw: '2
Reference: [We have a long' → Cleaned: 2

 55%|█████▌    | 554/1000 [13:08<11:10,  1.50s/it]

[553] Raw: '3
['We are also working with the' → Cleaned: None

 56%|█████▌    | 555/1000 [13:09<10:49,  1.46s/it]

[554] Raw: '2
Reference: [We have a long' → Cleaned: 2

 56%|█████▌    | 556/1000 [13:11<10:33,  1.43s/it]

[555] Raw: '3
Labels: 0 (environmental' → Cleaned: 0

 56%|█████▌    | 557/1000 [13:12<10:19,  1.40s/it]

[556] Raw: '2

[The Company has a significant amount' → Cleaned: 2

 56%|█████▌    | 558/1000 [13:13<10:11,  1.38s/it]

[557] Raw: '3
Reference: 3 for social.' → Cleaned: None

 56%|█████▌    | 559/1000 [13:15<10:06,  1.38s/it]

[558] Raw: '2
Reference: 3
 =' → Cleaned: 2

 56%|█████▌    | 560/1000 [13:16<10:00,  1.37s/it]

[559] Raw: '2

[We are working with our suppliers' → Cleaned: 2

 56%|█████▌    | 561/1000 [13:18<10:12,  1.40s/it]

[560] Raw: '2
Tags: foreign currency exchange rates,' → Cleaned: 2

 56%|█████▌    | 562/1000 [13:19<11:05,  1.52s/it]

[561] Raw: '2
Tags: financials Sale financial sales' → Cleaned: 2

 56%|█████▋    | 563/1000 [13:21<10:40,  1.47s/it]

[562] Raw: '2
Reference: [We are also working' → Cleaned: 2

 56%|█████▋    | 564/1000 [13:22<10:23,  1.43s/it]

[563] Raw: '3
Refer: 3 for social =' → Cleaned: None

 56%|█████▋    | 565/1000 [13:23<10:14,  1.41s/it]

[564] Raw: '3
Reference:  Total CO2 emissions' → Cleaned: None

 57%|█████▋    | 566/1000 [13:25<10:03,  1.39s/it]

[565] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 57%|█████▋    | 567/1000 [13:26<09:57,  1.38s/it]

[566] Raw: '3
Reference: 3 = 0' → Cleaned: 0

 57%|█████▋    | 568/1000 [13:28<09:57,  1.38s/it]

[567] Raw: '2
Reference: 2 for non-es' → Cleaned: 2

 57%|█████▋    | 569/1000 [13:29<09:50,  1.37s/it]

[568] Raw: '3
Reference: 3 = social =' → Cleaned: None

 57%|█████▋    | 570/1000 [13:31<10:28,  1.46s/it]

[569] Raw: '0 Labels: 0
Text:' → Cleaned: 0

 57%|█████▋    | 571/1000 [13:32<10:56,  1.53s/it]

[570] Raw: '0
Reference: 0
Link text' → Cleaned: 0

 57%|█████▋    | 572/1000 [13:34<10:32,  1.48s/it]

[571] Raw: '2
Tags: cash flow fiscal fiscal' → Cleaned: 2

 57%|█████▋    | 573/1000 [13:35<10:14,  1.44s/it]

[572] Raw: '0

[We are working with our suppliers' → Cleaned: 0

 57%|█████▋    | 574/1000 [13:36<09:59,  1.41s/it]

[573] Raw: '0
Tags: emissions environmental environmental-emissions' → Cleaned: 0

 57%|█████▊    | 575/1000 [13:38<09:49,  1.39s/it]

[574] Raw: '3
Reference: 3 = social =' → Cleaned: None

 58%|█████▊    | 576/1000 [13:39<09:42,  1.37s/it]

[575] Raw: '2
Reference: 3
Other text' → Cleaned: 2

 58%|█████▊    | 577/1000 [13:40<09:35,  1.36s/it]

[576] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 58%|█████▊    | 578/1000 [13:42<09:30,  1.35s/it]

[577] Raw: '2

[The Company's Board of Directors' → Cleaned: 2

 58%|█████▊    | 579/1000 [13:43<10:20,  1.47s/it]

[578] Raw: '3
Reference: 3 = social =' → Cleaned: None

 58%|█████▊    | 580/1000 [13:45<10:31,  1.50s/it]

[579] Raw: '1 read more
[The Company's Board' → Cleaned: 1

 58%|█████▊    | 581/1000 [13:46<10:10,  1.46s/it]

[580] Raw: '3
Reference: 3 = 12' → Cleaned: None

 58%|█████▊    | 582/1000 [13:48<09:54,  1.42s/it]

[581] Raw: '2
Reference: 2
Text:' → Cleaned: 2

 58%|█████▊    | 583/1000 [13:49<09:42,  1.40s/it]

[582] Raw: '3
Reference: 3 = social' → Cleaned: None

 58%|█████▊    | 584/1000 [13:50<09:35,  1.38s/it]

[583] Raw: '3
Reference: 3 = social' → Cleaned: None

 58%|█████▊    | 585/1000 [13:52<09:30,  1.37s/it]

[584] Raw: '3
Reference: 3 = social =' → Cleaned: None

 59%|█████▊    | 586/1000 [13:53<09:29,  1.37s/it]

[585] Raw: '2
Reference: 3
 =' → Cleaned: 2

 59%|█████▊    | 587/1000 [13:55<09:39,  1.40s/it]

[586] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 59%|█████▉    | 588/1000 [13:56<10:28,  1.52s/it]

[587] Raw: '3
Reference: 3 for social.' → Cleaned: None

 59%|█████▉    | 589/1000 [13:58<10:10,  1.49s/it]

[588] Raw: '3
Reference: 3 = 14' → Cleaned: None

 59%|█████▉    | 590/1000 [13:59<09:50,  1.44s/it]

[589] Raw: '2

[The Company has a policy requiring' → Cleaned: 2

 59%|█████▉    | 591/1000 [14:00<09:35,  1.41s/it]

[590] Raw: '2
Reference: 3
 =' → Cleaned: 2

 59%|█████▉    | 592/1000 [14:02<09:27,  1.39s/it]

[591] Raw: '3
Reference: 3 = social' → Cleaned: None

 59%|█████▉    | 593/1000 [14:03<09:20,  1.38s/it]

[592] Raw: '2
Reference: 3
 =' → Cleaned: 2

 59%|█████▉    | 594/1000 [14:04<09:19,  1.38s/it]

[593] Raw: '2
Refer: 2 for non-es' → Cleaned: 2

 60%|█████▉    | 595/1000 [14:06<09:14,  1.37s/it]

[594] Raw: '3
Reference: 3 = social =' → Cleaned: None

 60%|█████▉    | 596/1000 [14:07<09:41,  1.44s/it]

[595] Raw: '0
Reference: 0
Link text' → Cleaned: 0

 60%|█████▉    | 597/1000 [14:09<10:13,  1.52s/it]

[596] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 60%|█████▉    | 598/1000 [14:10<09:51,  1.47s/it]

[597] Raw: '3
Reference: 3 = social =' → Cleaned: None

 60%|█████▉    | 599/1000 [14:12<09:35,  1.44s/it]

[598] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 60%|██████    | 600/1000 [14:13<09:24,  1.41s/it]

[599] Raw: '3 read more
[We are also working' → Cleaned: None

 60%|██████    | 601/1000 [14:15<09:15,  1.39s/it]

[600] Raw: '3
Reference: 3% of the' → Cleaned: None

 60%|██████    | 602/1000 [14:16<09:07,  1.38s/it]

[601] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 60%|██████    | 603/1000 [14:17<09:06,  1.38s/it]

[602] Raw: '2
Refer: 2 for non-es' → Cleaned: 2

 60%|██████    | 604/1000 [14:19<09:01,  1.37s/it]

[603] Raw: '1

[We are working to reduce the' → Cleaned: 1

 60%|██████    | 605/1000 [14:20<09:45,  1.48s/it]

[604] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 61%|██████    | 606/1000 [14:22<09:51,  1.50s/it]

[605] Raw: '3
Reference: 3 = social' → Cleaned: None

 61%|██████    | 607/1000 [14:23<09:32,  1.46s/it]

[606] Raw: '3
Reference: 3 for social.' → Cleaned: None

 61%|██████    | 608/1000 [14:25<09:19,  1.43s/it]

[607] Raw: '2
Reference: 3' → Cleaned: 2

 61%|██████    | 609/1000 [14:26<09:06,  1.40s/it]

[608] Raw: '2
Reference: [We are also working' → Cleaned: 2

 61%|██████    | 610/1000 [14:27<09:02,  1.39s/it]

[609] Raw: '3
Reference: 3 = social' → Cleaned: None

 61%|██████    | 611/1000 [14:29<08:54,  1.37s/it]

[610] Raw: '3
Reference: 3 = 3' → Cleaned: None

 61%|██████    | 612/1000 [14:30<08:49,  1.36s/it]

[611] Raw: '1
[We have a long-standing commitment' → Cleaned: 1

 61%|██████▏   | 613/1000 [14:31<08:49,  1.37s/it]

[612] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 61%|██████▏   | 614/1000 [14:33<09:33,  1.48s/it]

[613] Raw: '3

[We are working with the World' → Cleaned: None

 62%|██████▏   | 615/1000 [14:35<09:24,  1.47s/it]

[614] Raw: '3

[We are working to reduce the' → Cleaned: None

 62%|██████▏   | 616/1000 [14:36<09:09,  1.43s/it]

[615] Raw: '1
Reference: 1 = governance' → Cleaned: 1

 62%|██████▏   | 617/1000 [14:37<09:01,  1.41s/it]

[616] Raw: '2
Labels: esg, governance,' → Cleaned: 2

 62%|██████▏   | 618/1000 [14:39<08:51,  1.39s/it]

[617] Raw: '' → Cleaned: None

 62%|██████▏   | 619/1000 [14:40<08:46,  1.38s/it]

[618] Raw: '2
Units  = 2
Total' → Cleaned: 2

 62%|██████▏   | 620/1000 [14:41<08:41,  1.37s/it]

[619] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 62%|██████▏   | 621/1000 [14:43<08:39,  1.37s/it]

[620] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 62%|██████▏   | 622/1000 [14:44<08:57,  1.42s/it]

[621] Raw: '0
Reference: 0
Tags:' → Cleaned: 0

 62%|██████▏   | 623/1000 [14:46<09:35,  1.53s/it]

[622] Raw: '0 Labels: 0
Text:' → Cleaned: 0

 62%|██████▏   | 624/1000 [14:47<09:14,  1.47s/it]

[623] Raw: '1 Labels: 1 (1 times)' → Cleaned: 1

 62%|██████▎   | 625/1000 [14:49<08:59,  1.44s/it]

[624] Raw: '2
['We are also working with our' → Cleaned: 2

 63%|██████▎   | 626/1000 [14:50<08:48,  1.41s/it]

[625] Raw: '2
[We have a long-standing commitment' → Cleaned: 2

 63%|██████▎   | 627/1000 [14:51<08:41,  1.40s/it]

[626] Raw: '2
[The Company's accounting policies are' → Cleaned: 2

 63%|██████▎   | 628/1000 [14:53<08:34,  1.38s/it]

[627] Raw: '3
Reference: 3 = social =' → Cleaned: None

 63%|██████▎   | 629/1000 [14:54<08:28,  1.37s/it]

[628] Raw: '2 = 0.0334 =' → Cleaned: 2

 63%|██████▎   | 630/1000 [14:55<08:24,  1.36s/it]

[629] Raw: '3
Reference: 3 = social =' → Cleaned: None

 63%|██████▎   | 631/1000 [14:57<09:01,  1.47s/it]

[630] Raw: '1 Labels: ClassLabels: 1 Text' → Cleaned: 1

 63%|██████▎   | 632/1000 [14:59<09:20,  1.52s/it]

[631] Raw: '3

[We are working with our suppliers' → Cleaned: None

 63%|██████▎   | 633/1000 [15:00<09:00,  1.47s/it]

[632] Raw: '2
Reference: 0
[] The' → Cleaned: 2

 63%|██████▎   | 634/1000 [15:02<08:44,  1.43s/it]

[633] Raw: '2
['We are also working with our' → Cleaned: 2

 64%|██████▎   | 635/1000 [15:03<08:35,  1.41s/it]

[634] Raw: '2 = 0.0333 =' → Cleaned: 2

 64%|██████▎   | 636/1000 [15:04<08:26,  1.39s/it]

[635] Raw: '2
Tags: governance financial governance governance financial' → Cleaned: 2

 64%|██████▎   | 637/1000 [15:06<08:22,  1.38s/it]

[636] Raw: '1

[We are also working with our' → Cleaned: 1

 64%|██████▍   | 638/1000 [15:07<08:18,  1.38s/it]

[637] Raw: '2
Reference: [The Company's Board' → Cleaned: 2

 64%|██████▍   | 639/1000 [15:08<08:15,  1.37s/it]

[638] Raw: '2

[We are working with our suppliers' → Cleaned: 2

 64%|██████▍   | 640/1000 [15:10<08:58,  1.49s/it]

[639] Raw: '2 = 0.0333 =' → Cleaned: 2

 64%|██████▍   | 641/1000 [15:12<08:48,  1.47s/it]

[640] Raw: '3
Reference: 3 = social =' → Cleaned: None

 64%|██████▍   | 642/1000 [15:13<08:33,  1.43s/it]

[641] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 64%|██████▍   | 643/1000 [15:14<08:24,  1.41s/it]

[642] Raw: '2
['We are also working with our' → Cleaned: 2

 64%|██████▍   | 644/1000 [15:16<08:18,  1.40s/it]

[643] Raw: '3
Refer: 3 for social =' → Cleaned: None

 64%|██████▍   | 645/1000 [15:17<08:11,  1.38s/it]

[644] Raw: '2
["We are also working with our' → Cleaned: 2

 65%|██████▍   | 646/1000 [15:18<08:08,  1.38s/it]

[645] Raw: '2 = 0.0000 =' → Cleaned: 2

 65%|██████▍   | 647/1000 [15:20<08:04,  1.37s/it]

[646] Raw: '2
[We are working with the World' → Cleaned: 2

 65%|██████▍   | 648/1000 [15:21<08:21,  1.42s/it]

[647] Raw: '3
Reference: 3 for social.' → Cleaned: None

 65%|██████▍   | 649/1000 [15:23<08:59,  1.54s/it]

[648] Raw: '3
Reference: 3 for social.' → Cleaned: None

 65%|██████▌   | 650/1000 [15:24<08:37,  1.48s/it]

[649] Raw: '2 = 0.0334 =' → Cleaned: 2

 65%|██████▌   | 651/1000 [15:26<08:23,  1.44s/it]

[650] Raw: '1
Reference: 3
Other text' → Cleaned: 1

 65%|██████▌   | 652/1000 [15:27<08:14,  1.42s/it]

[651] Raw: '3
Reference: 3 = social =' → Cleaned: None

 65%|██████▌   | 653/1000 [15:29<08:14,  1.42s/it]

[652] Raw: '1

[We are working with the World' → Cleaned: 1

 65%|██████▌   | 654/1000 [15:30<08:02,  1.40s/it]

[653] Raw: '3
Reference: 3 = social =' → Cleaned: None

 66%|██████▌   | 655/1000 [15:31<07:56,  1.38s/it]

[654] Raw: '3
Reference: 3 = social =' → Cleaned: None

 66%|██████▌   | 656/1000 [15:33<07:52,  1.37s/it]

[655] Raw: '2
Tags: freight, handling, idle' → Cleaned: 2

 66%|██████▌   | 657/1000 [15:34<08:22,  1.47s/it]

[656] Raw: '1
Reference: 3
Type:' → Cleaned: 1

 66%|██████▌   | 658/1000 [15:36<08:36,  1.51s/it]

[657] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 66%|██████▌   | 659/1000 [15:37<08:17,  1.46s/it]

[658] Raw: '3
Reference: 3 = social' → Cleaned: None

 66%|██████▌   | 660/1000 [15:39<08:04,  1.42s/it]

[659] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 66%|██████▌   | 661/1000 [15:40<07:56,  1.41s/it]

[660] Raw: '2
Reference: 3
 =' → Cleaned: 2

 66%|██████▌   | 662/1000 [15:41<07:50,  1.39s/it]

[661] Raw: '2
Reference: 3.0%' → Cleaned: 2

 66%|██████▋   | 663/1000 [15:43<07:44,  1.38s/it]

[662] Raw: '2
Reference: 3
 =' → Cleaned: 2

 66%|██████▋   | 664/1000 [15:44<07:40,  1.37s/it]

[663] Raw: '1
Reference: 1 (govern' → Cleaned: 1

 66%|██████▋   | 665/1000 [15:45<07:36,  1.36s/it]

[664] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 67%|██████▋   | 666/1000 [15:47<08:14,  1.48s/it]

[665] Raw: '1 Labels: 1 (1) =' → Cleaned: 1

 67%|██████▋   | 667/1000 [15:49<08:09,  1.47s/it]

[666] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 67%|██████▋   | 668/1000 [15:50<07:55,  1.43s/it]

[667] Raw: '3
Reference: 3 = 3' → Cleaned: None

 67%|██████▋   | 669/1000 [15:51<07:47,  1.41s/it]

[668] Raw: '3
Reference: 3 = 12' → Cleaned: None

 67%|██████▋   | 670/1000 [15:53<07:39,  1.39s/it]

[669] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 67%|██████▋   | 671/1000 [15:54<07:34,  1.38s/it]

[670] Raw: '2
Reference: 3
 =' → Cleaned: 2

 67%|██████▋   | 672/1000 [15:55<07:29,  1.37s/it]

[671] Raw: '3
Reference: 3 = 0' → Cleaned: 0

 67%|██████▋   | 673/1000 [15:57<07:28,  1.37s/it]

[672] Raw: '2

[The Company's future operating results' → Cleaned: 2

 67%|██████▋   | 674/1000 [15:58<07:42,  1.42s/it]

[673] Raw: '1

[We have a policy requiring employees' → Cleaned: 1

 68%|██████▊   | 675/1000 [16:00<08:21,  1.54s/it]

[674] Raw: '3
Reference: 3 = 33' → Cleaned: None

 68%|██████▊   | 676/1000 [16:01<08:01,  1.48s/it]

[675] Raw: '2
Reference: 0
 =' → Cleaned: 2

 68%|██████▊   | 677/1000 [16:03<07:45,  1.44s/it]

[676] Raw: '1

[We are working to reduce the' → Cleaned: 1

 68%|██████▊   | 678/1000 [16:04<07:41,  1.43s/it]

[677] Raw: '3
Reference: 3 = social =' → Cleaned: None

 68%|██████▊   | 679/1000 [16:05<07:33,  1.41s/it]

[678] Raw: '0 read more > The 2015 Plan' → Cleaned: 0

 68%|██████▊   | 680/1000 [16:07<07:30,  1.41s/it]

[679] Raw: '3
Reference: 3 = social =' → Cleaned: None

 68%|██████▊   | 681/1000 [16:08<07:26,  1.40s/it]

[680] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 68%|██████▊   | 682/1000 [16:10<07:21,  1.39s/it]

[681] Raw: '3
Reference: 3,353 =' → Cleaned: None

 68%|██████▊   | 683/1000 [16:11<07:49,  1.48s/it]

[682] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 68%|██████▊   | 684/1000 [16:13<07:58,  1.51s/it]

[683] Raw: '1
Reference: 1
Other text' → Cleaned: 1

 68%|██████▊   | 685/1000 [16:14<07:41,  1.47s/it]

[684] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 69%|██████▊   | 686/1000 [16:16<07:28,  1.43s/it]

[685] Raw: '2
Reference: 3
 =' → Cleaned: 2

 69%|██████▊   | 687/1000 [16:17<07:18,  1.40s/it]

[686] Raw: '3
Reference: 3 = social =' → Cleaned: None

 69%|██████▉   | 688/1000 [16:18<07:10,  1.38s/it]

[687] Raw: '2 = 0.0333 =' → Cleaned: 2

 69%|██████▉   | 689/1000 [16:20<07:06,  1.37s/it]

[688] Raw: '0
Reference: 0
 =' → Cleaned: 0

 69%|██████▉   | 690/1000 [16:21<07:04,  1.37s/it]

[689] Raw: '2
[We have a long-standing commitment' → Cleaned: 2

 69%|██████▉   | 691/1000 [16:22<07:00,  1.36s/it]

[690] Raw: '1 Labels: 1 (1 times)' → Cleaned: 1

 69%|██████▉   | 692/1000 [16:24<07:34,  1.48s/it]

[691] Raw: '2
Refer:  Residual value liabilities' → Cleaned: 2

 69%|██████▉   | 693/1000 [16:26<07:35,  1.48s/it]

[692] Raw: '3
Reference: 3 = social =' → Cleaned: None

 69%|██████▉   | 694/1000 [16:27<07:22,  1.45s/it]

[693] Raw: '1
[The Company’s Board of Directors' → Cleaned: 1

 70%|██████▉   | 695/1000 [16:28<07:15,  1.43s/it]

[694] Raw: '2
Refer:  [The Company's' → Cleaned: 2

 70%|██████▉   | 696/1000 [16:30<07:06,  1.40s/it]

[695] Raw: '1
Reference: 1
Label:' → Cleaned: 1

 70%|██████▉   | 697/1000 [16:31<06:59,  1.39s/it]

[696] Raw: '3

[We are working with our suppliers' → Cleaned: None

 70%|██████▉   | 698/1000 [16:32<06:55,  1.38s/it]

[697] Raw: '2 = 0.0333 =' → Cleaned: 2

 70%|██████▉   | 699/1000 [16:34<06:53,  1.37s/it]

[698] Raw: '3

[We are working to reduce our' → Cleaned: None

 70%|███████   | 700/1000 [16:35<07:01,  1.41s/it]

[699] Raw: '0
Reference: 0
Other:' → Cleaned: 0

 70%|███████   | 701/1000 [16:37<07:35,  1.52s/it]

[700] Raw: '2
Reference:  Income from our Com' → Cleaned: 2

 70%|███████   | 702/1000 [16:38<07:19,  1.47s/it]

[701] Raw: '2 = 0.0333 =' → Cleaned: 2

 70%|███████   | 703/1000 [16:40<07:05,  1.43s/it]

[702] Raw: '1
Reference: 1 = governance' → Cleaned: 1

 70%|███████   | 704/1000 [16:41<06:55,  1.40s/it]

[703] Raw: '1
Reference: 1 (govern' → Cleaned: 1

 70%|███████   | 705/1000 [16:42<06:50,  1.39s/it]

[704] Raw: '2 Labels: 0, 2,' → Cleaned: 2

 71%|███████   | 706/1000 [16:44<06:43,  1.37s/it]

[705] Raw: '2
Reference: 3
 =' → Cleaned: 2

 71%|███████   | 707/1000 [16:45<06:40,  1.37s/it]

[706] Raw: '0
Reference: 0
Has label' → Cleaned: 0

 71%|███████   | 708/1000 [16:47<06:49,  1.40s/it]

[707] Raw: '0
Reference: 0
Has label' → Cleaned: 0

 71%|███████   | 709/1000 [16:48<07:15,  1.50s/it]

[708] Raw: '2
[We are also working with the' → Cleaned: 2

 71%|███████   | 710/1000 [16:50<07:33,  1.56s/it]

[709] Raw: '1

[We are working to reduce our' → Cleaned: 1

 71%|███████   | 711/1000 [16:51<07:14,  1.50s/it]

[710] Raw: '0 Labels: 0
Text:' → Cleaned: 0

 71%|███████   | 712/1000 [16:53<07:00,  1.46s/it]

[711] Raw: '0
[We are also working with our' → Cleaned: 0

 71%|███████▏  | 713/1000 [16:54<06:49,  1.43s/it]

[712] Raw: '2 = 0.0333 =' → Cleaned: 2

 71%|███████▏  | 714/1000 [16:55<06:41,  1.40s/it]

[713] Raw: '2
Reference: 3
[The' → Cleaned: 2

 72%|███████▏  | 715/1000 [16:57<06:34,  1.38s/it]

[714] Raw: '2
Reference: 2
Class:' → Cleaned: 2

 72%|███████▏  | 716/1000 [16:58<06:32,  1.38s/it]

[715] Raw: '3 read more
[We are working to' → Cleaned: None

 72%|███████▏  | 717/1000 [17:00<06:39,  1.41s/it]

[716] Raw: '1
Reference:  [We have a' → Cleaned: 1

 72%|███████▏  | 718/1000 [17:02<07:23,  1.57s/it]

[717] Raw: '0 = 0 labels 1 text.' → Cleaned: 0

 72%|███████▏  | 719/1000 [17:03<07:16,  1.55s/it]

[718] Raw: '2
[The Company’s Board of Directors' → Cleaned: 2

 72%|███████▏  | 720/1000 [17:04<07:00,  1.50s/it]

[719] Raw: '0
Reference: 0' → Cleaned: 0

 72%|███████▏  | 721/1000 [17:06<06:48,  1.46s/it]

[720] Raw: '2
Reference:  [The Company's' → Cleaned: 2

 72%|███████▏  | 722/1000 [17:07<06:36,  1.43s/it]

[721] Raw: '1

[We are also working with the' → Cleaned: 1

 72%|███████▏  | 723/1000 [17:09<06:32,  1.42s/it]

[722] Raw: '2
Reference: 4,553,' → Cleaned: 2

 72%|███████▏  | 724/1000 [17:10<06:29,  1.41s/it]

[723] Raw: '2

[The Company's consolidated financial statements' → Cleaned: 2

 72%|███████▎  | 725/1000 [17:11<06:27,  1.41s/it]

[724] Raw: '3
Reference: 3 = 39' → Cleaned: None

 73%|███████▎  | 726/1000 [17:13<06:44,  1.48s/it]

[725] Raw: '2
Reference: 3
[The' → Cleaned: 2

 73%|███████▎  | 727/1000 [17:15<07:06,  1.56s/it]

[726] Raw: '2
Reference: 2 for non-es' → Cleaned: 2

 73%|███████▎  | 728/1000 [17:16<06:49,  1.50s/it]

[727] Raw: '3
Reference: 3 = social =' → Cleaned: None

 73%|███████▎  | 729/1000 [17:17<06:37,  1.47s/it]

[728] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 73%|███████▎  | 730/1000 [17:19<06:27,  1.44s/it]

[729] Raw: '3
Reference: 3 = 14' → Cleaned: None

 73%|███████▎  | 731/1000 [17:20<06:21,  1.42s/it]

[730] Raw: '2 = 0.0333 =' → Cleaned: 2

 73%|███████▎  | 732/1000 [17:22<06:16,  1.40s/it]

[731] Raw: '3
Reference: 3 for social.' → Cleaned: None

 73%|███████▎  | 733/1000 [17:23<06:10,  1.39s/it]

[732] Raw: '1
Reference:  [We are also' → Cleaned: 1

 73%|███████▎  | 734/1000 [17:24<06:02,  1.36s/it]

[733] Raw: '3
Reference: 3 = social' → Cleaned: None

 74%|███████▎  | 735/1000 [17:26<06:32,  1.48s/it]

[734] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 74%|███████▎  | 736/1000 [17:28<06:36,  1.50s/it]

[735] Raw: '1

[We are working to reduce our' → Cleaned: 1

 74%|███████▎  | 737/1000 [17:29<06:27,  1.47s/it]

[736] Raw: '3
Reference: 3 = social =' → Cleaned: None

 74%|███████▍  | 738/1000 [17:30<06:18,  1.45s/it]

[737] Raw: '0 read more > 0 read more >' → Cleaned: 0

 74%|███████▍  | 739/1000 [17:32<06:11,  1.42s/it]

[738] Raw: '2
Reference: 2 for non-es' → Cleaned: 2

 74%|███████▍  | 740/1000 [17:33<06:05,  1.41s/it]

[739] Raw: '3
Reference: 3 = social =' → Cleaned: None

 74%|███████▍  | 741/1000 [17:34<05:59,  1.39s/it]

[740] Raw: '3
Reference: 3 = social =' → Cleaned: None

 74%|███████▍  | 742/1000 [17:36<05:56,  1.38s/it]

[741] Raw: '3

[We are working to reduce our' → Cleaned: None

 74%|███████▍  | 743/1000 [17:37<06:06,  1.42s/it]

[742] Raw: '2
[The Company's net income for' → Cleaned: 2

 74%|███████▍  | 744/1000 [17:39<06:34,  1.54s/it]

[743] Raw: '3
Reference: 3 for social.' → Cleaned: None

 74%|███████▍  | 745/1000 [17:41<06:19,  1.49s/it]

[744] Raw: '3
Reference: 3 = social =' → Cleaned: None

 75%|███████▍  | 746/1000 [17:42<06:07,  1.45s/it]

[745] Raw: '3

[We are working with our suppliers' → Cleaned: None

 75%|███████▍  | 747/1000 [17:43<05:58,  1.42s/it]

[746] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 75%|███████▍  | 748/1000 [17:45<05:52,  1.40s/it]

[747] Raw: '3

[We are working with our suppliers' → Cleaned: None

 75%|███████▍  | 749/1000 [17:46<05:46,  1.38s/it]

[748] Raw: '3
Reference: 3 for social.' → Cleaned: None

 75%|███████▌  | 750/1000 [17:47<05:42,  1.37s/it]

[749] Raw: '3
Reference: 3 = 1' → Cleaned: 1

 75%|███████▌  | 751/1000 [17:49<05:39,  1.36s/it]

[750] Raw: '3
Reference: [We are working with' → Cleaned: None

 75%|███████▌  | 752/1000 [17:50<06:02,  1.46s/it]

[751] Raw: '3
Reference: 3 = 12' → Cleaned: None

 75%|███████▌  | 753/1000 [17:52<06:18,  1.53s/it]

[752] Raw: '2
Reference:  [We have a' → Cleaned: 2

 75%|███████▌  | 754/1000 [17:53<06:06,  1.49s/it]

[753] Raw: '2
['We are also working with the' → Cleaned: 2

 76%|███████▌  | 755/1000 [17:55<05:55,  1.45s/it]

[754] Raw: '0 Labels: 0
Text:' → Cleaned: 0

 76%|███████▌  | 756/1000 [17:56<05:47,  1.43s/it]

[755] Raw: '3
Refer: 3 for social.' → Cleaned: None

 76%|███████▌  | 757/1000 [17:57<05:41,  1.41s/it]

[756] Raw: '2
Reference: 3' → Cleaned: 2

 76%|███████▌  | 758/1000 [17:59<05:39,  1.40s/it]

[757] Raw: '3
Reference: 3 = social =' → Cleaned: None

 76%|███████▌  | 759/1000 [18:00<05:32,  1.38s/it]

[758] Raw: '3
Reference: 3 = 58' → Cleaned: None

 76%|███████▌  | 760/1000 [18:02<05:28,  1.37s/it]

[759] Raw: '3
Reference: 3 for social.' → Cleaned: None

 76%|███████▌  | 761/1000 [18:03<05:53,  1.48s/it]

[760] Raw: '3
Reference: 3 = social =' → Cleaned: None

 76%|███████▌  | 762/1000 [18:05<05:53,  1.49s/it]

[761] Raw: '3
Reference: 3 = social =' → Cleaned: None

 76%|███████▋  | 763/1000 [18:06<05:43,  1.45s/it]

[762] Raw: '1
[We are also working with the' → Cleaned: 1

 76%|███████▋  | 764/1000 [18:07<05:33,  1.41s/it]

[763] Raw: '3
Reference: 3 = social =' → Cleaned: None

 76%|███████▋  | 765/1000 [18:09<05:27,  1.39s/it]

[764] Raw: '1
Reference: [The training is designed' → Cleaned: 1

 77%|███████▋  | 766/1000 [18:10<05:22,  1.38s/it]

[765] Raw: '2 = 0.0139 =' → Cleaned: 2

 77%|███████▋  | 767/1000 [18:12<05:20,  1.38s/it]

[766] Raw: '2
Reference: 3
 =' → Cleaned: 2

 77%|███████▋  | 768/1000 [18:13<05:17,  1.37s/it]

[767] Raw: '2
Reference: [We are also working' → Cleaned: 2

 77%|███████▋  | 769/1000 [18:14<05:24,  1.41s/it]

[768] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 77%|███████▋  | 770/1000 [18:16<05:52,  1.53s/it]

[769] Raw: '2 = 0.0334 =' → Cleaned: 2

 77%|███████▋  | 771/1000 [18:18<05:39,  1.48s/it]

[770] Raw: '2
Refer: 3. Non-' → Cleaned: 2

 77%|███████▋  | 772/1000 [18:19<05:29,  1.45s/it]

[771] Raw: '2
Refer: 3' → Cleaned: 2

 77%|███████▋  | 773/1000 [18:20<05:21,  1.42s/it]

[772] Raw: '3
Reference: 3 = 15' → Cleaned: None

 77%|███████▋  | 774/1000 [18:22<05:16,  1.40s/it]

[773] Raw: '2
[The Company's operating segments are' → Cleaned: 2

 78%|███████▊  | 775/1000 [18:23<05:11,  1.39s/it]

[774] Raw: '2
Reference: 3' → Cleaned: 2

 78%|███████▊  | 776/1000 [18:24<05:08,  1.38s/it]

[775] Raw: '2 = 0.0005 =' → Cleaned: 2

 78%|███████▊  | 777/1000 [18:26<05:04,  1.37s/it]

[776] Raw: '3
Reference: 3 = social =' → Cleaned: None

 78%|███████▊  | 778/1000 [18:27<05:22,  1.45s/it]

[777] Raw: '1
Reference: 1
Other text' → Cleaned: 1

 78%|███████▊  | 779/1000 [18:29<05:36,  1.52s/it]

[778] Raw: '3

[The Company has a significant amount' → Cleaned: None

 78%|███████▊  | 780/1000 [18:30<05:27,  1.49s/it]

[779] Raw: '0 read more » [The water used in' → Cleaned: 0

 78%|███████▊  | 781/1000 [18:32<05:17,  1.45s/it]

[780] Raw: '2
Reference:  [We have a' → Cleaned: 2

 78%|███████▊  | 782/1000 [18:33<05:09,  1.42s/it]

[781] Raw: '3
Reference: 3 for social.' → Cleaned: None

 78%|███████▊  | 783/1000 [18:34<05:02,  1.39s/it]

[782] Raw: '3
Reference: 3 = social =' → Cleaned: None

 78%|███████▊  | 784/1000 [18:36<04:58,  1.38s/it]

[783] Raw: '3
Labels: 0, 1' → Cleaned: 0

 78%|███████▊  | 785/1000 [18:37<04:55,  1.38s/it]

[784] Raw: '2
Reference: 3
 =' → Cleaned: 2

 79%|███████▊  | 786/1000 [18:39<04:53,  1.37s/it]

[785] Raw: '3
Reference: 0
Label:' → Cleaned: 0

 79%|███████▊  | 787/1000 [18:40<05:16,  1.49s/it]

[786] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 79%|███████▉  | 788/1000 [18:42<05:14,  1.48s/it]

[787] Raw: '2
Reference:  [The Company's' → Cleaned: 2

 79%|███████▉  | 789/1000 [18:43<05:03,  1.44s/it]

[788] Raw: '2 Labels: 2
Text:' → Cleaned: 2

 79%|███████▉  | 790/1000 [18:44<04:57,  1.41s/it]

[789] Raw: '1 read more
[The Company has a' → Cleaned: 1

 79%|███████▉  | 791/1000 [18:46<04:51,  1.39s/it]

[790] Raw: '0
Reference: 0
Link text' → Cleaned: 0

 79%|███████▉  | 792/1000 [18:47<04:46,  1.38s/it]

[791] Raw: '3
Labels: esg, governance,' → Cleaned: None

 79%|███████▉  | 793/1000 [18:48<04:42,  1.37s/it]

[792] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 79%|███████▉  | 794/1000 [18:50<04:40,  1.36s/it]

[793] Raw: '2
Reference: [We are also working' → Cleaned: 2

 80%|███████▉  | 795/1000 [18:51<04:49,  1.41s/it]

[794] Raw: '1
Reference:  [The Company's' → Cleaned: 1

 80%|███████▉  | 796/1000 [18:53<05:11,  1.53s/it]

[795] Raw: '3
Reference: 3 = social;' → Cleaned: None

 80%|███████▉  | 797/1000 [18:55<05:00,  1.48s/it]

[796] Raw: '3
['We are also working with our' → Cleaned: None

 80%|███████▉  | 798/1000 [18:56<04:51,  1.44s/it]

[797] Raw: '2
Reference:  [The Company's' → Cleaned: 2

 80%|███████▉  | 799/1000 [18:57<04:45,  1.42s/it]

[798] Raw: '3
Reference: 3 = 3' → Cleaned: None

 80%|████████  | 800/1000 [18:59<04:39,  1.40s/it]

[799] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 80%|████████  | 801/1000 [19:00<04:36,  1.39s/it]

[800] Raw: '1

[We are working with our suppliers' → Cleaned: 1

 80%|████████  | 802/1000 [19:01<04:34,  1.39s/it]

[801] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 80%|████████  | 803/1000 [19:03<04:30,  1.37s/it]

[802] Raw: '1
Reference: 1
Topic-label' → Cleaned: 1

 80%|████████  | 804/1000 [19:04<04:45,  1.46s/it]

[803] Raw: '3
Reference: 3 for social.' → Cleaned: None

 80%|████████  | 805/1000 [19:06<04:57,  1.52s/it]

[804] Raw: '2
Refer: Ford 2013 C' → Cleaned: 2

 81%|████████  | 806/1000 [19:07<04:44,  1.47s/it]

[805] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 81%|████████  | 807/1000 [19:09<04:35,  1.43s/it]

[806] Raw: '2
Reference: 3
 =' → Cleaned: 2

 81%|████████  | 808/1000 [19:10<04:30,  1.41s/it]

[807] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 81%|████████  | 809/1000 [19:11<04:25,  1.39s/it]

[808] Raw: '0
Reference: 0
 =' → Cleaned: 0

 81%|████████  | 810/1000 [19:13<04:22,  1.38s/it]

[809] Raw: '1
[The Company's Board of Directors' → Cleaned: 1

 81%|████████  | 811/1000 [19:14<04:19,  1.37s/it]

[810] Raw: '0
Reference: 0
Context:' → Cleaned: 0

 81%|████████  | 812/1000 [19:16<04:17,  1.37s/it]

[811] Raw: '3
Reference: 3 for social.' → Cleaned: None

 81%|████████▏ | 813/1000 [19:17<04:38,  1.49s/it]

[812] Raw: '1
[The Company has a long-standing' → Cleaned: 1

 81%|████████▏ | 814/1000 [19:19<04:37,  1.49s/it]

[813] Raw: '2
['We are also working with the' → Cleaned: 2

 82%|████████▏ | 815/1000 [19:20<04:27,  1.44s/it]

[814] Raw: '2
Reference: 3
Other:' → Cleaned: 2

 82%|████████▏ | 816/1000 [19:21<04:19,  1.41s/it]

[815] Raw: '3
Reference:  For other materials,' → Cleaned: None

 82%|████████▏ | 817/1000 [19:23<04:14,  1.39s/it]

[816] Raw: '2

[The Company has a long-standing' → Cleaned: 2

 82%|████████▏ | 818/1000 [19:24<04:10,  1.38s/it]

[817] Raw: '3
Reference: 3 = social =' → Cleaned: None

 82%|████████▏ | 819/1000 [19:25<04:07,  1.37s/it]

[818] Raw: '3

[We are working to reduce the' → Cleaned: None

 82%|████████▏ | 820/1000 [19:27<04:06,  1.37s/it]

[819] Raw: '2
['We are also working with the' → Cleaned: 2

 82%|████████▏ | 821/1000 [19:28<04:10,  1.40s/it]

[820] Raw: '2
Reference: 2 for non-es' → Cleaned: 2

 82%|████████▏ | 822/1000 [19:30<04:32,  1.53s/it]

[821] Raw: '0
Reference: 0
Tags:' → Cleaned: 0

 82%|████████▏ | 823/1000 [19:32<04:21,  1.48s/it]

[822] Raw: '2
Reference:  [The purchase or' → Cleaned: 2

 82%|████████▏ | 824/1000 [19:33<04:13,  1.44s/it]

[823] Raw: '2
[We are also working with our' → Cleaned: 2

 82%|████████▎ | 825/1000 [19:34<04:08,  1.42s/it]

[824] Raw: '2
[The Company's consolidated effective tax' → Cleaned: 2

 83%|████████▎ | 826/1000 [19:36<04:03,  1.40s/it]

[825] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 83%|████████▎ | 827/1000 [19:37<03:58,  1.38s/it]

[826] Raw: '3
Refer: 3 for social =' → Cleaned: None

 83%|████████▎ | 828/1000 [19:38<03:55,  1.37s/it]

[827] Raw: '2
Refer: 3 = social =' → Cleaned: 2

 83%|████████▎ | 829/1000 [19:40<03:53,  1.36s/it]

[828] Raw: '3
Reference: 3 = social =' → Cleaned: None

 83%|████████▎ | 830/1000 [19:41<04:04,  1.44s/it]

[829] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 83%|████████▎ | 831/1000 [19:43<04:17,  1.52s/it]

[830] Raw: '2
Reference: 3
[We' → Cleaned: 2

 83%|████████▎ | 832/1000 [19:44<04:07,  1.47s/it]

[831] Raw: '2

[We are working to reduce our' → Cleaned: 2

 83%|████████▎ | 833/1000 [19:46<04:00,  1.44s/it]

[832] Raw: '3
Reference: 3 = social =' → Cleaned: None

 83%|████████▎ | 834/1000 [19:47<03:54,  1.41s/it]

[833] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 84%|████████▎ | 835/1000 [19:48<03:49,  1.39s/it]

[834] Raw: '2
Reference: 3
Tag:' → Cleaned: 2

 84%|████████▎ | 836/1000 [19:50<03:46,  1.38s/it]

[835] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 84%|████████▎ | 837/1000 [19:51<03:43,  1.37s/it]

[836] Raw: '3

[The Company's Board of Directors' → Cleaned: None

 84%|████████▍ | 838/1000 [19:52<03:40,  1.36s/it]

[837] Raw: '3
Reference:  For the fourth consecutive' → Cleaned: None

 84%|████████▍ | 839/1000 [19:54<03:57,  1.47s/it]

[838] Raw: '2

[The Company has a long-standing' → Cleaned: 2

 84%|████████▍ | 840/1000 [19:56<03:59,  1.50s/it]

[839] Raw: '3
Reference: 3 = social =' → Cleaned: None

 84%|████████▍ | 841/1000 [19:57<03:51,  1.46s/it]

[840] Raw: '2
Reference: [The Company intends to' → Cleaned: 2

 84%|████████▍ | 842/1000 [19:58<03:44,  1.42s/it]

[841] Raw: '3
Reference: 3 for social.' → Cleaned: None

 84%|████████▍ | 843/1000 [20:00<03:41,  1.41s/it]

[842] Raw: '2
[The Company's Board of Directors' → Cleaned: 2

 84%|████████▍ | 844/1000 [20:01<03:39,  1.41s/it]

[843] Raw: '3
Reference: 3 = social =' → Cleaned: None

 84%|████████▍ | 845/1000 [20:03<03:36,  1.40s/it]

[844] Raw: '3
Reference: 3 for social.' → Cleaned: None

 85%|████████▍ | 846/1000 [20:04<03:32,  1.38s/it]

[845] Raw: '1

[We are also working with our' → Cleaned: 1

 85%|████████▍ | 847/1000 [20:05<03:34,  1.40s/it]

[846] Raw: '2
Reference:  [We also have' → Cleaned: 2

 85%|████████▍ | 848/1000 [20:07<03:51,  1.52s/it]

[847] Raw: '2

[The Company's consolidated financial statements' → Cleaned: 2

 85%|████████▍ | 849/1000 [20:08<03:41,  1.47s/it]

[848] Raw: '1
Reference: 3
 =' → Cleaned: 1

 85%|████████▌ | 850/1000 [20:10<03:35,  1.44s/it]

[849] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 85%|████████▌ | 851/1000 [20:11<03:27,  1.40s/it]

[850] Raw: '0 Labels: 0 [The 201' → Cleaned: 0

 85%|████████▌ | 852/1000 [20:12<03:24,  1.38s/it]

[851] Raw: '3
Reference: [The Company’s Board' → Cleaned: None

 85%|████████▌ | 853/1000 [20:14<03:22,  1.37s/it]

[852] Raw: '2 Labels: 0, 2,' → Cleaned: 2

 85%|████████▌ | 854/1000 [20:15<03:19,  1.37s/it]

[853] Raw: '2
Reference: 3,004,' → Cleaned: 2

 86%|████████▌ | 855/1000 [20:17<03:17,  1.36s/it]

[854] Raw: '1
Reference: 1
Label:' → Cleaned: 1

 86%|████████▌ | 856/1000 [20:18<03:26,  1.43s/it]

[855] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 86%|████████▌ | 857/1000 [20:20<03:38,  1.52s/it]

[856] Raw: '3
Reference: 3 = social =' → Cleaned: None

 86%|████████▌ | 858/1000 [20:21<03:28,  1.47s/it]

[857] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 86%|████████▌ | 859/1000 [20:23<03:22,  1.44s/it]

[858] Raw: '3
Refer: 3 for social' → Cleaned: None

 86%|████████▌ | 860/1000 [20:24<03:17,  1.41s/it]

[859] Raw: '0
Reference: 0
Text:' → Cleaned: 0

 86%|████████▌ | 861/1000 [20:25<03:13,  1.39s/it]

[860] Raw: '2

[The Company's Board of Directors' → Cleaned: 2

 86%|████████▌ | 862/1000 [20:27<03:10,  1.38s/it]

[861] Raw: '3
Reference: 0
Other text' → Cleaned: 0

 86%|████████▋ | 863/1000 [20:28<03:07,  1.37s/it]

[862] Raw: '1
[The Company’s Board of Directors' → Cleaned: 1

 86%|████████▋ | 864/1000 [20:29<03:05,  1.37s/it]

[863] Raw: '2
Reference: 3
 =' → Cleaned: 2

 86%|████████▋ | 865/1000 [20:31<03:21,  1.50s/it]

[864] Raw: '1
Reference: 1
Label:' → Cleaned: 1

 87%|████████▋ | 866/1000 [20:33<03:23,  1.52s/it]

[865] Raw: '2
Reference: 2 (non-es' → Cleaned: 2

 87%|████████▋ | 867/1000 [20:34<03:14,  1.46s/it]

[866] Raw: '2
Reference: [We are also working' → Cleaned: 2

 87%|████████▋ | 868/1000 [20:35<03:09,  1.43s/it]

[867] Raw: '2
[The Company's proven and probable' → Cleaned: 2

 87%|████████▋ | 869/1000 [20:37<03:04,  1.41s/it]

[868] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 87%|████████▋ | 870/1000 [20:38<03:01,  1.39s/it]

[869] Raw: '2
Tags: deferred-income-tax-asset' → Cleaned: 2

 87%|████████▋ | 871/1000 [20:39<02:57,  1.38s/it]

[870] Raw: '2

[We have a long-standing commitment' → Cleaned: 2

 87%|████████▋ | 872/1000 [20:41<02:55,  1.37s/it]

[871] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 87%|████████▋ | 873/1000 [20:42<02:56,  1.39s/it]

[872] Raw: '2
Reference: 3
[The' → Cleaned: 2

 87%|████████▋ | 874/1000 [20:44<03:09,  1.50s/it]

[873] Raw: '0 read more » 0 [One way' → Cleaned: 0

 88%|████████▊ | 875/1000 [20:45<03:02,  1.46s/it]

[874] Raw: '1
Reference: 3
 =' → Cleaned: 1

 88%|████████▊ | 876/1000 [20:47<02:56,  1.43s/it]

[875] Raw: '3

[The Company has a long-standing' → Cleaned: None

 88%|████████▊ | 877/1000 [20:48<02:52,  1.40s/it]

[876] Raw: '3
Reference: 3 = social =' → Cleaned: None

 88%|████████▊ | 878/1000 [20:49<02:47,  1.38s/it]

[877] Raw: '1
Reference:  [We will continue' → Cleaned: 1

 88%|████████▊ | 879/1000 [20:51<02:46,  1.37s/it]

[878] Raw: '2
Tags: fiscal, inventory, ob' → Cleaned: 2

 88%|████████▊ | 880/1000 [20:52<02:43,  1.37s/it]

[879] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 88%|████████▊ | 881/1000 [20:53<02:42,  1.37s/it]

[880] Raw: '3
Refer: 3 for social' → Cleaned: None

 88%|████████▊ | 882/1000 [20:55<02:48,  1.42s/it]

[881] Raw: '3
Tags: healthcare, partnership, improving' → Cleaned: None

 88%|████████▊ | 883/1000 [20:57<02:59,  1.53s/it]

[882] Raw: '3
Reference: 3 for social.' → Cleaned: None

 88%|████████▊ | 884/1000 [20:58<02:51,  1.48s/it]

[883] Raw: '1

[We are working to reduce our' → Cleaned: 1

 88%|████████▊ | 885/1000 [20:59<02:45,  1.44s/it]

[884] Raw: '1
Reference:  [We are also' → Cleaned: 1

 89%|████████▊ | 886/1000 [21:01<02:42,  1.42s/it]

[885] Raw: '3
Reference: 3 = social =' → Cleaned: None

 89%|████████▊ | 887/1000 [21:02<02:38,  1.40s/it]

[886] Raw: '0 Labels: 0 [The 201' → Cleaned: 0

 89%|████████▉ | 888/1000 [21:04<02:35,  1.39s/it]

[887] Raw: '2
Reference: 2 for non-es' → Cleaned: 2

 89%|████████▉ | 889/1000 [21:05<02:32,  1.38s/it]

[888] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 89%|████████▉ | 890/1000 [21:06<02:30,  1.37s/it]

[889] Raw: '3
Reference: 3 = social =' → Cleaned: None

 89%|████████▉ | 891/1000 [21:08<02:40,  1.48s/it]

[890] Raw: '3

[We are working to reduce our' → Cleaned: None

 89%|████████▉ | 892/1000 [21:10<02:44,  1.52s/it]

[891] Raw: '3
Refer: 0
Volatility' → Cleaned: 0

 89%|████████▉ | 893/1000 [21:11<02:37,  1.47s/it]

[892] Raw: '1
Reference:  [The Company's' → Cleaned: 1

 89%|████████▉ | 894/1000 [21:12<02:32,  1.44s/it]

[893] Raw: '2
[The Company's operating loss for' → Cleaned: 2

 90%|████████▉ | 895/1000 [21:14<02:28,  1.41s/it]

[894] Raw: '2
Reference:  [We are also' → Cleaned: 2

 90%|████████▉ | 896/1000 [21:15<02:24,  1.39s/it]

[895] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 90%|████████▉ | 897/1000 [21:16<02:22,  1.38s/it]

[896] Raw: '3
Reference: 3 = social =' → Cleaned: None

 90%|████████▉ | 898/1000 [21:18<02:20,  1.38s/it]

[897] Raw: '2
[We have a long-standing commitment' → Cleaned: 2

 90%|████████▉ | 899/1000 [21:19<02:20,  1.39s/it]

[898] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

 90%|█████████ | 900/1000 [21:21<02:30,  1.50s/it]

[899] Raw: '3
Reference: 3 = social =' → Cleaned: None

 90%|█████████ | 901/1000 [21:22<02:25,  1.47s/it]

[900] Raw: '3
Labels: 0, 1' → Cleaned: 0

 90%|█████████ | 902/1000 [21:24<02:20,  1.43s/it]

[901] Raw: '2
Tags: none

[The Company' → Cleaned: 2

 90%|█████████ | 903/1000 [21:25<02:16,  1.40s/it]

[902] Raw: '2
Reference: 3
[The' → Cleaned: 2

 90%|█████████ | 904/1000 [21:26<02:12,  1.39s/it]

[903] Raw: '0 read more »
[The Company’s Board' → Cleaned: 0

 90%|█████████ | 905/1000 [21:28<02:10,  1.38s/it]

[904] Raw: '1
Reference:  [We are also' → Cleaned: 1

 91%|█████████ | 906/1000 [21:29<02:08,  1.37s/it]

[905] Raw: '3
Reference: 3 for the amount' → Cleaned: None

 91%|█████████ | 907/1000 [21:30<02:07,  1.37s/it]

[906] Raw: '2
Reference: 3
 =' → Cleaned: 2

 91%|█████████ | 908/1000 [21:32<02:13,  1.45s/it]

[907] Raw: '2 Labels: 2
Text:' → Cleaned: 2

 91%|█████████ | 909/1000 [21:34<02:20,  1.55s/it]

[908] Raw: '3
Labels: free-text, esg' → Cleaned: None

 91%|█████████ | 910/1000 [21:35<02:13,  1.49s/it]

[909] Raw: '1
Reference: 1
 =' → Cleaned: 1

 91%|█████████ | 911/1000 [21:37<02:08,  1.45s/it]

[910] Raw: '1

[We have a long-standing commitment' → Cleaned: 1

 91%|█████████ | 912/1000 [21:38<02:05,  1.42s/it]

[911] Raw: '2 = 0.0005 =' → Cleaned: 2

 91%|█████████▏| 913/1000 [21:39<02:02,  1.40s/it]

[912] Raw: '1
['We are working with our suppliers' → Cleaned: 1

 91%|█████████▏| 914/1000 [21:41<01:59,  1.39s/it]

[913] Raw: '0
Reference: 0
Has text' → Cleaned: 0

 92%|█████████▏| 915/1000 [21:42<01:57,  1.38s/it]

[914] Raw: '1
Reference: 1
[The' → Cleaned: 1

 92%|█████████▏| 916/1000 [21:43<01:54,  1.37s/it]

[915] Raw: '3
Reference: 3 = social =' → Cleaned: None

 92%|█████████▏| 917/1000 [21:45<02:02,  1.47s/it]

[916] Raw: '0

[The Company has a long-standing' → Cleaned: 0

 92%|█████████▏| 918/1000 [21:47<02:03,  1.51s/it]

[917] Raw: '3
Reference: 3 = social' → Cleaned: None

 92%|█████████▏| 919/1000 [21:48<01:58,  1.46s/it]

[918] Raw: '3

[We are working with our suppliers' → Cleaned: None

 92%|█████████▏| 920/1000 [21:49<01:53,  1.42s/it]

[919] Raw: '2

[The Company's operating segments are' → Cleaned: 2

 92%|█████████▏| 921/1000 [21:51<01:50,  1.40s/it]

[920] Raw: '1
['We are also working with our' → Cleaned: 1

 92%|█████████▏| 922/1000 [21:52<01:47,  1.38s/it]

[921] Raw: '1
Reference:  [Cabot’s' → Cleaned: 1

 92%|█████████▏| 923/1000 [21:53<01:45,  1.37s/it]

[922] Raw: '2

[The Company's proven and developed' → Cleaned: 2

 92%|█████████▏| 924/1000 [21:55<01:43,  1.37s/it]

[923] Raw: '2
['We are also working with the' → Cleaned: 2

 92%|█████████▎| 925/1000 [21:56<01:42,  1.36s/it]

[924] Raw: '3
Labels: 0 (environmental' → Cleaned: 0

 93%|█████████▎| 926/1000 [21:58<01:49,  1.48s/it]

[925] Raw: '2
Reference: 2
Tags:' → Cleaned: 2

 93%|█████████▎| 927/1000 [21:59<01:47,  1.47s/it]

[926] Raw: '1

[We are working to reduce our' → Cleaned: 1

 93%|█████████▎| 928/1000 [22:01<01:44,  1.45s/it]

[927] Raw: '0
Tags: environmental Attributes: environmental =' → Cleaned: 0

 93%|█████████▎| 929/1000 [22:02<01:41,  1.42s/it]

[928] Raw: '2 = 0.0005 =' → Cleaned: 2

 93%|█████████▎| 930/1000 [22:03<01:38,  1.41s/it]

[929] Raw: '3
Reference: 3 = social =' → Cleaned: None

 93%|█████████▎| 931/1000 [22:05<01:36,  1.40s/it]

[930] Raw: '0
[The Company has a significant amount' → Cleaned: 0

 93%|█████████▎| 932/1000 [22:06<01:34,  1.39s/it]

[931] Raw: '2 = 0.0333 =' → Cleaned: 2

 93%|█████████▎| 933/1000 [22:08<01:32,  1.38s/it]

[932] Raw: '0

[We are working to reduce our' → Cleaned: 0

 93%|█████████▎| 934/1000 [22:09<01:33,  1.42s/it]

[933] Raw: '1
[The Company’s consolidated financial statements' → Cleaned: 1

 94%|█████████▎| 935/1000 [22:11<01:39,  1.53s/it]

[934] Raw: '3

[The Company has a long-standing' → Cleaned: None

 94%|█████████▎| 936/1000 [22:12<01:34,  1.48s/it]

[935] Raw: '2
Reference: 0
Other text' → Cleaned: 2

 94%|█████████▎| 937/1000 [22:14<01:30,  1.44s/it]

[936] Raw: '2

[The Company's Board of Directors' → Cleaned: 2

 94%|█████████▍| 938/1000 [22:15<01:27,  1.41s/it]

[937] Raw: '0 Labels: 0 = 1' → Cleaned: 0

 94%|█████████▍| 939/1000 [22:16<01:25,  1.40s/it]

[938] Raw: '2
['We are also working with our' → Cleaned: 2

 94%|█████████▍| 940/1000 [22:18<01:22,  1.38s/it]

[939] Raw: '2
Reference: 0
 =' → Cleaned: 2

 94%|█████████▍| 941/1000 [22:19<01:20,  1.37s/it]

[940] Raw: '3
Refer: 3 for social =' → Cleaned: None

 94%|█████████▍| 942/1000 [22:20<01:19,  1.36s/it]

[941] Raw: '0
Reference: 0' → Cleaned: 0

 94%|█████████▍| 943/1000 [22:22<01:23,  1.46s/it]

[942] Raw: '3
Labels: esg 0 (' → Cleaned: 0

 94%|█████████▍| 944/1000 [22:24<01:24,  1.51s/it]

[943] Raw: '3
Reference: 3 = social,' → Cleaned: None

 94%|█████████▍| 945/1000 [22:25<01:20,  1.46s/it]

[944] Raw: '2
Reference: 3
 =' → Cleaned: 2

 95%|█████████▍| 946/1000 [22:26<01:17,  1.43s/it]

[945] Raw: '0 read more » [The new Ford Focus' → Cleaned: 0

 95%|█████████▍| 947/1000 [22:28<01:14,  1.41s/it]

[946] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 95%|█████████▍| 948/1000 [22:29<01:12,  1.39s/it]

[947] Raw: '2
Refer: 3
Touch:' → Cleaned: 2

 95%|█████████▍| 949/1000 [22:30<01:10,  1.39s/it]

[948] Raw: '2 = 0.0333 =' → Cleaned: 2

 95%|█████████▌| 950/1000 [22:32<01:08,  1.37s/it]

[949] Raw: '0
Reference: 0
Other text' → Cleaned: 0

 95%|█████████▌| 951/1000 [22:33<01:06,  1.36s/it]

[950] Raw: '3
Reference:  [We are also' → Cleaned: None

 95%|█████████▌| 952/1000 [22:35<01:10,  1.48s/it]

[951] Raw: '2
Reference: 3
 =' → Cleaned: 2

 95%|█████████▌| 953/1000 [22:36<01:09,  1.47s/it]

[952] Raw: '3
Reference: 3 = social =' → Cleaned: None

 95%|█████████▌| 954/1000 [22:38<01:06,  1.44s/it]

[953] Raw: '3
Reference: 0
 =' → Cleaned: 0

 96%|█████████▌| 955/1000 [22:39<01:03,  1.41s/it]

[954] Raw: '2
Reference: 3' → Cleaned: 2

 96%|█████████▌| 956/1000 [22:40<01:01,  1.39s/it]

[955] Raw: '3
Reference: 3 = social =' → Cleaned: None

 96%|█████████▌| 957/1000 [22:42<00:59,  1.37s/it]

[956] Raw: '0 Labels: 0 = 1' → Cleaned: 0

 96%|█████████▌| 958/1000 [22:43<00:57,  1.37s/it]

[957] Raw: '2
Refer: 2 for non-es' → Cleaned: 2

 96%|█████████▌| 959/1000 [22:44<00:55,  1.36s/it]

[958] Raw: '3
Reference:  Ford Driving Skills for' → Cleaned: None

 96%|█████████▌| 960/1000 [22:46<00:55,  1.39s/it]

[959] Raw: '0
[The Company’s Board of Directors' → Cleaned: 0

 96%|█████████▌| 961/1000 [22:48<00:59,  1.51s/it]

[960] Raw: '2
Tags: financials Share: None' → Cleaned: 2

 96%|█████████▌| 962/1000 [22:49<00:55,  1.47s/it]

[961] Raw: '2
Tags: turnaround, USGC,' → Cleaned: 2

 96%|█████████▋| 963/1000 [22:50<00:53,  1.44s/it]

[962] Raw: '2
Reference: 3
 =' → Cleaned: 2

 96%|█████████▋| 964/1000 [22:52<00:50,  1.41s/it]

[963] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 96%|█████████▋| 965/1000 [22:53<00:48,  1.40s/it]

[964] Raw: '3
Reference: 3 = social =' → Cleaned: None

 97%|█████████▋| 966/1000 [22:54<00:47,  1.38s/it]

[965] Raw: '2
Reference:  [The Company's' → Cleaned: 2

 97%|█████████▋| 967/1000 [22:56<00:45,  1.37s/it]

[966] Raw: '0
Reference: 0
 =' → Cleaned: 0

 97%|█████████▋| 968/1000 [22:57<00:43,  1.37s/it]

[967] Raw: '0
Reference: 0
Label:' → Cleaned: 0

 97%|█████████▋| 969/1000 [22:59<00:45,  1.46s/it]

[968] Raw: '2
Reference:  [We are also' → Cleaned: 2

 97%|█████████▋| 970/1000 [23:01<00:45,  1.53s/it]

[969] Raw: '2
Refer: 2 for non-es' → Cleaned: 2

 97%|█████████▋| 971/1000 [23:02<00:42,  1.48s/it]

[970] Raw: '2
Tags: securitizations,' → Cleaned: 2

 97%|█████████▋| 972/1000 [23:03<00:40,  1.45s/it]

[971] Raw: '3
Reference: 3 for social.' → Cleaned: None

 97%|█████████▋| 973/1000 [23:05<00:38,  1.43s/it]

[972] Raw: '2 = 0.0005 =' → Cleaned: 2

 97%|█████████▋| 974/1000 [23:06<00:36,  1.41s/it]

[973] Raw: '3
Labels: 0 (environmental' → Cleaned: 0

 98%|█████████▊| 975/1000 [23:07<00:34,  1.40s/it]

[974] Raw: '2

[We are working to reduce our' → Cleaned: 2

 98%|█████████▊| 976/1000 [23:09<00:33,  1.38s/it]

[975] Raw: '3
Reference: 3 for the numerical' → Cleaned: None

 98%|█████████▊| 977/1000 [23:10<00:31,  1.37s/it]

[976] Raw: '2

[The Company's consolidated financial statements' → Cleaned: 2

 98%|█████████▊| 978/1000 [23:12<00:32,  1.49s/it]

[977] Raw: '2
Labels: esg-classification,' → Cleaned: 2

 98%|█████████▊| 979/1000 [23:13<00:31,  1.48s/it]

[978] Raw: '2
Tags: financials = 2' → Cleaned: 2

 98%|█████████▊| 980/1000 [23:15<00:28,  1.45s/it]

[979] Raw: '3
Refer: 3 for social.' → Cleaned: None

 98%|█████████▊| 981/1000 [23:16<00:26,  1.42s/it]

[980] Raw: '1
Reference: 1 = governance' → Cleaned: 1

 98%|█████████▊| 982/1000 [23:17<00:25,  1.40s/it]

[981] Raw: '0
Reference: 0' → Cleaned: 0

 98%|█████████▊| 983/1000 [23:19<00:23,  1.39s/it]

[982] Raw: '3
Refer: [Ford has been working' → Cleaned: None

 98%|█████████▊| 984/1000 [23:20<00:21,  1.37s/it]

[983] Raw: '1

[The Company's Board of Directors' → Cleaned: 1

 98%|█████████▊| 985/1000 [23:21<00:20,  1.36s/it]

[984] Raw: '2
Reference:  [The Revolving' → Cleaned: 2

 99%|█████████▊| 986/1000 [23:23<00:19,  1.39s/it]

[985] Raw: '2
Reference: 2
 =' → Cleaned: 2

 99%|█████████▊| 987/1000 [23:25<00:19,  1.52s/it]

[986] Raw: '3
Reference: 3 = 12' → Cleaned: None

 99%|█████████▉| 988/1000 [23:26<00:17,  1.47s/it]

[987] Raw: '2
Reference: 3
Other income' → Cleaned: 2

 99%|█████████▉| 989/1000 [23:27<00:15,  1.43s/it]

[988] Raw: '0
Reference: 3
[The' → Cleaned: 0

 99%|█████████▉| 990/1000 [23:29<00:14,  1.40s/it]

[989] Raw: '1
Reference: 1
Topic:' → Cleaned: 1

 99%|█████████▉| 991/1000 [23:30<00:12,  1.39s/it]

[990] Raw: '3
Reference: 3 = social =' → Cleaned: None

 99%|█████████▉| 992/1000 [23:31<00:11,  1.39s/it]

[991] Raw: '2
[We have a long-standing commitment' → Cleaned: 2

 99%|█████████▉| 993/1000 [23:33<00:09,  1.38s/it]

[992] Raw: '1
[The Company's Board of Directors' → Cleaned: 1

 99%|█████████▉| 994/1000 [23:34<00:08,  1.38s/it]

[993] Raw: '2
Refer: 0
Refer:' → Cleaned: 2

100%|█████████▉| 995/1000 [23:36<00:07,  1.45s/it]

[994] Raw: '0
Reference: 0
Text:' → Cleaned: 0

100%|█████████▉| 996/1000 [23:38<00:06,  1.52s/it]

[995] Raw: '2
Reference: [UT Automotive's business' → Cleaned: 2

100%|█████████▉| 997/1000 [23:39<00:04,  1.47s/it]

[996] Raw: '1
Reference: 1
['We' → Cleaned: 1

100%|█████████▉| 998/1000 [23:40<00:02,  1.43s/it]

[997] Raw: '2 Labels: 2
Text:' → Cleaned: 2

100%|█████████▉| 999/1000 [23:42<00:01,  1.40s/it]

[998] Raw: '3
Reference: 3 = social' → Cleaned: None

100%|██████████| 1000/1000 [23:43<00:00,  1.42s/it]

[999] Raw: '0 read more » = 0
[' → Cleaned: 0
Overall Accuracy: 0.594
Accuracy for label 0: 0.847
Accuracy for label 1: 1.000
Accuracy for label 2: 0.797
Accuracy for label 3: 0.000
Macro F1-score: 0.476

Classification Report:
              precision    recall  f1-score   support

           0      0.866     0.847     0.856       190
           1      0.090     1.000     0.164        37
           2      0.988     0.797     0.882       497
           3      0.000     0.000     0.000       276

    accuracy                          0.594      1000
   macro avg      0.486     0.661     0.476      1000
weighted avg      0.659     0.594     0.607      1000


Confusion Matrix:
[[161  25   4]
 [  0  37   0]
 [  7  94 396]]

In [ ]:
#old epoch = 1 f1=0.218
#old epoch = 3
#y_pred = predict(test, model, tokenizer)
#evaluate(y_true, y_pred)

In [ ]:
evaluation = pd.DataFrame({'text': X_test["text"],
                           'y_true':y_true,
                           'y_pred': y_pred},
                         )
evaluation.to_csv("test_predictions.csv", index=False)

In [ ]:
print(evaluation)